[apps.blap]
platforms = [
  { value = "{{ $.Config.OS }}", target = "linux" }
]
[apps.blap.github]
project = "seanenck/blap"
release = { asset = "tarball" }
[[apps.blap.setup]]
commands = ["just", "--quiet", "version={{ $.Vars.Tag }}"]
[[apps.blap.setup]]
commands = [
    ["/bin/sh", "-c", "{{ $.Vars.Directories.Working }}$COMPGEN"],
    ["ln", "-sf", "{{ $.Vars.Directories.Working }}/{{ $.Name }}", "$LOCALBIN/"]
]
directory = "target"
