[applications.blap]
platforms = [
  { value = "{{ $.Config.OS }}", target = "linux" }
]
[applications.blap.github]
project = "seanenck/blap"
release = { asset = "tarball" }
[[applications.blap.setup]]
command = ["just", "--quiet", "version={{ $.Vars.Tag }}"]
[[applications.blap.setup]]
command = [
    ["/bin/sh", "-c", "{{ $.Vars.Directories.Working }}$COMPGEN"],
    ["ln", "-sf", "{{ $.Vars.Directories.Working }}/{{ $.Name }}", "$LOCALBIN/"]
]
directory = "target"
