[applications.dotfiles.github]
project = "seanenck/dotfiles"
branch = { name = "master" }
[[applications.dotfiles.setup]]
command = [
    ["./{{ $.Name }}", "--deploy"],
    ["ln", "-sf", "{{ $.Vars.Directories.Root }}/{{ $.Name }}", "$LOCALBIN/"]
]
