[applications.efm-langserver]
platforms = [
  { value = "{{ $.Config.OS }}", target = "linux"}
]
[applications.efm-langserver.github]
project = "mattn/efm-langserver"
release = { asset = "tarball" }
[applications.efm-langserver.commands]
[[applications.efm-langserver.commands.steps]]
command = ["go", "build", "-ldflags", "-X main.revision={{ $.Vars.Tag }}", "-o", "{{ $.Name }}", "."]
[[applications.efm-langserver.commands.steps]]
command = ["ln", "-sf", "{{ $.Vars.Directories.Root }}/{{ $.Name }}", "$LOCALBIN/"]
