[applications.efm.github]
project = "mattn/efm-langserver"
release = { asset = "tarball" }
[applications.efm.commands]
variables = [
  { key = "NAME", value = "efm-langserver" }
]
[[applications.efm.commands.steps]]
command = ["go", "build", "-ldflags", "-X main.revision={{ $.Vars.Tag }}", "-o", "$NAME", "."]
[[applications.efm.commands.steps]]
command = ["ln", "-sf", "{{ $.Vars.Directories.Root }}/$NAME", "$LOCALBIN/"]
