[applications.gittools]
platforms = [
  { value = "{{ $.Config.OS }}", target = "linux" }
]
[applications.gittools.github]
project = "seanenck/git-tools"
release = { asset = "tarball" }
[[applications.gittools.setup]]
command = ["just", "--quiet"]
[[applications.gittools.setup]]
command = ["ln", "-sf", "{{ $.Vars.Directories.Working }}/git-uncommitted", "$LOCALBIN/"]
directory = "target"
[[applications.gittools.setup]]
command = ["ln", "-sf", "{{ $.Vars.Directories.Working }}/git-motd", "$LOCALBIN/"]
directory = "target"
[[applications.gittools.setup]]
command = ["ln", "-sf", "{{ $.Vars.Directories.Working }}/git-current-state", "$LOCALBIN/"]
directory = "target"
