[apps.gittools]
platforms = [
  { value = "{{ $.Config.OS }}", target = "linux" }
]
[apps.gittools.github]
project = "seanenck/git-tools"
release = { asset = "tarball" }
[[apps.gittools.setup]]
commands = ["just", "--quiet"]
[[apps.gittools.setup]]
commands = [
    ["ln", "-sf", "{{ $.Vars.Directories.Working }}/git-uncommitted", "$LOCALBIN/"],
    ["ln", "-sf", "{{ $.Vars.Directories.Working }}/git-motd", "$LOCALBIN/"],
    ["ln", "-sf", "{{ $.Vars.Directories.Working }}/git-current-state", "$LOCALBIN/"]
]
directory = "target"
