[apps.gofumpt]
platforms = [
  { value = "{{ $.Config.OS }}", target = "linux" }
]
[apps.gofumpt.github]
project = "mvdan/gofumpt"
release = { asset = "tarball" }
[[apps.gofumpt.setup]]
commands = [
    ["go", "build", "-trimpath", "-mod=readonly", "-modcacherw"],
    ["ln", "-sf", "{{ $.Vars.Directories.Root }}/{{ $.Name }}", "$LOCALBIN/"]
]
