[applications.gofumpt]
platforms = [
  { value = "{{ $.Config.OS }}", target = "linux" }
]
[applications.gofumpt.github]
project = "mvdan/gofumpt"
release = { asset = "tarball" }
[[applications.gofumpt.commands.steps]]
command = ["go", "build", "-trimpath", "-mod=readonly", "-modcacherw"]
[[applications.gofumpt.commands.steps]]
command = ["ln", "-sf", "{{ $.Vars.Directories.Root }}/{{ $.Name }}", "$LOCALBIN/"]
