[applications.gofumpt]
platforms = [
  { value = "{{ $.Config.OS }}", target = "linux" }
]
[applications.gofumpt.github]
project = "mvdan/gofumpt"
release = { asset = "tarball" }
[[applications.gofumpt.setup]]
command = [
    ["go", "build", "-trimpath", "-mod=readonly", "-modcacherw"],
    ["ln", "-sf", "{{ $.Vars.Directories.Root }}/{{ $.Name }}", "$LOCALBIN/"]
]
