[apps.gopls]
platforms = [
  { value = "{{ $.Config.OS }}", target = "linux" }
]
[apps.gopls.github]
project = "golang/tools"
release = { asset = "tarball" }
[[apps.gopls.setup]]
commands = [
    ["go", "build", "-v", "-buildmode=pie", "-mod=readonly", "-modcacherw", "-ldflags", "-compressdwarf=false", "-o", "{{ $.Name }}"],
    ["ln", "-sf", "{{ $.Vars.Directories.Working }}/{{ $.Name }}", "$LOCALBIN/"]
]
directory = "{{ $.Name }}"
