[applications]
  [applications.gopls]
    [applications.gopls.commands]

      [[applications.gopls.commands.steps]]
        command = ["go", "build", "-v", "-buildmode=pie", "-mod=readonly", "-modcacherw", "-ldflags", "-compressdwarf=false", "-o", "{{ $.Name }}"]
        directory = "{{ $.Name }}"

      [[applications.gopls.commands.steps]]
        command = ["ln", "-sf", "{{ $.Vars.Directories.Working }}/{{ $.Name }}", "$LOCALBIN/"]
        directory = "{{ $.Name }}"
    [applications.gopls.github]
      project = "golang/tools"
      [applications.gopls.github.release]
        asset = "tarball"
