[applications.gopls]
platforms = [
  { value = "{{ $.Config.OS }}", target = "linux" }
]
[applications.gopls.github]
project = "golang/tools"
release = { asset = "tarball" }
[[applications.gopls.setup]]
command = ["go", "build", "-v", "-buildmode=pie", "-mod=readonly", "-modcacherw", "-ldflags", "-compressdwarf=false", "-o", "{{ $.Name }}"]
directory = "{{ $.Name }}"
[[applications.gopls.setup]]
command = ["ln", "-sf", "{{ $.Vars.Directories.Working }}/{{ $.Name }}", "$LOCALBIN/"]
directory = "{{ $.Name }}"
