[apps.lb]
platforms = [
  { value = "{{ $.Config.OS }}", target = "linux" }
]
[apps.lb.github]
project = "seanenck/lockbox"
release = { asset = "tarball" }
[[apps.lb.setup]]
commands = ["just", "--quiet", "version={{ $.Vars.Tag }}"]
[[apps.lb.setup]]
commands = [
    ["/bin/sh", "-c", "{{ $.Vars.Directories.Working }}$COMPGEN"],
    ["ln", "-sf", "{{ $.Vars.Directories.Working }}/{{ $.Name }}", "$LOCALBIN/"]
]
directory = "target"
