[applications.lb]
platforms = [
  { value = "{{ $.Config.OS }}", target = "linux" }
]
[applications.lb.github]
project = "seanenck/lockbox"
release = { asset = "tarball" }
[[applications.lb.commands.steps]]
command = ["just", "--quiet", "version={{ $.Vars.Tag }}"]
[[applications.lb.commands.steps]]
command = ["/bin/sh", "-c", "{{ $.Vars.Directories.Working }}$COMPGEN"]
directory = "target"
[[applications.lb.commands.steps]]
command = ["ln", "-sf", "{{ $.Vars.Directories.Working }}/{{ $.Name }}", "$LOCALBIN/"]
directory = "target"
