[apps.revive]
platforms = [
  { value = "{{ $.Config.OS }}", target = "linux" }
]
[apps.revive.github]
project = "mgechev/revive"
release = { asset = "tarball" }
[[apps.revive.setup]]
commands = [
    ["go", "build", "-buildmode=pie", "-trimpath", "-modcacherw"],
    ["ln", "-sf", "{{ $.Vars.Directories.Root }}/{{ $.Name }}", "$LOCALBIN/"]
]
