[applications.revive]
platforms = [
  { value = "{{ $.Config.OS }}", target = "linux" }
]
[applications.revive.github]
project = "mgechev/revive"
release = { asset = "tarball" }
[[applications.revive.commands.steps]]
command = ["go", "build", "-buildmode=pie", "-trimpath", "-modcacherw"]
[[applications.revive.commands.steps]]
command = ["ln", "-sf", "{{ $.Vars.Directories.Root }}/{{ $.Name }}", "$LOCALBIN/"]
