[apps.staticcheck]
platforms = [
  { value = "{{ $.Config.OS }}", target = "linux" }
]
[apps.staticcheck.github]
project = "dominikh/go-tools"
release = { asset = "tarball" }
[[apps.staticcheck.setup]]
commands = ["go", "build", "-v", "-mod=readonly", "-modcacherw", "-ldflags", "-compressdwarf=false", "-o", "{{ $.Name }}", "./cmd/{{ $.Name }}"]
[[apps.staticcheck.setup]]
commands = ["ln", "-sf", "{{ $.Vars.Directories.Working }}/{{ $.Name }}", "$LOCALBIN/"]
directory = "{{ $.Name }}"
