[applications.staticcheck]
platforms = [
  { value = "{{ $.Config.OS }}", target = "linux" }
]
[applications.staticcheck.github]
project = "dominikh/go-tools"
release = { asset = "tarball" }
[applications.staticcheck.commands]
variables = [
    { key = "CACHE", value = "$HOME/.cache/staticcheck" },
]
[[applications.staticcheck.commands.steps]]
command = ["go", "build", "-v", "-mod=readonly", "-modcacherw", "-ldflags", "-compressdwarf=false", "-o", "{{ $.Name }}", "./cmd/{{ $.Name }}"]
[[applications.staticcheck.commands.steps]]
command = ["ln", "-sf", "{{ $.Vars.Directories.Working }}/{{ $.Name }}", "$LOCALBIN/"]
directory = "{{ $.Name }}"
[[applications.staticcheck.commands.steps]]
command = ["/bin/sh", "-c", "test ! -d $CACHE || find $CACHE -type f -mtime +1 -print"]
