#!/bin/bash

# args == status bar
if [ ! -z "$1" ]; then
    # Send the header so that i3bar knows we want to use JSON:
    echo '{"version":1}'

    # Begin the endless array.
    echo '['

    # We send an empty first array of blocks to make the loop simpler:
    echo '[],'
fi

# Now send blocks with information forever:
source $HOME/.config/home/common
export USER_TMP
export HOME_BIN
export STATUS_RESET
export SYS_ONLINE
exec lua5.3 $HOME/.local/bin/status.lua $1
