[applications.alpinevirt]
platforms = [
  { value = "{{ $.Config.OS }}-$HOST_OS", target = "linux-alpine" },
  { value = "{{ $.Config.OS }}-$HOST_OS", target = "linux-cusp" }
]
[applications.alpinevirt.github]
project = "alpinelinux/aports"
branch = { name = "3.20-stable" }
[[applications.alpinevirt.commands.steps]]
command = ["/bin/bash", "-c", "diff --ignore-all-space -u <(grep -E '^(pkgver|pkgrel)=' APKBUILD | sort -r | cut -d '=' -f 2 | tr '\n' '-' | sed 's/$/virt/g') <(uname -r)"]
directory = "main/linux-lts"
