[applications]
  [applications.alpine]
    [applications.alpine.extract]
      skip = true
    [applications.alpine.git]
      repository = "https://github.com/alpinelinux/aports"
      [applications.alpine.git.tagged]
        download = "https://dl-cdn.alpinelinux.org/alpine/v{{ $.Vars.Tag.Major }}.{{ $.Vars.Tag.Minor }}/releases/aarch64/alpine-standard-{{ $.Vars.Tag.Version }}-aarch64.iso.sha256"
        filters = ["refs/tags/weekly", "refs/tags/release", "v[1-2][0-9][0-9][0-9][0-9][0-9]", "{}"]
