[applications.fedoraimage]
platforms = [
  { value = "{{ $.Config.OS }}-$HOST_OS", target = "linux-fedora" }
]
[applications.fedoraimage.github]
project = "seanenck/workstation-builds"
branch = { name = "master" }
[[applications.fedoraimage.commands.steps]]
command = ["just", "hash={{ $.Vars.Tag }}", "needs"]
