[applications]
  [applications.fedoraimage]
    [applications.fedoraimage.commands]

      [[applications.fedoraimage.commands.steps]]
        command = ["just", "hash={{ $.Vars.Tag }}", "needs"]
    [applications.fedoraimage.github]
      project = "seanenck/workstation-builds"
      [applications.fedoraimage.github.branch]
        name = "master"
