[applications]
  [applications.nvimcmp]
    [applications.nvimcmp.commands]

      [[applications.nvimcmp.commands.steps]]
        command = ["rsync", "-ac", "--delete-after", ".", "$NVIM_PLUGINS/nvim-cmp/"]
    [applications.nvimcmp.github]
      project = "hrsh7th/nvim-cmp"
      [applications.nvimcmp.github.branch]
        name = "main"
  [applications.nvimcmplsp]
    [applications.nvimcmplsp.commands]

      [[applications.nvimcmplsp.commands.steps]]
        command = ["rsync", "-ac", "--delete-after", ".", "$NVIM_PLUGINS/cmp-nvim-lsp/"]
    [applications.nvimcmplsp.github]
      project = "hrsh7th/cmp-nvim-lsp"
      [applications.nvimcmplsp.github.branch]
        name = "main"
  [applications.nvimlspconfig]
    [applications.nvimlspconfig.commands]

      [[applications.nvimlspconfig.commands.steps]]
        command = ["rsync", "-ac", "--delete-after", ".", "$NVIM_PLUGINS/nvim-lspconfig/"]
    [applications.nvimlspconfig.github]
      project = "neovim/nvim-lspconfig"
      [applications.nvimlspconfig.github.branch]
        name = "master"
  [applications.nvimluasnip]
    [applications.nvimluasnip.commands]

      [[applications.nvimluasnip.commands.steps]]
        command = ["rsync", "-ac", "--delete-after", ".", "$NVIM_PLUGINS/LuaSnip/"]
    [applications.nvimluasnip.github]
      project = "L3MON4D3/LuaSnip"
      [applications.nvimluasnip.github.branch]
        name = "master"
  [applications.nvimscrollbar]
    [applications.nvimscrollbar.commands]

      [[applications.nvimscrollbar.commands.steps]]
        command = ["rsync", "-ac", "--delete-after", ".", "$NVIM_PLUGINS/nvim-scrollbar/"]
    [applications.nvimscrollbar.github]
      project = "petertriho/nvim-scrollbar"
      [applications.nvimscrollbar.github.branch]
        name = "main"
  [applications.vimairline]
    [applications.vimairline.commands]

      [[applications.vimairline.commands.steps]]
        command = ["rsync", "-ac", "--delete-after", ".", "$NVIM_PLUGINS/vim-airline/"]
    [applications.vimairline.github]
      project = "vim-airline/vim-airline"
      [applications.vimairline.github.branch]
        name = "master"
  [applications.vimjust]
    [applications.vimjust.commands]

      [[applications.vimjust.commands.steps]]
        command = ["rsync", "-ac", "--delete-after", ".", "$NVIM_PLUGINS/vim-just/"]
    [applications.vimjust.github]
      project = "NoahTheDuke/vim-just"
      [applications.vimjust.github.branch]
        name = "main"
