[applications.nvimcmp.github]
project = "hrsh7th/nvim-cmp"
branch = { name = "main" }
[[applications.nvimcmp.commands.steps]]
command = ["rsync", "-ac", "--delete-after", ".", "$NVIM_PLUGINS/nvim-cmp/"]

[applications.nvimcmplsp.github]
project = "hrsh7th/cmp-nvim-lsp"
branch = { name = "main" }
[[applications.nvimcmplsp.commands.steps]]
command = ["rsync", "-ac", "--delete-after", ".", "$NVIM_PLUGINS/cmp-nvim-lsp/"]

[applications.nvimlspconfig.github]
project = "neovim/nvim-lspconfig"
branch = { name = "master" }
[[applications.nvimlspconfig.commands.steps]]
command = ["rsync", "-ac", "--delete-after", ".", "$NVIM_PLUGINS/nvim-lspconfig/"]

[applications.nvimluasnip.github]
project = "L3MON4D3/LuaSnip"
branch = { name = "master" }
[[applications.nvimluasnip.commands.steps]]
command = ["rsync", "-ac", "--delete-after", ".", "$NVIM_PLUGINS/LuaSnip/"]

[applications.nvimscrollbar.github]
project = "petertriho/nvim-scrollbar"
branch = { name = "main" }
[[applications.nvimscrollbar.commands.steps]]
command = ["rsync", "-ac", "--delete-after", ".", "$NVIM_PLUGINS/nvim-scrollbar/"]

[applications.vimairline.github]
project = "vim-airline/vim-airline"
branch = { name = "master" }
[[applications.vimairline.commands.steps]]
command = ["rsync", "-ac", "--delete-after", ".", "$NVIM_PLUGINS/vim-airline/"]

[applications.vimjust.github]
project = "NoahTheDuke/vim-just"
branch = { name = "main" }
[[applications.vimjust.commands.steps]]
command = ["rsync", "-ac", "--delete-after", ".", "$NVIM_PLUGINS/vim-just/"]
