[applications]
  [applications.rectangle]
    [applications.rectangle.extract]
      skip = true
    [applications.rectangle.github]
      project = "rxhanson/Rectangle"
      [applications.rectangle.github.release]
        asset = ".dmg$"
