[applications.utm]
platforms = [
  { value = "{{ $.Config.OS }}", target = "darwin" }
]
[applications.utm.github]
project = "utmapp/UTM"
release = { asset = ".dmg$" }
[applications.utm.extract]
skip = true
