[applications.nvimcmp]
platforms = [
  { value = "{{ $.Config.OS }}-$EDITOR", target = "linux-nvim" }
]
[applications.nvimcmp.github]
project = "hrsh7th/nvim-cmp"
branch = { name = "main" }
[[applications.nvimcmp.commands.steps]]
command = ["rsync", "-ac", "--delete-after", ".", "$VIM_PLUGINS/nvim-cmp/"]

[applications.nvimcmplsp]
platforms = [
  { value = "{{ $.Config.OS }}-$EDITOR", target = "linux-nvim" }
]
[applications.nvimcmplsp.github]
project = "hrsh7th/cmp-nvim-lsp"
branch = { name = "main" }
[[applications.nvimcmplsp.commands.steps]]
command = ["rsync", "-ac", "--delete-after", ".", "$VIM_PLUGINS/cmp-nvim-lsp/"]

[applications.nvimluasnip]
platforms = [
  { value = "{{ $.Config.OS }}-$EDITOR", target = "linux-nvim" }
]
[applications.nvimluasnip.github]
project = "L3MON4D3/LuaSnip"
branch = { name = "master" }
[[applications.nvimluasnip.commands.steps]]
command = ["rsync", "-ac", "--delete-after", ".", "$VIM_PLUGINS/LuaSnip/"]

[applications.nvimscrollbar]
platforms = [
  { value = "{{ $.Config.OS }}-$EDITOR", target = "linux-nvim" }
]
[applications.nvimscrollbar.github]
project = "petertriho/nvim-scrollbar"
branch = { name = "main" }
[[applications.nvimscrollbar.commands.steps]]
command = ["rsync", "-ac", "--delete-after", ".", "$VIM_PLUGINS/nvim-scrollbar/"]

[applications.vimairline]
platforms = [
  { value = "{{ $.Config.OS }}", target = "linux" }
]
[applications.vimairline.github]
project = "vim-airline/vim-airline"
branch = { name = "master" }
[[applications.vimairline.commands.steps]]
command = ["rsync", "-ac", "--delete-after", ".", "$VIM_PLUGINS/vim-airline/"]

[applications.vimjust]
platforms = [
  { value = "{{ $.Config.OS }}", target = "linux" }
]
[applications.vimjust.github]
project = "NoahTheDuke/vim-just"
branch = { name = "main" }
[[applications.vimjust.commands.steps]]
command = ["rsync", "-ac", "--delete-after", ".", "$VIM_PLUGINS/vim-just/"]

[applications.toggleterm]
platforms = [
  { value = "{{ $.Config.OS }}-$EDITOR", target = "linux-nvim" }
]
[applications.toggleterm.github]
project = "akinsho/toggleterm.nvim"
branch = { name = "main" }
[[applications.toggleterm.commands.steps]]
command = ["rsync", "-ac", "--delete-after", ".", "$VIM_PLUGINS/toggleterm/"]

[applications.ale]
platforms = [
  { value = "{{ $.Config.OS }}-$EDITOR", target = "linux-vim" }
]
[applications.ale.github]
project = "dense-analysis/ale"
branch = { name = "master" }
[[applications.ale.commands.steps]]
command = ["rsync", "-ac", "--delete-after", ".", "$VIM_PLUGINS/ale/"]
