[applications.nvimscrollbar]
platforms = [
  { value = "{{ $.Config.OS }}-$EDITOR", target = "linux-nvim" }
]
[applications.nvimscrollbar.github]
project = "petertriho/nvim-scrollbar"
branch = { name = "main" }
[[applications.nvimscrollbar.commands.steps]]
command = ["rsync", "-ac", "--delete-after", ".", "$VIM_PLUGINS/nvim-scrollbar/"]

[applications.vimairline]
platforms = [
  { value = "{{ $.Config.OS }}", target = "linux" }
]
[applications.vimairline.github]
project = "vim-airline/vim-airline"
branch = { name = "master" }
[[applications.vimairline.commands.steps]]
command = ["rsync", "-ac", "--delete-after", ".", "$VIM_PLUGINS/vim-airline/"]

[applications.vimjust]
platforms = [
  { value = "{{ $.Config.OS }}", target = "linux" }
]
[applications.vimjust.github]
project = "NoahTheDuke/vim-just"
branch = { name = "main" }
[[applications.vimjust.commands.steps]]
command = ["rsync", "-ac", "--delete-after", ".", "$VIM_PLUGINS/vim-just/"]

[applications.toggleterm]
platforms = [
  { value = "{{ $.Config.OS }}-$EDITOR", target = "linux-nvim" }
]
[applications.toggleterm.github]
project = "akinsho/toggleterm.nvim"
branch = { name = "main" }
[[applications.toggleterm.commands.steps]]
command = ["rsync", "-ac", "--delete-after", ".", "$VIM_PLUGINS/toggleterm/"]

[applications.ale]
platforms = [
  { value = "{{ $.Config.OS }}-$EDITOR", target = "linux-vim" }
]
[applications.ale.github]
project = "dense-analysis/ale"
branch = { name = "master" }
[[applications.ale.commands.steps]]
command = ["rsync", "-ac", "--delete-after", ".", "$VIM_PLUGINS/ale/"]

[applications.mini-completion]
platforms = [
  { value = "{{ $.Config.OS }}-$EDITOR", target = "linux-nvim" }
]
[applications.mini-completion.github]
project = "echasnovski/mini.completion"
branch = { name = "main" }
[[applications.mini-completion.commands.steps]]
command = ["rsync", "-ac", "--delete-after", ".", "$VIM_PLUGINS/mini.completion/"]
