#!/usr/bin/env bash
glint() {
  gofumpt -l $(find . -type f -name "*.go") 2>&1 | sed "s/^/[gofumpt]    -> /g"
  staticcheck -checks all ./... 2>&1 | sed "s/^/[staticcheck] -> /g"
  go vet ./... 2>&1 | sed "s/^/[govet]       -> /g"
}

glint
