#!/usr/bin/env bash
CONF="$HOME/.config/pkgs/"
CACHE="$HOME/.cache/pkgs/"
if [ -z "$1" ]; then
	echo "option required"
	exit 1
fi
if [ "$1" == "--list" ]; then
	ls "$CONF/src"
	echo "clean"
	exit 0
fi
if [ ! -e "$CONF/src/$1" ]; then
	if [ "$1" != "clean" ]; then
		echo "invalid package"
		exit 1
	fi
fi
mkdir -p $CACHE
rsync -avc $CONF/ $CACHE
if ! (cd $CACHE && make $1); then
	exit 1
fi