#!/bin/bash

if [ $IS_SCHROOT -eq 0 ]; then
    if [ ! -e /var/lib/systemd/linger/enck ]; then
        echo "sudo loginctl enable-linger"
    fi

    MUTT=$HOME/.mutt
    if [ -d $MUTT ]; then
        if [ -e $START_MUTT ]; then
            rm -f $START_MUTT
            mutt -F $HOME/.mutt/fastmail.muttrc
            exit 0
        fi
    else
        echo "no .mutt folder"
    fi

    twtui.app() {
        taskwarrior-tui
    }

    _services() {
        systemctl --user enable --now drudge-session@mail.service
        systemctl --user start drudge-session@messaging.service
    }

    _services
else
    PS1='[\u@${SCHROOT_CHROOT_NAME} \W]\$ '
fi
