#!/bin/bash

if [ -d "$HOME/.gnupg" ]; then
    unset SSH_AGENT_PID
    if [ "${gnupg_SSH_AUTH_SOCK_by:-0}" -ne $$ ]; then
        export SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"
    fi

    export GPG_TTY=$(tty)
    gpg-connect-agent updatestartuptty /bye >/dev/null
else
    echo "no .gnupg dir"
fi

if [ ! -e /var/lib/systemd/linger/enck ]; then
    echo "sudo loginctl enable-linger"
fi

MUTT=$HOME/.mutt
if [ -d $MUTT ]; then
    if [ -e $START_MUTT ]; then
        rm -f $START_MUTT
        mutt -F $HOME/.mutt/fastmail.muttrc
        exit 0
    fi
else
    echo "no .mutt folder"
fi

if [ ! -z "$SCHROOT_CHROOT_NAME" ]; then
    PS1='[\u@${SCHROOT_CHROOT_NAME} \W]\$ '
fi

_services() {
    local check
    check=/tmp/.services.$(date +%Y%m%d)
    if [ -e $check ]; then
        return
    fi
    systemctl is-enabled --user drudge-session@mail.service --quiet
    if [ $? -ne 0 ]; then
        systemctl --user enable --now drudge-session@mail.service
    fi
    touch $check
}

_services

drudge user.mail > ~/.cache/drudge/messages
