#!/bin/bash
PORT_CACHE=$HOME/Library/Caches/ports
PORT_CFG=$HOME/.config/macports/

_vim-plugins() {
    echo "-> update vim plugins"
    for f in "vim-airline/vim-airline" "dense-analysis/ale"; do
        echo "$f"
        p="$HOME/.vim/pack/dist/start/"
        if [ ! -d $p ]; then
            mkdir -p $p
        fi
        p="$p"$(echo $f | cut -d "/" -f 2)
        if [ ! -d $p ]; then
            git clone "https://github.com/$f" $p
        fi
        git -C $p pull
    done
}

_update-tools() {
    local t
    echo "update tooling"
    mkdir -p $HOME/.bin
    mkdir -p $HOME/.completions
    for t in VFTool Lockbox Homedir Macrun; do
        cd $HOME/Source/com.voidedtech.$t && make && make install
    done
    golangci-lint completion bash > $HOME/.completions/golangci-lint.bash
}

_ports() {
    local port stat prev script oldifs name target
    stat=$PORT_CACHE/last
    prev=$stat.prev
    echo "-> install/configure ports"
    oldifs=$IFS
    IFS=$'\n'
    for port in $(cat ${PORT_CFG}install); do
        echo "sudo port install $port" >> $stat
    done
    for port in $(cat ${PORT_CFG}select); do
        name=$(echo $port | cut -d " " -f 1)
        target=$(echo $port | cut -d " " -f 2)
        echo "sudo port select --set $name $target" >> $stat
    done
    IFS=$oldifs
    chmod u+x $stat
    if [ "$(which python)" == "/usr/bin/python" ]; then
        rm $prev
    fi
    touch $prev
    diff -u $prev $stat
    if [ $? -ne 0 ]; then
        $stat
    fi
    mv $stat $prev
}

sys-upgrade() {
    local f p c
    c=$PWD
    echo "-> update ports"
    sudo port selfupdate
    sudo port upgrade outdated
    _ports
    echo "-> cleanup ports"
    sudo port uninstall inactive
    sudo port reclaim
    echo "-> update kitty"
    kitty-updater
    _vim-plugins
    _update-tools
    cd $c
}

mkdir -p $PORT_CACHE
if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
    :
else
    sys-upgrade
fi
