alias python=python3
alias nano=vim
alias vi=vim
alias crypt='mounting crypt'
alias shares='mounting shares'
alias sys-stats-on='subsystem sys-stats enable on'
alias sys-stats-off='subsystem sys-stats enable off'
alias tree='tree .'
alias clear-mail="echo 'd *' | mail -N"
