alias nano=vim
alias vi=vim
alias crypt='mounting crypt'
alias tree='tree .'
alias checksum='find -type f -exec sha512sum "{}" + | sort -k 2'
alias machinectl="sudo machinectl"
alias notes="vim notes"
alias ssid="sudo iwlist wlp3s0 scanning essid"
alias csv-processing="$HOME/.bin/modules/csv-stats/csvstats.sh"
alias xhost-local="xhost +local:"
alias load-keys="mounting keys"
