linters:
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errorlint
    - exportloopref
    - forcetypeassert
    - gci
    - goconst
    - gocritic
    - godot
    - godox
    - goerr113
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - ifshort
    - importas
    - makezero
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - tagliatelle
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - whitespace

linters-settings:
  thelper:
    # The following configurations enable all checks. It can be omitted because all checks are enabled by default.
    # You can enable only required checks deleting unnecessary checks.
    test:
      first: true
      name: true
      begin: false
    benchmark:
      first: true
      name: true
      begin: true
    tb:
      first: true
      name: true
      begin: true
