#!/bin/bash
export BROWSER=firefox-developer-edition
for f in $(find ~/.env/thin/lib/ -name "*.app"); do
    source $f load
done

for f in mumble $BROWSER pavucontrol; do
    alias $f="echo disabled in bash"
done

vlc() {
    /usr/bin/vlc "$@" &
    disown
}

firefox() {
    /usr/bin/$BROWSER "$@" &
    disown
}

_apps() {
    local f b targets host
    targets="$HOME/.env/thin/lib/"
    if [ ! -d $targets ]; then
        mkdir -p $targets
    fi
    for f in $(ls $targets*.app); do
        b=$(basename $f)
        alias $b="bash $f"
    done
}

_apps

if [ -x /usr/bin/sway ]; then
    if [ -z $DISPLAY ] && [ "$(tty)" == "/dev/tty1" ]; then
        export MOZ_ENABLE_WAYLAND=1
        sway > ~/.cache/sway.log 2>&1
        exit
    fi
fi
