FROM alpine:latest

RUN echo "@testing http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
RUN apk add --no-cache mdbook@testing go make git bash
WORKDIR /src/voidedtech.com
RUN make release
