export PATH="$HOME/.env/dotfiles/bin:$PATH"
source $HOME/.env/local/lib/bashrc
export GOPATH="$HOME/.cache/go"
export XDG_RUNTIME_DIR=/tmp/$(id -u)-runtimedir

_sway-start() {
    dbus-launch --exit-with-session sway
}

if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then
    if ! test -d $XDG_RUNTIME_DIR; then
        mkdir $XDG_RUNTIME_DIR
        chmod 0700 $XDG_RUNTIME_DIR
    fi
    _sway-start > $HOME/.cache/sway.log 2>&1 
    exit
fi

_vimclean() {
    local h
    h=$HOME/.vim/$f
    if [ -d "$h" ]; then
        find "$h" -type f -mtime +1 -delete
    fi
}
_vimclean undo
_vimclean swap
_vimclean backup

export GPG_TTY=$(tty)
gpg-connect-agent updatestartuptty /bye > /dev/null 2>&1
bck=$(find /var/cache/backups -mtime -2 | wc -l)
if [ $bck -lt 1 ]; then
    echo
    echo "    -> no recent backup"
    echo
fi
git uncommitted
