#!/bin/bash

for f in mutt mumble $BROWSER pavucontrol schroot makepkg repo-add mkarchroot; do
    alias $f="echo disabled in bash"
done

container() {
    perl ~/.local/lib/containers.pl $@
}

pltidy() {
    local f
    for f in $(git grep "#\!/usr/bin/perl" | cut -d ":" -f 1 | sort); do
       perltidy $f
       mv $f.tdy $f
    done
}

glint() {
    local f
    goimports -l . | grep -v bindata.go | sed 's/^/[goimports]    /g'
    revive ./... | sed 's/^/[revive]       /g'
    for f in $(find . -type f -name "*.go" -exec dirname {} \; | sort -u); do
        go vet $f | sed 's/^/[govet]        /g'
    done
}

_container() {
    local opts cur
    cur=${COMP_WORDS[COMP_CWORD]}
    if [ $COMP_CWORD -eq 1 ]; then
        opts=$(perl ~/.local/lib/containers.pl)
        COMPREPLY=( $(compgen -W "$opts" -- $cur) )
    fi
}

complete -F _container container
