#!/bin/bash

vlc() {
    /usr/bin/vlc "$@" &
    disown
}

firefox() {
    /usr/bin/$BROWSER "$@" &
    disown
}

totp() {
    perl ~/.local/lib/totp.pl $@
}

_apps() {
    local f b targets host
    targets="$HOME/.local/apps"
    if [ ! -d $targets ]; then
        mkdir -p $targets
    fi
    for f in $(ls $targets/*.app); do
        b=$(basename $f)
        alias $b="bash $f"
    done
}

_apps
