#!/bin/bash

for f in mutt mumble $BROWSER pavucontrol schroot makepkg repo-add mkarchroot; do
    alias $f="echo disabled in bash"
done

aem() {
    perl ~/.local/lib/aem.pl $@
}

pltidy() {
    local f
    for f in $(git grep "#\!/usr/bin/perl" | cut -d ":" -f 1 | sort); do
       perltidy $f
       mv $f.tdy $f
    done
}

glint() {
    goimports -l . | grep -v bindata.go | sed 's/^/[goimports]    /g'
    revive ./... | sed 's/^/[revive]       /g'
}

_aem() {
    local opts cur
    cur=${COMP_WORDS[COMP_CWORD]}
    if [ $COMP_CWORD -eq 1 ]; then
        opts=$(perl ~/.local/lib/aem.pl help)
        COMPREPLY=( $(compgen -W "$opts" -- $cur) )
    else
        if [ $COMP_CWORD -ge 2 ]; then
            cur=${COMP_WORDS[1]}
            opts=""
            case "$cur" in
                "repo-add")
                    if [ $COMP_CWORD -eq 2 ]; then
                        opts="vpr.db.tar.gz apr.db.tar.gz"
                    else
                        opts=$(ls | grep ".pkg.tar.zst")
                    fi
                    ;;
                "detach-sign")
                    if [ $COMP_CWORD -eq 2 ]; then
                        opts=$(ls | grep ".pkg.tar.zst")
                    fi
                    ;;
            esac
            if [ ! -z "$opts" ]; then
                 COMPREPLY=( $(compgen -W "$opts" -- ${COMP_WORDS[COMP_CWORD]}) )
            fi
        fi
    fi
}

complete -F _aem aem
