#!/bin/bash

GITCONF=$HOME/.local/var/gitconfig
if [ ! -e $GITCONF ]; then
    ln -sf ~/.local/env/dev.gitconfig $GITCONF
fi

_vimgo() {
    local vimgo tmpvimgo
    vimgo=$HOME/.vim/pack/plugins/start/vim-go
    if [ ! -d $vimgo ]; then
        echo "setting up vim-go"
        echo
        git clone https://github.com/fatih/vim-go.git $vimgo
    else
        tmpvimgo=$HOME/.local/tmp/vim-go
        if [ ! -e $tmpvimgo ]; then
            git -C $vimgo pull
            if [ $? -eq 0 ]; then
                touch $tmpvimgo
            fi
        fi
    fi
}

(_vimgo 2>&1 | systemd-cat -t vimgogit &)

unset SSH_AGENT_PID
if [ "${gnupg_SSH_AUTH_SOCK_by:-0}" -ne $$ ]; then
    export SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"
fi

export GPG_TTY=$(tty)
gpg-connect-agent updatestartuptty /bye >/dev/null

source ~/.local/env/dev_aliases
if [ -z "$SSH_CONNECTION" ]; then
    source ~/.local/lib/ide.app load
    source ~/.local/env/dev_disp_aliases
fi

if [ ! -z "$SCHROOT_CHROOT_NAME" ]; then
    PS1='[\u@${SCHROOT_CHROOT_NAME} \W]\$ '
fi

if [ -x /usr/bin/xhost ]; then
    if [ ! -z "$DISPLAY" ]; then
        xhost +local: > /dev/null
    fi
fi
