#!/bin/bash

if [ ! -e /var/lib/systemd/linger/enck ]; then
    echo "sudo loginctl enable-linger"
fi

MAIL_APP=$HOME/.mutt/mail.pl
if [ ! -h $MAIL_APP ]; then
    ln -s $HOME/.local/lib/mail_host.pl $MAIL_APP
fi

if [ -e $START_MUTT ]; then
    mutt -F $HOME/.mutt/fastmail.muttrc
    exit 0
fi

git -C .mutt/ status -sb

fastmail.app() {
    tmux attach -t mutt
}
