#!/bin/bash
export IS_DESKTOP=$HOME/.local/var/is.desktop
export IS_LAPTOP=$HOME/.local/var/is.laptop
export START_MUTT=$HOME/.cache/start.mutt
if [ -e $IS_LAPTOP ] || [ -e $IS_DESKTOP ]; then
    export PASSWORD_STORE_DIR=$HOME/.local/private/pass
    export BROWSER=firefox-developer-edition
    export GOPATH="$HOME/.cache/go"
    NET=/etc/voidedtech/env/network
    if [ -e $NET ]; then
        source /etc/voidedtech/env/network
    fi
    export IS_DEV=1
else
    export IS_DEV=0
fi
