#!/bin/bash
export TERM=xterm
export PAGER=less
export IS_DESKTOP=$HOME/.cache/is.desktop
export IS_LAPTOP=$HOME/.cache/is.laptop
export IS_MAIL=$HOME/.cache/is.mail
export COMP_KNOWN_HOSTS_WITH_HOSTFILE=""
if [ -e $IS_LAPTOP ] || [ -e $IS_DESKTOP ]; then
    export PASSWORD_STORE_DIR=$HOME/.local/private/pass
    export BROWSER=firefox-developer-edition
    export GOPATH="$HOME/.cache/go"
    source /etc/voidedtech/env/network
    export IS_DEV=1
else
    export IS_DEV=0
fi
