#!/usr/bin/env bash
CONFIGS="$HOME/.vms/"
TIME="$HOME/Shared/comm/"

_init() {
  (cd "$CONFIGS$1" && vfu --config "$CONFIGS$1/config.json" $2)
}

_status() {
  if screen -list | grep -q "\.$1"; then
    echo "running"
    exit 0
  fi
  echo "stopped"
}

_set-time() {
  local now file t
  while : ; do
    now="$(date +%s)"
    file="$(date +%Y.%m.%d.%H.%M.%S)"
    for d in $(ls "$CONFIGS"); do
	t="${TIME}$d/"
	mkdir -p "$t"
	find "$t" -mmin +5 -delete
	echo "$now" > "$t/$file"
    done
    sleep 15
  done 
}

_manage-time() {
  local script
  script="vm time"
  if screen -list | grep -q "vm-time"; then
    return
  fi
  echo "starting time manager"
  screen -S vm-time -d -m $script 
}

_start() {
  local script
  _status "$1"
  script="vm init $1"
  if ! $script "--verify"; then
    echo "verify failed"
    exit 1
  fi
  echo
  echo "starting $1..."
  echo
  _manage-time
  screen -S $1 -d -m $script
}

if [ -z "$1" ]; then
  echo "command required"
  exit 1
fi
if [ "$1" != "ls" ] && [ "$1" != "time" ]; then
  if [ -z "$2" ]; then
    echo "vm required"
    exit 1
  fi
  if [ ! -e "$CONFIGS$2/config.json" ]; then
    echo "$2 is not a valid vm"
    exit 1
  fi
fi

case "$1" in
  "time")
    _set-time
  ;;
  "start")
    _start $2
  ;;
  "init")
    _init $2 $3 
  ;;
  "stop")
    pkill vfu
  ;;
  "attach")
    screen -r $2
  ;;
  "status")
    _status $2
  ;;
  "ls")
    ls "$CONFIGS"
  ;;
  *)
    echo "unknown command: $1"
    exit 1
  ;;
esac
