#!/usr/bin/env bash
CONFIGS="$HOME/.vms/"
TIME_SERVER="192.168.65.1"
TIME_PORT="8989"

_init() {
  (cd "$CONFIGS$1" && vfu --config "$CONFIGS$1/config.json" $2)
}

_status() {
  if screen -list | grep -q "\.$1"; then
    echo "running"
    exit 0
  fi
  echo "stopped"
}

_http() {
  _check-http start
}

_check-http() {
  if ! ps aux | grep vm-http | grep -q python; then
    if [ "$1" == "warn" ]; then
      echo "http server not running, remember to start it"
    else
      vm-http -address "$TIME_SERVER" --port "$TIME_PORT" &
      disown
    fi 
  fi
  echo "vm http started"
}

_start() {
  local script
  _status "$1"
  script="vm init $1"
  if ! $script "--verify"; then
    echo "verify failed"
    exit 1
  fi
  echo
  echo "starting $1..."
  echo
  _check-http warn
  screen -S $1 -d -m $script
}

if [ -z "$1" ]; then
  echo "command required"
  exit 1
fi
if [ "$1" != "ls" ] && [ "$1" != "http" ]; then
  if [ -z "$2" ]; then
    echo "vm required"
    exit 1
  fi
  if [ ! -e "$CONFIGS$2/config.json" ]; then
    echo "$2 is not a valid vm"
    exit 1
  fi
fi

case "$1" in
  "http")
    _http
  ;;
  "start")
    _start $2
  ;;
  "init")
    _init $2 $3 
  ;;
  "stop")
    pkill vfu
  ;;
  "attach")
    screen -r $2
  ;;
  "status")
    _status $2
  ;;
  "ls")
    ls "$CONFIGS"
  ;;
  *)
    echo "unknown command: $1"
    exit 1
  ;;
esac
