#!/usr/bin/env python3
from http.server import HTTPServer, BaseHTTPRequestHandler
import argparse
from datetime import datetime
import time


class VMHandler(BaseHTTPRequestHandler):

    def do_GET(self) -> None:
        if self.path == "/time" or self.path == "/hour":
            self.send_response(200)
            self.end_headers()
            val = ""
            if self.path == "/time":
                val = str(int(time.time()))
            else:
                val = str(datetime.now().hour)
                if len(val) < 2:
                    val = "0" + val
            self.wfile.write(val.encode("utf-8"))
        else:
            self.send_error(403)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--address", type=str, required=True)
    parser.add_argument("--port", type=int, required=True)
    args = parser.parse_args()
    httpd = HTTPServer((args.address, args.port), VMHandler)
    httpd.serve_forever()


if __name__ == "__main__":
    main()
