#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
#xmodmap "/home/enck/.Xmodmap"

dunst -config $HOME/.config/dunst &
nm-applet &
pasystray &
light-locker --lock-on-suspend &

cnt=$(xrandr | grep " connected" | wc -l)
if [ $cnt -eq 2 ]; then
    xrandr --output DP-2-1-8 --rotate right --left-of DP-2-8
fi

exec fluxbox -log /home/enck/.fluxbox/log
