#!/bin/sh

dunst -config $HOME/.config/dunst &
nm-applet &
pasystray &
if [ -x /usr/bin/cbatticon ]; then
    cbatticon -l 10 -r 5 &
fi
xautolock -detectsleep -time 5 -locker "$HOME/.local/bin/sys xautolock" &

. $HOME/.variables
host=$(cat $HOST_TYPE)
if [[ "$host" == "$DESKTOP" ]]; then
    cnt=$(xrandr | grep " connected" | wc -l)
    if [ $cnt -eq 2 ]; then
        xrandr --output DP-2-1-8 --rotate right --left-of DP-2-8
    fi
else
    if [[ "$host" == "$LAPTOP" ]]; then
        xrandr --output eDP-1 --auto --dpi 144 --mode 2560x1440
    fi
fi

exec fluxbox -log /home/enck/.fluxbox/log
