#!/usr/bin/env bash
version() {
  echo "0.0.44"
}

deps() {
  echo golang
}

url() {
  echo "https://github.com/mattn/efm-langserver"
}

sha256sum() {
  echo "825aef5815fb6eff656370e9f01fc31f91e5b2ab9d2b1f080881839676020dac"
}

download() {
  echo "$(url)/archive/v$(version).tar.gz"
}

workdir() {
  echo "efm-langserver-$(version)"
}

build() {
  echo "go build $GOFLAGS -o bin/efm-langserver"
}

install() {
  echo "install -Dm755 bin/efm-langserver $BINDIR/efm-langserver"
}
