#!/usr/bin/env bash
version() {
  echo "1.6.3"
}

deps() {
  echo "golang"
}

url() {
  echo "https://github.com/kisielk/errcheck"
}

sha256sum() {
  echo "6b5e8fb4637d58b72dc3dfcfc0e75cbc3703477e50b4e8234a6772104316975f"
}

download() {
  echo "$(url)/archive/v$(version).tar.gz"
}

workdir() {
  echo "errcheck-$(version)"
}

build() {
  echo "go build $GOFLAGS -o bin/errcheck"
}

install() {
	echo "install -Dm755 bin/errcheck $BINDIR/dev/errcheck"
}
