#!/usr/bin/env bash
version() {
  echo "0.4.0"
}

deps() {
  echo golang
}

url() {
  echo "https://github.com/mvdan/gofumpt"
}

sha256sum() {
  echo "ba1fd89dd5a36a5443c879cd084b5626d3f8704000ec53c0d1cf5276af2bfa86"
}

download() {
  echo "$(url)/archive/v$(version).tar.gz"
}

workdir() {
  echo "gofumpt-$(version)"
}

build() {
  echo "go build $GOFLAGS -o bin/gofumpt"
}

install() {
  echo "install -Dm755 bin/gofumpt $BINDIR/dev/gofumpt"
}
