#!/usr/bin/env bash
version() {
  echo "0.11.0"
}

deps() {
  echo golang
}

sha256sum() {
  echo "b5dd0040bcc75b4760eb543826b6503a163c835c90f50843e626a112ca083931"
}

url() {
  echo "https://github.com/golang/tools"
}

download() {
  echo "$(url)/archive/gopls/v$(version).tar.gz"
}

workdir() {
  echo "tools-gopls-v$(version)/gopls"
}

build() {
  echo "go build $GOFLAGS -o bin/gopls"
}

install() {
  echo "install -Dm755 bin/gopls $BINDIR/dev/gopls"
}
