#!/usr/bin/env bash
version() {
  echo "1.0.0"
}

deps() {
  echo golang
}

sha256sum() {
  echo "076757a960fcc41a5d0ffd041a790ef0ec0e0ed15f5189a1580768096b5bf5a1"
}

url() {
  echo "https://github.com/enckse/lockbox"
}

download() {
  echo "$(url)/archive/v$(version).tar.gz"
}

workdir() {
  echo "lockbox-$(version)"
}

build() {
  echo "go build $GOFLAGS -o bin/lb cmd/main.go"
}

install() {
  echo "install -Dm 755 bin/lb $BINDIR/host/lb"
  echo "mkdir -p $PKGDIR/.bashrc.d/"
  echo "bin/lb bash > $PKGDIR/.bashrc.d/99-lockbox.host.sh"
}
