#!/usr/bin/env bash
version() {
  echo "23.03.01"
}

deps() {
  echo golang
}

sha256sum() {
  echo "95908762d8cc9395222530f3adae22307e82e8e71703ce0b868b66146aef6172"
}

url() {
  echo "https://github.com/enckse/lockbox"
}

download() {
  echo "$(url)/archive/v$(version).tar.gz"
}

workdir() {
  echo "lockbox-$(version)"
}

build() {
  echo "go build $GOFLAGS -o bin/lb cmd/main.go"
}

install() {
  echo "install -Dm 755 bin/lb $BINDIR/host/lb"
  echo "mkdir -p $PKGDIR/.bashrc.d/"
  echo "bin/lb bash > $PKGDIR/.bashrc.d/99-lockbox.host.sh"
}
