#!/usr/bin/env bash
version() {
  echo "1.2.5"
}

deps() {
  echo golang
}

url() {
  echo "https://github.com/mgechev/revive"
}

workdir() {
  echo "revive-$(version)"
}

download() {
  echo "$(url)/archive/v$(version).tar.gz"
}

build() {
  echo "go build $GOFLAGS -o bin/revive"
}

sha256sum() {
  echo "a34fe667d51dd9824f06fa0985f58a4359e2883ee25b235d91e366f3c4be68d8"
}

install() {
  echo "install -Dm755 bin/revive $BINDIR/dev/revive"
}
