#!/usr/bin/env bash
url() {
  echo "https://github.com/dominikh/go-tools"
}

deps() {
  echo golang
}

version() {
  echo "2023.1.2"
}

sha256sum() {
  echo "c112f8f5f41866729bf7e8f83881210228d0d6e2c037f45870b5d90ce239e4be"
}

workdir() {
  echo "go-tools-$(version)"
}

download() {
  echo "$(url)/archive/$(version).tar.gz"
}

build() {
  echo "go build $GOFLAGS -o bin/staticcheck ./cmd/staticcheck"
}

install() {
  echo "install -Dm755 bin/staticcheck $BINDIR/dev/staticcheck"
}
