#!/bin/sh -e
OFFSET=".local/ttypty"
[ "$(uname)" = "Darwin" ] && OFFSET="Library/com.ttypty"
DEPLOY="$HOME/$OFFSET/dotfiles/fs"
URL="https://github.com/seanenck/dotfiles"

mkdir -p "$DEPLOY"
HASH=$(git ls-remote "$URL" | grep "HEAD" | cut -c 1-7)
DEST="$DEPLOY/$HASH"
if [ ! -d "$DEST" ]; then
  echo "updating dotfiles to $HASH"
  curl -L --silent "${URL}/archive/master.tar.gz" > "$DEST.tar.gz"
  (cd "$DEPLOY" && tar xf "$DEST.tar.gz")
  (cd "$DEPLOY" && mv dotfiles-master "$HASH")
fi
(cd "$DEST" && ./dotfiles --deploy)
(cd "$DEST" && ln -sf "$PWD/dotfiles" "$HOME/.local/bin")
if [ "$(find "$DEPLOY" -maxdepth 1 -type f -not -path "*$HASH*" | wc -l)" -gt 10 ]; then
  echo "purging old dotfile deployments"
  find "$DEPLOY" -type f -not -newer "$DEST" -not -path "*$HASH*" -delete
  find "$DEPLOY" -empty -delete
fi
