#!/bin/sh
test ! -e go.mod && echo "cowardly refusing to run without go.mod" && exit 1
revive ./... | sed 's#^#revive:      #g'
go vet ./... | sed 's#^#go vet:      #g'
staticcheck -checks all -debug.run-quickfix-analyzers ./... | sed 's#^#staticcheck: #g'
gofumpt -l -extra $(find . -type f -name "*.go") | sed 's#^#gofumpt:     #g'
