#!/bin/sh -e
for FILE in "$HOME/Workspace/dotfiles/.local/libexec/packages/"*.sh; do
  . "$FILE"
done
PKGS_SHELL="$(basename "$SHELL")"
WORKDIR=".local/ttypty"
[ "$(uname)" = "Darwin" ] && WORKDIR="Library/com.ttypty"

export PKGS_BIN="$HOME/.local/bin"
export PKGS_COMPLETIONS="$HOME/.local/share/${PKGS_SHELL}-completion/completions/"
export API_TOKEN="$("$HOME/$WORKDIR/secrets/libexec/api-token")"
[ -z "$API_TOKEN" ] && echo "no github token found/set" && exit 1

export PKGS_DIR="$HOME/$WORKDIR/packages"
[ -d "$PKGS_DIR" ] || mkdir -p "$PKGS_DIR"

for FILE in "$HOME/Workspace/dotfiles/.config/packages/"**/*.sh; do
  . "$FILE"
done
