#!/bin/sh -e
for FILE in "$HOME/.local/libexec/packages/"*.sh; do
  . "$FILE"
done

PKGS_SHELL="$(basename "$SHELL")"
WORKDIR="Library/com.ttypty"
case "$(uname)" in
  "Linux")
    WORKDIR=".local/ttypty"
    export PKGS_LIBC="gnu"
    export PKGS_ARCH="aarch64"
    ;;
esac

export PKGS_BIN="$HOME/.local/bin"
export PKGS_COMPLETIONS="$HOME/.local/share/${PKGS_SHELL}-completion/completions/"
export API_TOKEN="$("$HOME/$WORKDIR/secrets/libexec/api-token")"
[ -z "$API_TOKEN" ] && echo "no github token found/set" && exit 1

export PKGS_DIR="$HOME/$WORKDIR/packages"
[ -d "$PKGS_DIR" ] || mkdir -p "$PKGS_DIR"

for FILE in "$HOME/.config/packages/linux/"/*.sh; do
  echo "processing: $(basename "$FILE")"
  . "$FILE"
done
