#!/usr/bin/env bash
HOME_CACHE="$HOME/.cache"
export GOPATH="$HOME_CACHE/go"
export DELTA_PAGER="less -c -X"
export PATH="$HOME/.bin:$PATH"
export XDG_SSH_ENV="$HOME/.cache/xdg.env"
source "$HOME/.cargo/env"

if [ ! -d "$HOME_CACHE" ]; then
    mkdir "$HOME_CACHE"
fi
if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then
    exec sway > $HOME/.cache/sway.log 2>&1 | systemd-cat -t sway
fi

if [ -z "$SSH_CONNECTION" ]; then
    {
        echo "export XDG_RUNTIME_DIR='$XDG_RUNTIME_DIR'"
    } > "$XDG_SSH_ENV"
else
    if [ -e "$XDG_SSH_ENV" ]; then
        source "$XDG_SSH_ENV"
    fi
fi
if [ -n "$XDG_RUNTIME_DIR" ]; then
    SSH_AGENT_ENV="$XDG_RUNTIME_DIR/ssh-agent.env"
    if ! pgrep ssh-agent > /dev/null; then
        ssh-agent > "$SSH_AGENT_ENV"
    fi
    if [[ ! -f "$SSH_AUTH_SOCK" ]]; then
        source "$SSH_AGENT_ENV" >/dev/null
    fi
else
    echo "no agent"
fi
 
_not-pushed() {
    if ! git uncommitted --quiet; then
        echo
        echo "uncommitted:"
        git uncommitted | cut -d " " -f 1 | sort -u | sed "s#$HOME/##g" | sed 's/^/  -> /g'
        echo
    fi
}
_not-pushed
