#!/usr/bin/env bash
HOME_CACHE="$HOME/.cache"
export GOPATH="$HOME_CACHE/go"
export DELTA_PAGER="less -c -X"
export PATH="$HOME/.bin:$PATH"
source "$HOME/.cargo/env"

_sway-start() {
    dbus-launch --exit-with-session sway
}

if [ ! -d "$HOME_CACHE" ]; then
    mkdir "$HOME_CACHE"
fi
if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then
    _sway-start > $HOME/.cache/sway.log 2>&1 
    exit
fi

SSH_AGENT_ENV="$XDG_RUNTIME_DIR/ssh-agent.env"
if ! pgrep ssh-agent > /dev/null; then
    ssh-agent > "$SSH_AGENT_ENV"
fi
if [[ ! -f "$SSH_AUTH_SOCK" ]]; then
    source "$SSH_AGENT_ENV" >/dev/null
fi
 
_not-pushed() {
    if ! git uncommitted --quiet; then
        echo
        echo "uncommitted:"
        git uncommitted | cut -d " " -f 1 | sort -u | sed "s#$HOME/##g" | sed 's/^/  -> /g'
        echo
    fi
}
_not-pushed
