directory: ~/.local/fs
indexing:
  enabled: true
parallelization: 4
include:
  - "~/.config/blap/apps/*.yaml"
  - "~/.config/blap/src/*.yaml"
  - "~/.config/blap/bin/*.yaml"
variables:
  - key: "LOCALBIN"
    value: "$HOME/.local/bin"
  - key: "COMPLETIONS"
    value: "$HOME/.local/share/{{ if eq $.OS \"linux\" }}bash{{else}}zsh{{end}}-completion/completions"
  - key: "NVIM_PLUGINS"
    value: "$HOME/.config/nvim/pack/plugins/start"
  - key: "COMPGEN"
    value: "/{{ $.Name }} completions > $COMPLETIONS/{{ $.Name }}"
