directory: ~/.local/fs
indexing:
  enabled: true
parallelization: 4
connections:
  github:
    token: ~/.local/state/blap.github.token
include:
  - "~/.config/blap/apps/*.yaml"
variables:
  values:
    "PATHS": "$HOME/.bash/paths"
    "COMPLETIONS": "$HOME/.bash/completions"
    "NVIM_PLUGINS": "$HOME/.config/nvim/pack/plugins/start"
