directory: ~/.local/fs
indexing:
  enabled: true
parallelization: 4
include:
  - "~/.config/blap/apps/*.yaml"
connections:
  github:
    token: ["secret-tool", "lookup", "blap", "github"]
variables:
  values:
    "PATHS": "$HOME/.bash/paths"
    "COMPLETIONS": "$HOME/.bash/completions"
    "NVIM_PLUGINS": "$HOME/.config/nvim/pack/plugins/start"
