directory: ~/.local/fs
parallelization: 4
connections:
  github:
    token: ~/.local/state/blap.github.token
include:
  - "~/.config/blap/apps/*.yaml"
pinned:
  - "^0000000."
variables:
  values:
    "PATHS": "$HOME/.bash/paths"
    "COMPLETIONS": "$HOME/.bash/completions"
    "NVIM_PLUGINS": "$HOME/.config/nvim/pack/plugins/start"
