directory: ~/.local/fs
indexing:
  enabled: true
parallelization: 4
include:
  - "~/.config/blap/apps/*.yaml"
  - "~/.config/blap/src/*.yaml"
  - "~/.config/blap/bin/*.yaml"
variables:
  "PATHS": "$HOME/.local/bin"
  "COMPLETIONS": "$HOME/.local/share/{{ if eq $.OS \"linux\" }}bash{{else}}zsh{{end}}-completion/completions"
  "NVIM_PLUGINS": "$HOME/.config/nvim/pack/plugins/start"
  "COMPSH": "{{ if eq $.OS \"linux\" }}bash{{else}}zsh{{end}}"
