directory: ~/.local/fs
parallelization: 4
connections:
  github:
    token: ~/.local/state/blap.github.token
include:
  - "~/.config/blap/apps/*.yaml"
variables:
  values:
    "DESTDIR": "$HOME/.local/bin"
    "COMPLETIONS": "$HOME/.config/shellrc/completions"
    "NVIM_PLUGINS": "$HOME/.config/nvim/pack/plugins/start"
