directory = "~/.local/fs"
include = ["~/.config/blap/apps/*", "~/.config/blap/src/*", "~/.config/blap/bin/*"]
parallelization = 4

variables = [
  { key = "LOCALBIN", value = "$HOME/.local/bin" },
  { key = "COMPLETIONS", value = "$HOME/.local/share/{{ if eq $.Config.OS \"linux\" }}bash{{else}}zsh{{end}}-completion/completions" },
  { key = "VIM_PLUGINS", value = "$HOME/.config/$EDITOR/pack/plugins/start" },
  { key = "COMPGEN", value = "/{{ $.Name }} completions > $COMPLETIONS/{{ $.Name }}" }
]

[connections]
github.token = ["$SECRET_ROOT/libexec/read-blap-token"]

[logging]
file = "~/{{ if eq $.Config.OS \"linux\" }}.local/state{{else}}Library/com.ttypty/blap{{end}}/blap.log"

[indexing]
enabled = true
