ARG release=41
ARG variant=sericea

FROM quay.io/fedora-ostree-desktops/$variant:$release
RUN rpm-ostree install \
    age \
    alacritty \
    neovim \
    ripgrep \
    ShellCheck \
    git-delta \
    just \
    bat && \
    rpm-ostree uninstall \
    foot && \
    ostree container commit
