#!/bin/bash
## various points
HOME_BIN=$HOME/.local/bin

# cache files
HOME_CACHE=$HOME/.cache/home/
HOME_SCRATCH=${HOME_CACHE}scratch/
DMENU_URLS=${HOME_CACHE}dmenuurls/
USER_TMP=${HOME_CACHE}tmp/

# perm/store
PERM_LOCATION=${HOME}/store/
HOME_STORE=${PERM_LOCATION}documents/
PERM_CONFIGS=${HOME_STORE}configs/
PRIV_PATH=${PERM_LOCATION}private/

# mail
MAIL_DIR=$HOME/.mutt/imap/
TRIGGER_MAIL=${USER_TMP}mail.trigger

# files
SSH_AUTH_TMP=/tmp/ssh-auth.sock
GIT_CHANGES=${USER_TMP}git.log
PRIV_CONF=${PERM_CONFIGS}priv.aliases
XDG_USER_CONFIG=$HOME/.config/user-dirs.dirs
SYS_ONLINE=${USER_TMP}sys.online

# string vars
BASE_SERVER="blip"
RED_TEXT="\033[1;31m"
NORM_TEXT="\033[0m"
TASK_FILE=".tsk"

export OPENSC_CONF="$HOME/.config/opensc.conf"

_init() {
    local xsess
    # cleanup xsession errors
    xsess=$HOME/.xsession-errors
    cat $xsess >> ${USER_TMP}xsession.$(date +%Y-%m-%d)
    echo > $xsess
    
    # make sure I can operate
    mkdir -p $DMENU_URLS
    mkdir -p $HOME_SCRATCH
    mkdir -p $USER_TMP

    # check mail for valid files
    find $MAIL_DIR -type f -exec file {} \; | grep -v "\.notmuch\/" | grep -v -E "(ASCII|UTF-8 Unicode|ISO-8859) text(,|$)" | systemd-cat -t "mailsync" -p err

    # cleanup temp dirs
    find ${USER_TMP}* -mtime 1 -type f -exec rm {} \;
    find $USER_TMP -empty -type d -delete
    find $HOME/.vim/{swap,undo} -mmin +1440 -type f -exec rm {} \;
    journalctl -t sync --since "7 days ago" | grep -q "local sync completed"
    if [ $? -ne 0 ]; then
        echo "no recent successful syncs" | systemd-cat -p err -t "maintain"
    fi
}
