#!/bin/bash
DEB_SIGN_KEY=031E9E4B09CFD8D3F0ED35025109CDF607B5BB04
MIRROR_SERVER="voidedtech.com"
MIRROR_COMPONENTS="enckse epiphyte"

_exports() {
    for f in MIRROR_SERVER MIRROR_COMPONENTS DEB_SIGN_KEY; do
        echo "$f=${!f}"
    done
}
