#!/bin/bash
DEB_SIGN_KEY=031E9E4B09CFD8D3F0ED35025109CDF607B5BB04
MIRROR_SERVER="voidedtech.com"
MIRROR_COMPONENTS="enckse epiphyte"
DEB_BUILD_GO="/build/go/"
DEB_BUILD_DIR="${DEB_BUILD_GO}src/packages/"

_exports() {
    for f in MIRROR_SERVER MIRROR_COMPONENTS DEB_SIGN_KEY DEB_BUILD_GO DEB_BUILD_DIR; do
        echo "$f=${!f}"
    done
}
