if type brew &>/dev/null; then
  FPATH=$(/opt/homebrew/bin/brew --prefix)/share/zsh/site-functions:$FPATH

  autoload -Uz compinit
  compinit
fi

_totp() {
	compadd $(totp list)
}

compdef _totp totp
