_rust-comp() {
    completions=~/.completions/_rustup
    if [ ! -e $completions ]; then
        ~/.rust/cargo/bin/rustup completions zsh > $completions
    fi
}

_rust-comp

if type brew &>/dev/null; then
    FPATH=$(/opt/homebrew/bin/brew --prefix)/share/zsh/site-functions:$FPATH

    autoload -Uz compinit
    compinit
fi

_totp() {
	compadd $(totp list)
}

compdef _totp totp
