apksrc: "/src"
tag: "apod-build"
configure: "configure"
cache: "~/.cache/apks"
containerfile: "~/.config/apod/Containerfile"
builddir: "/home/enck"
abuild: "~/.abuild"
user: "enck"
repository: "/opt/repository"
commands:
  run_args:
    - "-it"
    - "--rm"
    - "--userns"
    - "keep-id"
  podman_run:
    - ["doas", "/sbin/apk", "update"]
    - ["abuild", "sanitycheck"]
    - ["abuild", "verify"]
    - ["abuild", "-r"]
  build_args: []
  volumes: []