#!/usr/bin/env bash
TARGET="store/active/backup/"
COMPLETE="completed all backups"
CACHE="$HOME/.cache/backups"
TYPE="backups"
TODAY="$CACHE/$(date +%Y%m%d)"
FORCE=0
CHECK=0
DAILY=0
DAYS="1"
if [ -n "$1" ]; then
  case "$1" in
    "--force")
      FORCE=1
      mkdir -p "$CACHE"
      ;;
    "--check")
      DAYS="3"
      CHECK=1
      ;;
    "--daily")
      DAILY=1
      ;;
    *)
      echo "unknown argument"
      ;;
    esac
fi

if [ $FORCE -eq 0 ]; then
  if [ -e "$TODAY" ]; then
    exit 0
  else
    if [ $DAILY -eq 1 ]; then
      systemctl start --user backups
      exit 0
    fi
  fi
  if [ ! -d "$CACHE" ]; then
    echo "unable to backup yet..., try '--force'"
    exit 1
  fi
  if journalctl -t "$TYPE" --since "$DAYS days ago" | grep -q "$COMPLETE"; then
    exit 0
  else
    if [ $CHECK -eq 1 ]; then
      echo "no recent backup"
      exit 1
    fi
  fi
fi

if [ $CHECK -eq 1 ]; then
  exit 0
fi

touch "$TODAY"
_sync() {
  local finished
  finished=1
  for f in ".cache/upstreams" ".env" ".store"; do
    if ! rsync -avc --delete-after "$HOME/$f" "router:$TARGET" 2>&1; then
      finished=0
    fi
  done
  if [ $finished -eq 1 ]; then
    echo "$COMPLETE"
  else
    echo "failed"
  fi
}

_sync | systemd-cat -t "$TYPE"
CACHE="$LOCAL_STORE/media/"

_htmlmp4() {
    echo "<html><body><video controls preload loop playsinline poster=''>
          <source src='$1' type='video/mp4'></video></body></html>"
}

regen-media() {
  local t f
  rm -f "$CACHE"*.html
  for f in $(ls "$CACHE"*.mp4); do
    t="$f.html"
    _htmlmp4 "$(basename $f)" > "$t"
    chmod 644 "$t"
  done
  rsync -avc --delete-after "$CACHE" "router:store/active/media/"
}

regen-media
