#!/usr/bin/env bash
TARGET="store/active/backups/"
COMPLETE="completed all backups"
MEDIA="$LOCAL_STORE/media/"
TYPE="backups"
DIRS=(".cache/upstreams" ".env" ".store")
CHECK_DAYS=7
CHECK="$CHECK_DAYS days ago"
REPORT=0

_check() {
  local d cnt
  for d in "${DIRS[@]}"; do
    cnt=$(find "$HOME/$d" -type f -mtime +$CHECK_DAYS | wc -l)
    if [ "$cnt" -gt 0 ]; then
      return
    fi
  done
  exit 0
}

if [ -n "$1" ]; then
  case "$1" in
    "--check")
      _check
      REPORT=1
      ;;
    "--force")
      CHECK=""
  esac
else
    CHECK="today"
fi

if [ -n "$CHECK" ]; then
  if journalctl -t "$TYPE" --since "$CHECK" | grep -q "$COMPLETE"; then
    exit 0
  else
    if [ "$REPORT" -eq 1 ]; then
      exit 1
    fi
  fi
fi

_htmlmp4() {
    echo "<html><body><video controls preload loop playsinline poster=''>
          <source src='$1' type='video/mp4'></video></body></html>"
}

_regen-media() {
  local t f cnt
  for f in "$MEDIA"*.mp4; do
    t="$f.html"
    if [ ! -e "$t" ]; then
      _htmlmp4 "$(basename "$f")" > "$t"
      chmod 644 "$t"
    else
      touch "$t"
    fi
  done
  find "$MEDIA" -type f -name "*.html" -mtime +1 -delete
}

_sync() {
  local finished
  finished=1
  for f in ".cache/upstreams" ".env" ".store"; do
    if ! rsync -avc --delete-after "$HOME/$f" "router:$TARGET" 2>&1; then
      finished=0
    fi
  done
  if [ $finished -eq 1 ]; then
    echo "$COMPLETE"
  else
    echo "failed"
  fi
}

_regen-media
_sync | systemd-cat -t "$TYPE"
