#!/usr/bin/env bash
COMPLETE="completed all backups"
MEDIA="$LOCAL_STORE/media/"
READY="$HOME/.cache/backups.ready"
TYPE="backups"
CHECK_DAYS=7
CHECK="$CHECK_DAYS days ago"
REPORT=0

if [ ! -e "$READY" ]; then
    echo "not ready for backups, missing: $READY"
    exit 1
fi

_check() {
  local cnt
  cnt=$(find "$LOCAL_STORE" -type f -mtime +$CHECK_DAYS | wc -l)
  if [ "$cnt" -gt 0 ]; then
    return
  fi
  exit 0
}

if [ -n "$1" ]; then
  case "$1" in
    "--check")
      _check
      REPORT=1
      ;;
    "--force")
      CHECK=""
  esac
else
    CHECK="today"
fi

if [ -n "$CHECK" ]; then
  if journalctl -t "$TYPE" --since "$CHECK" MESSAGE="$COMPLETE" | grep -q "$COMPLETE"; then
    exit 0
  else
    if [ "$REPORT" -eq 1 ]; then
      exit 1
    fi
  fi
fi

_htmlmp4() {
    echo "<html><body><video controls preload loop playsinline poster=''>
          <source src='$1' type='video/mp4'></video></body></html>"
}

_regen-media() {
  local t f cnt
  for f in "$MEDIA"*.mp4; do
    t="$f.html"
    if [ ! -e "$t" ]; then
      _htmlmp4 "$(basename "$f")" > "$t"
      chmod 644 "$t"
    else
      touch "$t"
    fi
  done
  find "$MEDIA" -type f -name "*.html" -mtime +1 -delete
}

_sync() {
  local finished
  finished=1
  if ! rsync -avc --delete-after "$LOCAL_STORE/" "sync.voidedtech.com:store/active/synced/" 2>&1; then
    finished=0
  fi
  if [ $finished -eq 1 ]; then
    echo "$COMPLETE"
  else
    echo "failed"
  fi
}

_regen-media
_sync | systemd-cat -t "$TYPE"
