#!/usr/bin/env bash
DOTPREFIX=".dotfiles"

_dotfiles_hook() {
  local h
  h="$1/$2"
  if [ ! -e "$h" ]; then
    return
  fi
  if [ ! -x "$h" ]; then
    echo "hook ($h) is not executable"
    return
  fi
  $h
}

_lsfiles() {
  {
    git ls-files
    git ls-files --others
  } | grep '^\.' | grep -v "^$DOTPREFIX"
}

dotfiles() {
  local f d
  if [ ! -d ".git" ]; then
    echo "not a git/parent directory"
    return
  fi
  if [ ! -d "$DOTPREFIX" ]; then
    if [ ! -e "$DOTPREFIX" ]; then
      echo "not a dotfiles repository"
      return
    fi
  fi
  _dotfiles_hook "$DOTPREFIX" "pre"
  for f in $(_lsfiles); do
    d="$HOME/"$(dirname "$f")
    mkdir -p "$d"
    ln -sf "$PWD/$f" "$HOME/$f"
  done
  _dotfiles_hook "$DOTPREFIX" "post"
  for d in $(_lsfiles | grep '/' | cut -d '/' -f 1 | sort -u); do
    find "$HOME/$d" -xtype l -delete
  done
}

dotfiles
