#!/usr/bin/env bash
CONF="$HOME/.config/voidedtech/toolbox.yml"
if [ -z "$1" ]; then
  echo "command required"
  exit 1
fi
if [ "$1" == "--list" ]; then
  {
    CNT=0
    BOX=$(yq '.boxes | length' $CONF)
    if [ -n "$BOX" ] && [ "$BOX" -gt 0 ]; then
      while [ $CNT -lt $BOX ]; do
        yq ".boxes[$CNT].name" $CONF
        CNT=$((CNT+1))
      done
    fi
    toolbox list --containers | tail -n +2 | awk '{print $2}'
  } | sort -u
  exit 0
fi
if [ $(echo $1 | wc -c) -le 3 ]; then
  echo "name must be >= 3 characters"
  exit 1
fi
DEFAULTS=$(yq '.defaults[]' $CONF)
RPMS=""
SPEC=$(yq ".boxes[] | select (.name == \"$1\")" "$CONF")
if [ -n "$SPEC" ]; then
  PKGS=""
  for P in $(echo "$SPEC" | yq '.packages[]') $DEFAULTS; do
    PKGS="$PKGS $P"
  done
  for R in $(echo "$SPEC" | yq '.rpms[]'); do
    RPMS="$RPMS $R"
  done
else
  PKGS="$DEFAULTS"
fi
HAS=$(toolbox list --containers | awk '{print $2}' | grep "^$1\$")
if [ -z "$HAS" ]; then
  if ! toolbox create "$1"; then
    echo "failed to create $1"
    exit 1
  fi
  if ! toolbox run --container "$1" sudo dnf install -y $PKGS; then
    echo "failed to install default packages"
    exit 1
  fi
  for r in $(echo "$RPMS"); do
    if ! toolbox run --container "$1" sudo dnf install -y $RPMS_STORE/$r*; then
      echo "failed to install $r rpm"
      exit 1
    fi
  done
fi
exec toolbox enter $1
