#!/usr/bin/env bash
CONFIG="$HOME/.config/oclone/config.bash"
if [ ! -e "$CONFIG" ]; then
  echo "no config file"
  exit 1
fi
source "$CONFIG"

if [ "$(type -t "${UPSTREAM}_url")" != "function" ]; then
  echo "missing upstream store config"
  exit 1
fi
STORE=$(${UPSTREAM}_url)
if [ ! -d "$STORE" ]; then
  echo "$STORE does not exist"
  exit 1
fi

REPO="$1"
if [ -z "$REPO" ]; then
  echo "fetching mirror updates"
  for r in $(ls $STORE); do
    echo "-> $r"
    if ! git -C "$STORE/$r" fetch; then
      echo "failed"
    fi
  done
  exit 0
fi
DIR=$STORE/$(echo "$REPO" | rev | cut -d '/' -f 1 | rev)
if [ -d "$DIR" ]; then
  echo "$REPO is already mirrored"
  exit 0
fi
MAIN="${UPSTREAM_REMOTES[0]}"
if ! git clone "$MAIN$REPO" --mirror ${@:2} $DIR; then
  echo "clone failed"
  exit 1
fi
CNT=1
for MIRROR in "${UPSTREAM_REMOTES[@]}"; do
  if [ $CNT -gt 1 ]; then
    git -C "$DIR" remote set-url --add origin "$MIRROR$REPO"
  fi
  CNT=$((CNT+1))
done
RCV=$DIR/hooks/post-receive
{
  echo "#!/bin/sh"
  echo "git -C $DIR push origin --mirror"
} > $RCV
chmod 755 $RCV
