#!/usr/bin/env bash
BUILDS="$HOME/.env/dotfiles/containers"
TAG="instaweb"
if [ -z "$1" ]; then
  exec firefox "http://localhost:1234/gitweb"
fi
_stop() {
  local id
  id=$(podman ps --format "{{ .ID }} {{ .Image }}" | grep "localhost/$TAG" | awk '{print $1}')
  if [ -z "$id" ]; then
    echo "no container found"
    return
  fi
  podman stop "$id"
}
case "$1" in
  "start")
    _stop
    if ! (cd "$BUILDS" && podman build -f instaweb.Containerfile -t "$TAG"); then
      exit 1
    fi
    if ! (podman run --rm -p "1234:1234/tcp" -v "$HOME/.store/git:/opt/git:z" "$TAG"); then
      exit 1
    fi
    ;;
  "stop")
    _stop
    ;;
esac
