#!/usr/bin/env bash
LOCAL_LIB="$HOME/.env/local/lib/system/"
WORLD_FILE="${LOCAL_LIB}world"
_command() {
  rpm-ostree status --booted --json | jq -r '.deployments[0]."'$1'"[]' | sed "s/^/$2: /g"
}

if [ -n "$1" ] && [ "$1" == "check" ]; then
  if [ $(find "$WORLD_FILE" -mtime -1 | wc -l) -eq 1 ]; then
    exit 0
  fi
fi
{
  _command "requested-packages" "packages"
  _command "requested-base-removals" "removals"
  _command "requested-local-packages" "locals"
} | sort -u > "$WORLD_FILE"
cp /etc/ssh/sshd_config "${LOCAL_LIB}sshd_config"
