FROM alpine:edge

RUN echo "@testing http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
RUN apk add --no-cache qmk-cli@testing git py3-pip make gcc-avr avr-libc
WORKDIR /src
COPY keymap.json /src/qmk.json
COPY bin/qmk_firmware /root/qmk_firmware
RUN qmk setup --yes
RUN python3 -m pip install -r /root/qmk_firmware/requirements.txt
RUN mkdir -p /root/qmk_firmware/keyboards/keebio/iris/keymaps/personal
RUN qmk json2c qmk.json > /root/qmk_firmware/keyboards/keebio/iris/keymaps/personal/keymap.c
RUN qmk compile -kb keebio/iris/rev6 -km personal
RUN cp /root/qmk_firmware/keebio_iris_rev6_personal.hex personal.hex
