#!/bin/bash
# constants
RED_TEXT="\033[1;31m"
NORM_TEXT="\033[0m"
BASE_SERVER="blip"

# tmpfiles
SSH_AUTH_TMP=/tmp/ssh-auth.sock
USER_TMP=$HOME/.tmp
GIT_CHANGES=$USER_TMP/.git.changes
PROFILE_TMP=$USER_TMP/.profile.synced.
USER_JOURNAL=$USER_TMP/journal.log
SYS_ONLINE=$USER_TMP/.isonline
MAIL_DIR=$HOME/.mutt/imap/
TRIGGER_EMAIL=$USER_TMP/trigger.email

# offsets from home
PERM_LOCATION=$HOME/store/
PERM_DOCS=${PERM_LOCATION}documents
PERM_CONFIGS=$PERM_DOCS/configs/
SYNCED_PATH=$HOME/.synced/
HOME_CONF=$HOME/.config/
HOME_CACHE=$HOME/.cache/home/
HOME_SCRATCH=${HOME_CACHE}scratch/
HOME_BIN=$HOME/.bin/
CHROOT_LOCATION=${PERM_LOCATION}chroot
PRIV_CONF=${PERM_CONFIGS}priv.aliases
TASK_FILE=".tsk"
XDG_USER_CONFIG=${HOME_CONF}user-dirs.dirs

export OPENSC_CONF="$HOME/.config/opensc.conf"

_systemstop() {
    which pamixer > /dev/null 2>&1
    if [ $? -eq 0 ]; then
        pamixer -m
    fi
}
