#!/bin/bash
USER_TMP=$HOME/.tmp
SYNCED_PATH="$HOME/.synced/"
WSW_NET=${SYNCED_PATH}networks/
SYNCED_CONF=${SYNCED_PATH}/configs/
PERM_LOCATION=/opt/perm/
CHROOT_LOCATION=${PERM_LOCATION}chroot
SSH_SYNC_PATH=${SYNCED_PATH}ssh/
SSH_KEY_PATH=${SSH_SYNC_PATH}private/
PROFILE_DEF="${USER_TMP}/profile.next"
READY="ready"
IS_CONNECTED=1
NOT_CONNECTED=0
DISPLAY_UN=$USER_TMP/display-unlocked
DISPLAY_EN=$USER_TMP/display-enabled
STATUS_LOCKING_KEY="locking"
STATUS_BACKLIGHT_KEY="backlight"
RED_TEXT="\033[1;31m"
NORM_TEXT="\033[0m"
SSH_AUTH_TMP=/tmp/ssh-auth.sock
PACMAN_LOG=/var/log/pacman.log
EPIPHYTE_CONF=$HOME/.config/epiphyte/env
PERM_PERSONAL=personal
PRIV_CONF=${SYNCED_CONF}priv.aliases
GIT_PARTIAL_PATTERN="weechat|random_seed"
GIT_PARTIAL_TMP=$USER_TMP/git-partial
BASE_SERVER="base"
COPY_INDICATOR=$USER_TMP/backup.files
LAST_TIMES=$HOME/.cache/last-timed.log
LAST_TIMES_TMP=$USER_TMP/.last_time.tmp
REQUIRED_EVENTS=6
TRAY_SET=$USER_TMP/.tray
PKG_QUERY=$USER_TMP/package.query
CONF_HOME=$HOME/.config/home
SETUP_LOG="$USER_TMP/bash_setup.log"
GIT_CHANGES=$USER_TMP/git.changes
SND_MUTE="$USER_TMP/.mute"
PROFILE_TMP="$USER_TMP/.profile.synced."

function refresh-usr1()
{
    local _pids=$USER_TMP/icons.pid
    if [ -e $_pids ]; then
        kill -USR1 $(cat $_pids)
    fi
}

function mute()
{
    pamixer -m
}

function tray()
{
    if [ ! -e $TRAY_SET ]; then
        i3_commands tray_icons > /dev/null 2>&1 &
    fi
}

function set-system()
{
    # disable touchpad
    xinput set-prop $(xinput | grep "SynPS/2" | sed -n -e 's/^.*id=//p' | sed -e "s/\s/ /g" | cut -d " " -f 1) "Device Enabled" 0

    # mute
    if [ ! -e $SND_MUTE ]; then
        mute
        touch $SND_MUTE
    fi
}

function update-time()
{
    d=$(date +%Y-%m-%d)
    update-time-log "$1" $d
}

function update-time-log()
{
    cat $LAST_TIMES | grep -v "$1," > $LAST_TIMES_TMP
    cat $LAST_TIMES_TMP > $LAST_TIMES
    echo "$1,$2" >> $LAST_TIMES
}

function process-logs()
{
    d=$(cat $PACMAN_LOG | grep $(date +%Y) | cut -d " " -f 1 | cut -d "[" -f 2 | sort | uniq | tail -n 1)
    update-time-log "pacman" $d
}

function enter-window-vals()
{
    word=$2
    window=0
    while [ $window -eq 0 ]; do
        echo "please activate the $1 window to enter the text into"
        sleep 3
        active=$(xdotool getactivewindow)
        xdotool search --class $1 | grep -q $active
        if [ $? -eq 0 ]; then
            window=1
        else
            echo "please select a $1 window"
        fi
    done
    xdotool type "$word"
    for i in ${@:3}; do
        xdotool key $i
    done
}

function check-timed-events()
{
    all=""
    today=$(date +%Y-%m-%d)
    all="$today"
    for d in $(seq 1 7); do
        past=$(date +%Y-%m-%d -d "-$d days")
        all=$all"|$past"
    done
    year=$(date +%Y)
    months="($year-"$(date +%m)"|"$year-$(date -d "last month" +%m)")"
    all="($all)"
    if [ ! -e "$LAST_TIMES" ]; then
        touch $LAST_TIMES
    else
        warnings=""
        cnt=0
        for item in $(cat $LAST_TIMES); do
            cnt=$((cnt+1))
            i=$(echo $item | cut -d "," -f 1)
            d=$(echo $item | cut -d "," -f 2)
            echo $d | grep -q -E "$all"
            if [ $? -ne 0 ]; then
                _warn=1
                if [[ $i == "$PKGBUILD_IND"* ]]; then
                    if [[ $i == *"-git" ]]; then
                        echo $d | grep -q -E "$months"
                        if [ $? -eq 0 ]; then
                            _warn=0
                        fi
                    fi
                fi
                if [ $_warn -eq 1 ]; then
                    warnings="$warnings ${i}_(${d})"
                fi
            fi
        done
        if [ $cnt -ne $REQUIRED_EVENTS ]; then
            warnings=$warnings" wrong_number_of_events"
        fi
        if [ ! -z "$warnings" ]; then
            echo -e "${RED_TEXT}"
            echo "system events"
            echo "==="
            for w in $(echo $warnings); do
                changed=$(echo $w |  sed "s/_/ /g")
                echo -e "  -> (maintanence) $changed"
            done
            echo -e "${NORM_TEXT}"
            process-logs
        fi
    fi
}

function test-ssh()
{
    running=$(ssh -o BatchMode=yes -o ConnectTimeout=5 $1 echo $READY 2>&1)
    if [[ "$running" == "$READY" ]]; then
        echo $IS_CONNECTED
    else
        echo $NOT_CONNECTED
    fi
}

function get-all-changes()
{
    git update-index -q --refresh 
    git diff-index --name-only HEAD --
    git status -sb | grep 'ahead'
    git branch | grep "^\*" | grep -v "master"
}

function set-user-files()
{
    # user tmp
    mkdir -p $USER_TMP
    find $USER_TMP* -mtime +1 -type f -exec rm {} \;
    find $USER_TMP -empty -type d -delete

    if [ ! -e "$COPY_INDICATOR" ]; then
        cp /etc/hosts ${SYNCED_CONF}hosts
        cp /etc/systemd/network/* $HOME/.config/networkd/
        cp /etc/wsw/* $WSW_NET
        touch $COPY_INDICATOR
    fi

    for f in $(find $USER_TMP -type f -mmin +30 | grep "dmenu"); do
        rm -f $f
    done

    # vim
    for v in $(echo "undo swap"); do
        vim_dir=$HOME/.vim/$v
        mkdir -p $vim_dir
        find $vim_dir -mmin +1440 -type f -exec rm {} \;
    done
    
    # packages
    if [ ! -e $PKG_QUERY ]; then
        running=$(pidof pacman)
        if [ -z "$running" ]; then
            /usr/bin/pacman -Qqe > ${CONF_HOME}/packages
        fi
    fi
}

function get-git-folders()
{
    res=""
    for f in $(find $1 -type d | sort); do
        if [ ! -d "$f/.git" ]; then
            continue
        fi
        res=$res" "$f
    done
    echo $res
}

function get-workspace-objs()
{
    get-git-folders "$HOME/workspace/"
}

function get-perm-objs()
{
    get-git-folders "${PERM_LOCATION} -maxdepth 2"
}

function git-changing()
{
    d_paths="$HOME $SYNCED_PATH "$(get-perm-objs)" "$(get-workspace-objs)
    for d in $(echo "$d_paths"); do
        if [ ! -d "$d/.git" ]; then
            continue
        fi
        cd $d
        local_res=$(get-all-changes "$d")
        if [ -e "$GIT_PARTIAL_TMP" ]; then
            local_res=$(echo "$local_res" | grep -E -v "$GIT_PARTIAL_PATTERN")
        fi
        if [ ! -z "$local_res" ]; then
            if [ -z $first ]; then
                echo "uncommitted changes"
            fi
            echo -e "$d${RED_TEXT}"
            echo -e "$local_res${NORM_TEXT}" | sed "s/^/    /g"
            first="false"
        fi
    done
    touch $GIT_PARTIAL_TMP
    cd $HOME
}

function github-commit()
{
    local _hash
    _hash=$(git ls-remote --$1 $2 | tail -n 1)
    if [ ! -z "$_hash" ]; then
        commit=$(echo "$_hash" | cut -d " " -f 1 | cut -d "/" -f 1 | sed "s#refs##g")
        echo $commit
    fi
}

function github-releases()
{
    local last
    last=$(date -d "1 month ago" +%Y-%m-%d)
    for u in $(echo "enckse epiphyte"); do
        _file=$USER_TMP/repos.$u
        curl -s "https://api.github.com/search/repositories?q=user:$u+pushed:%3E=$last&sort=updated" | grep "clone_url" | cut -d ":" -f 2,3 | sed 's/"//g;s/ //g;s/,//g' > $_file
        for r in $(cat $_file | sort | grep -v -E "https://github.com/(enckse|epiphyte)/(home|batchy).git"); do
            tag=$(github-commit "tags" $r)
            if [ ! -z "$tag" ]; then
                head=$(github-commit "head" $r)
                if [[ "$head" != "$tag" ]]; then
                    echo "$r" | sed "s/\.git$/\/releases/g"
                fi
            fi
        done
    done
    update-time "github-releases"
}
