#!/bin/bash
INPUT_FILE=$1
TMP_FILE=/tmp/csvstats.sh
if [ -z $INPUT_FILE ] || [ ! -e $INPUT_FILE ]; then
    echo "Input file expected"
    exit -1
fi

if [ ! -e $TMP_FILE ]; then
    wget -O $TMP_FILE https://raw.githubusercontent.com/enckse/csv-stats/master/csvstats.sh
    chmod u+x $TMP_FILE
fi

FRIENDLY=$(echo $INPUT_FILE | cut -d "." -f 1)
echo
echo "$FRIENDLY:"
$TMP_FILE $PWD/$INPUT_FILE
echo
