#!/bin/bash
BACKLIGHT_ON="up"
BACKLIGHT_OFF="down"
BRIGHTER="brighter"
FULL_BRIGHT="full"
LOW_BRIGHT="low"
MID_BRIGHT="mid"
DIMMER="dimmer"
LEFT_POS="left"
RIGHT_POS="right"
CENTER_POS="center"
DPMS_ON="on"
DPMS_OFF="off"
DPMS_RESET="reset"
CHANGE_BY_STEP=5
IS_POSITIONED=0
PROFILE_CYCLE="cycle"
MAIN_DISPLAY="eDP1"
DISP_ONE="DP2-8"
DISP_TWO="HDMI1"
HOME_DISP="DP1"

function get-lighting-help()
{
    echo "
    $1 $2 $BACKLIGHT_ON (toggle backlights ON)
    $1 $2 $BACKLIGHT_OFF (toggle backlights OFF)
    $1 $3 $BRIGHTER (increase backlights)
    $1 $3 $DIMMER (decrease backlights)
    $1 $3 $FULL_BRIGHT (full brightness)
    $1 $4 $DPMS_ON (dpms on)
    $1 $4 $DPMS_OFF (dpms off)
    $1 $4 $DPMS_RESET (dpms reset)
    $1 $5 $PROFILE_CYCLE (profile cycling)
    "
}

function toggle-dpms()
{
    case $1 in
        $DPMS_ON)
            xset dpms force on
            ;;
        $DPMS_OFF)
            xset dpms force off
            ;;
        $DPMS_RESET)
            toggle-dpms $DPMS_OFF
            toggle-dpms $DPMS_ON
            ;;
    esac
}

# Get displays, first argument can filter out any displays
function get-displays()
{
    get-all-displays " "
}

function get-all-displays()
{
    xrandr | grep "${1}connected" | cut -d " " -f 1
}

# Toggle backlighting up/down to a specified level
function toggle-backlighting()
{
    case $1 in
        $BACKLIGHT_ON)
            SETTING=1.0
            ;;
        $BACKLIGHT_OFF)
            SETTING=0.3
            ;;
        *)
            echo "Unknown command $1"
            ;;
    esac
    
    if [ ! -z "$SETTING" ]; then
        DISPLAYS=$(get-displays)
        for disp in ${DISPLAYS[@]}; do
            xrandr --output $disp --brightness $SETTING
        done
    fi
}

# Increase/decrease brightness
function change-brightness()
{
    case $1 in
        $BRIGHTER)
            SUBCMD="-inc $CHANGE_BY_STEP"
            ;;
        $DIMMER)
            SUBCMD="-dec $CHANGE_BY_STEP"
            ;;
        $LOW_BRIGHT | $FULL_BRIGHT | $MID_BRIGHT)
            SUBVAL=""
            if [[ "$1" == "$FULL_BRIGHT" ]]; then
                SUBVAL=100
            else
                if [[ "$1" == "$MID_BRIGHT" ]]; then
                    SUBVAL=5
                else
                    SUBVAL=1
                fi
            fi
            SUBCMD="-set ${SUBVAL}0"
            ;;
        *)
            echo "unknown command $ACTION"
            ;;
    esac
    if [ ! -z "$SUBCMD" ]; then
        xbacklight $SUBCMD
    fi
}
