#!/bin/bash
URL_COMMON=$HOME/.cache/dmenu_urls/
INDEX_NAME="index"
INDEX_FILE=${URL_COMMON}${INDEX_NAME}
REGISTER_KEYWORD="--register"
HELP_KEYWORD="--help"
REBUILD_KEYWORD="--rebuild"
REMOVE_KEYWORD="--remove"
DISPLAY_KEYWORD="--display"
BROWSERS="google-chrome-stable chromium"
DEFAULT_ARGS="--new-window"
START_LINE="#name,browser,url,args,pre-setup"
ARG_DELIMITER="|"
function run-browser()
{
    browser=$1
    url=$2
    args=""
    if [ ! -z "$3" ]; then
        args=$3
    fi

    echo "$browser $url $args"
    $browser $url $args
}

function create-script()
{
    local SCRIPT_ACTION
    mkdir -p $URL_COMMON
    FILE_NAME=${URL_COMMON}$1
    if [ ! -z "$5" ]; then
        SCRIPT_ACTION=$URL_COMMON$5
        if [ ! -e $SCRIPT_ACTION ]; then
            echo "Missing referenced script $SCRIPT_ACTION for $1"
            exit -1
        fi
    fi
    echo "
#!/bin/bash
# url for $1
source \$HOME/.bin/dmenu_urls
$SCRIPT_ACTION
run-browser $3 $2 $4
" > $FILE_NAME
    chmod u+x $FILE_NAME
}

function build-scripts()
{
    if [ -e $INDEX_FILE ]; then
        LINES=$(cat $INDEX_FILE | grep -v "$START_LINE")
        for line in $LINES; do
            NAME=$(echo "$line" | cut -d "," -f 1 | tr -d '"')
            BROWSER=$(echo "$line" | cut -d "," -f 2)
            URL=$(echo "$line" | cut -d "," -f 3)
            ARGS=$(echo "$line" | cut -d "," -f 4 | sed "s/$ARG_DELIMITER/ /g")
            PRESETUP=$(echo "$line" | cut -d "," -f 5 | sed 's/"//g')
            create-script "$NAME" "$URL" "$BROWSER" "$ARGS" "$PRESETUP"
        done
    fi
}

function update-index()
{
    if [ ! -e $INDEX_FILE ]; then
        mkdir -p $URL_COMMON
        touch $INDEX_FILE
    fi
    
    EXISTING=$(cat $INDEX_FILE | grep -v "\"$1\"," | grep -v "$START_LINE")
    echo "$START_LINE" > $INDEX_FILE
    NEW_LINE="$2"
    if [ ! -z "$NEW_LINE" ]; then
        echo "$NEW_LINE" >> $INDEX_FILE
    fi
    
    if [ ! -z "$EXISTING" ]; then
        echo "$EXISTING" >> $INDEX_FILE
    fi
}

case $1 in
    $REGISTER_KEYWORD)
        DO_HELP=1
        NAME=$2
        if [ ! -z "$NAME" ]; then
            if [[ "$NAME" == "$INDEX_NAME" ]]; then
                echo "$INDEX_NAME is a reserved"
            else
                for browse in $BROWSERS; do
                    echo "$3" | grep -q "^$browse$"
                    if [ $? -eq 0 ]; then
                        BROWSER=$browse
                        break
                    fi
                done
                if [ ! -z "$BROWSER" ]; then
                    URL=$4
                    ARGS="${@:6}"
                    PRESET=$5
                    VALID=1
                    if [ -z "$URL" ]; then
                        if [ -z "$ARGS" ]; then
                            echo "URL or arguments are required"
                            VALID=0
                        fi
                    fi
                    
                    if [ $VALID -eq 1 ]; then
                        if [ -z "$ARGS" ]; then
                            ARGS=$DEFAULT_ARGS
                        fi

                        ARGS=$(echo "$ARGS" | sed "s/ /$ARG_DELIMITER/g")
                        NEW_ITEM="\"$NAME\",\"$BROWSER\",\"$URL\",\"$ARGS\",\"$PRESET\""
                        update-index "$NAME" "$NEW_ITEM"
                        REBUILD=1
                    fi
                else
                    echo "browser ($BROWSERS) is required"
                fi
            fi
        else
            echo "name is required"
        fi
        ;;
    $REBUILD_KEYWORD)
        REBUILD=1
        ;;
    $REMOVE_KEYWORD)
        DO_HELP=1
        NAME=$2
        if [ ! -z "$NAME" ]; then
            REBUILD=1
            update-index "$NAME" ""
            if [ -e "${URL_COMMON}$NAME" ]; then
                rm "${URL_COMMON}$NAME"
            fi
        else
            echo "name is required"
        fi
        ;;
    $DISPLAY_KEYWORD)
        if [ -e $INDEX_FILE ]; then
            cat $INDEX_FILE
        fi
        exit 0
        ;;
    $HELP_KEYWORD)
        DO_HELP=1
        ;;
esac

if [ ! -z $REBUILD ]; then
    build-scripts
    echo "index update completed"
    exit 0
fi

if [ ! -z $DO_HELP ]; then
    echo "
    $REGISTER_KEYWORD [name] [browser($BROWSERS)] [url] [setup] [args]
    $REMOVE_KEYWORD [name]
    $REBUILD_KEYWORD
    $DISPLAY_KEYWORD
    $HELP_KEYWORD
"
fi
