#!/bin/bash
source $HOME/.bin/common
INDEX_NAME="urls$INDEX_EXT"
INDEX_FILE=${URL_COMMON}/${INDEX_NAME}
REGISTER_KEYWORD="--register"
HELP_KEYWORD="--help"
REBUILD_KEYWORD="--rebuild"
REMOVE_KEYWORD="--remove"
DISPLAY_KEYWORD="--display"
BROWSERS="firefox"
DEFAULT_ARGS=""
START_LINE="#name,browser,url,args"
ARG_DELIMITER="|"
function run-browser()
{
    browser=$1
    url=$2
    args=""
    if [ ! -z "$3" ]; then
        args=$3
    fi

    cmd="$url $args"
    echo "$browser $cmd"
    pid=$(pidof $browser)
    cnt=0
    while [ -z "$pid" ]; do
        if [ $cnt -eq 0 ]; then
            $browser &
        fi
        cnt=$((cnt+1))
        sleep 3
        pid=$(pidof $browser)
        if [ $cnt -eq 5 ]; then
            break
        fi
    done
    $browser $cmd
}

function create-script()
{
    local SCRIPT_ACTION
    mkdir -p $URL_COMMON
    FILE_NAME=${URL_COMMON}/$1
    echo "
#!/bin/bash
# url for $1
source \$HOME/.bin/dmenu_urls
run-browser $3 $2 $4
" > $FILE_NAME
    chmod u+x $FILE_NAME
}

function build-scripts()
{
    if [ -e $INDEX_FILE ]; then
        LINES=$(cat $INDEX_FILE | grep -v "$START_LINE")
        for line in $LINES; do
            NAME=$(echo "$line" | cut -d "," -f 1 | tr -d '"')
            BROWSER=$(echo "$line" | cut -d "," -f 2)
            URL=$(echo "$line" | cut -d "," -f 3)
            ARGS=$(echo "$line" | cut -d "," -f 4 | sed "s/$ARG_DELIMITER/ /g")
            create-script "$NAME" "$URL" "$BROWSER" "$ARGS"
        done
    fi
}

function update-index()
{
    if [ ! -e $INDEX_FILE ]; then
        mkdir -p $URL_COMMON
        touch $INDEX_FILE
    fi
    
    EXISTING=$(cat $INDEX_FILE | grep -v "\"$1\"," | grep -v "$START_LINE")
    echo "$START_LINE" > $INDEX_FILE
    NEW_LINE="$2"
    if [ ! -z "$NEW_LINE" ]; then
        echo "$NEW_LINE" >> $INDEX_FILE
    fi
    
    if [ ! -z "$EXISTING" ]; then
        echo "$EXISTING" >> $INDEX_FILE
    fi
}

function get-browser()
{
    BROWSER=""
    for browse in $BROWSERS; do
        if [[ "$browse" == "$1" ]]; then
            BROWSER=$browse
            break
        fi
    done
    echo "$BROWSER"
}

case $1 in
    $REGISTER_KEYWORD)
        DO_HELP=1
        NAME=$2
        if [ ! -z "$NAME" ]; then
            if [[ "$NAME" == "$INDEX_NAME" ]]; then
                echo "$INDEX_NAME is a reserved"
            else
                BROWSER=$(get-browser "$3")
                if [ ! -z "$BROWSER" ]; then
                    URL=$4
                    ARGS="${@:6}"
                    PRESET=$5
                    VALID=1
                    if [ -z "$URL" ]; then
                        if [ -z "$ARGS" ]; then
                            echo "URL or arguments are required"
                            VALID=0
                        fi
                    fi
                    
                    if [ $VALID -eq 1 ]; then
                        if [ -z "$ARGS" ]; then
                            ARGS=$DEFAULT_ARGS
                        fi

                        ARGS=$(echo "$ARGS" | sed "s/ /$ARG_DELIMITER/g")
                        NEW_ITEM="\"$NAME\",\"$BROWSER\",\"$URL\",\"$ARGS\",\"$PRESET\""
                        update-index "$NAME" "$NEW_ITEM"
                        REBUILD=1
                    fi
                else
                    echo "browser ($BROWSERS) is required"
                fi
            fi
        else
            echo "name is required"
        fi
        ;;
    $REBUILD_KEYWORD)
        REBUILD=1
        ;;
    $REMOVE_KEYWORD)
        DO_HELP=1
        NAME=$2
        if [ ! -z "$NAME" ]; then
            REBUILD=1
            update-index "$NAME" ""
            if [ -e "${URL_COMMON}/$NAME" ]; then
                rm "${URL_COMMON}/$NAME"
            fi
        else
            echo "name is required"
        fi
        ;;
    $DISPLAY_KEYWORD)
        if [ -e $INDEX_FILE ]; then
            cat $INDEX_FILE
        fi
        exit 0
        ;;
    $HELP_KEYWORD)
        DO_HELP=1
        ;;
esac

if [ ! -z $REBUILD ]; then
    build-scripts
    rm -f $DMENU_ENTRIES
    echo "index update completed"
    exit 0
fi

if [ ! -z $DO_HELP ]; then
    echo "
    $REGISTER_KEYWORD [name] [browser($BROWSERS)] [url] [setup] [args]
    $REMOVE_KEYWORD [name]
    $REBUILD_KEYWORD
    $DISPLAY_KEYWORD
    $HELP_KEYWORD
"
fi
