#!/bin/bash
source $HOME/.bin/common
CACHE_DIR=$HOME/.cache/dmenurls/
URLS=$SYNCED_PATH/configs/urls.csv
BROWSER="/usr/bin/firefox"
HASHED=$USER_TMP/.dmenu_urls
APPS="vlc pavucontrol passwords irc claws-mail"
AVAILABLE="$USER_TMP/.dmenu_available"

function _dmenucall() {
    echo "$@" | ${SHELL:-"/bin/sh" }
    exit 0
}

function _dmenuwrapper() {
    local results urls u name url params group file hashed prev names
    hashed=$(sha256sum $URLS | cut -d " " -f 1)
    prev=""
    if [ -e "$AVAILABLE" ]; then
        if [ $(ls $CACHE_DIR | wc -l) -gt 0 ]; then
            if [ -e $HASHED ]; then
                prev=$(cat $HASHED)
            fi
        fi
    fi
    echo "$hashed" > $HASHED
    if [[ "$hashed" != "$prev" ]]; then
        urls=""
        names="$APPS"
        rm -f $CACHE_DIR*
        for u in $(cat $URLS | sed 's/"//g'); do
            name=$(echo "$u" | cut -d "," -f 1)
            file="$CACHE_DIR$name"
            url=$(echo "$u" | cut -d "," -f 2)
            params=$(echo "$u" | cut -d "," -f 3)
            group=$(echo "$u" | cut -d "," -f 4)
            names="$names $name"
            echo "$BROWSER $params $url" > $file
            if [ ! -z "$group" ]; then
                names="$names $group"
                file=$CACHE_DIR$group
                if [ -e $file ]; then
                    group=$(cat $file)
                    group="$group $url"
                    echo "$group" > $file
                else
                    echo "$BROWSER $url" > $file
                fi
            fi
        done
        names=$(echo $names)
        echo "$names" | tr ' ' '\n' | sort -u > $AVAILABLE
    fi
    results=$(cat $AVAILABLE | dmenu "$@")
    file="$CACHE_DIR/$results"
    if [ -e "$file" ]; then
        _dmenucall $(cat $file)
    fi
    echo "$APPS" | tr ' ' '\n' | grep -q "^$results$"
    if [ $? -eq 0 ]; then
        _dmenucall "$results"
    fi
    results=$(echo "$results" | sed "s/^search //g")
    results=$(echo $results)
    results="$(perl -MURI::Escape -e 'print uri_escape($ARGV[0]);' "$results")"
    _dmenucall "$BROWSER https://www.duckduckgo.com/?q=$results"
}

_dmenuwrapper "$@"
