#!/bin/bash
source $HOME/.bin/common
MAIL_DIR=$HOME/.mutt/imap/
INDEXED=$MAIL_DIR/Indexed/cur/
INDEX_FILE=$USER_TMP/mail.index
_mailsync() {
    local process cnt last now
    now=$USER_TMP/mailstatus.current
    process=0
    source $PRIV_CONF
    for f in $(cat ${HOME_PERSONAL}.muttrc | sed "s/^mailboxes //g" | sed "s/+//g"); do
        cnt=$(find $MAIL_DIR$f/new -type f | wc -l)
        process=$((process+cnt))
    done
    if [ -e $now ]; then
        last=$(cat $now)
        if [ $process -gt $last ]; then
            notmuch new
            notify-send Mail "unread messages ($process)"
        fi
    fi
    echo "$process" > $now
    cp $now $MAIL_COUNT
}

_offlineimap() {
    local pids purge last now
    pids=$(pidof -x offlineimap)
    if [ -z "$pids" ]; then
        purge=1
        if [ -e $INDEX_FILE ]; then
            last=$(cat $INDEX_FILE)
            now=$(date -d "15 minutes ago" +%s)
            if [ $last -gt $now ]; then
                purge=0
            fi
        fi
        echo "purging index: $purge"
        if [ $purge -eq 1 ]; then
            rm -f ${INDEXED}*
        fi
        offlineimap -c ${SYNCED_PATH}mail/imap.conf
        _mailsync
    else
        echo "offlineimap already running ($pids)"
    fi
}

_search() {
    date +%s > $INDEX_FILE
    rm -f ${INDEXED}*
    notmuch search --output=files $@ | sed -e 's: :\\\\ :g' | xargs -r -I searchoutput ln -s searchoutput $INDEXED
}

if [ -z "$1" ]; then
    _offlineimap
else
    if [[ "$1" == "client" ]]; then
        _offlineimap 2>/dev/null &
        sleep 0.5
        cd $HOME/Downloads
        mutt
    else
        if [[ "$1" == "search" ]]; then
            _search ${@:2}
        else
            echo "unknown command: $1"
        fi
    fi
fi
