#!/bin/bash
NAME=$1
WORKING=/tmp/encrypt-temp/
if [ -z "$NAME" ]; then
    echo "Name is required"
    exit -1
fi

items=${@:2}
for item in $items; do
    valid="true"
    if [ ! -e $item ]; then
        echo "$item is not a file"
        exit -1
    fi
done

if [ -z $valid ]; then
    echo "No items given"
    exit -1
fi

mkdir -p $WORKING
WORKING_DIR=$WORKING$NAME/
mkdir -p $WORKING_DIR
for item in $items; do
    cp $item $WORKING_DIR
done

CURRENT_PWD=$PWD
cd $WORKING_DIR
TAR_FILE=$NAME.tar.gz
tar -cvzf $CURRENT_PWD/$TAR_FILE *
cd $CURRENT_PWD
rm -rf $WORKING_DIR
gpg --symmetric --cipher-algo aes256 $TAR_FILE
rm $TAR_FILE
