#!/usr/bin/env bash
PATHS=$(ls $HOME/.env/ | sed "s#^#$HOME/\.env/#g")
PATHS="$HOME $PATHS"
for p in $(echo $PATHS | tr ' ' '\n' | sort); do
    echo
    echo "reconciling: $(basename $p)"
    git -C $p pull
    git -C $p push
done
echo
