#!/usr/bin/env bash
CONFIG="$HOME/.config/voidedtech/git.bash"
HIST="$HOME/.cache/oclone.hst"
if [ ! -e "$CONFIG" ]; then
  echo "missing config"
  exit 1
fi
source "$CONFIG"

oclone() {
  local in spec dst url clone cfg rel
  in="$1"
  if [ "$in" == "--list" ]; then
    {
      echo "${SOURCES[@]}" | tr ' ' '\n' | sed 's#$#/#g'
      if [ -e "$HIST" ]; then
        cat "$HIST"
      fi
    } | sort
    return
  fi
  repo=$(echo "$in" | cut -d '/' -f 1)
  spec="${repo}_url"
  if [ "$(type -t "$spec")" != "function" ]; then
    echo "invalid argument, spec not found"
    exit 1
  fi
  url=$($spec)
  rel=$(echo "$in" | cut -d '/' -f 2-)
  clone="$url$rel"
  if ! git clone "$clone" "${@:2}"; then
    echo "clone failed"
    exit 1
  fi
  touch "$HIST"
  awk -v line="$in" 'FNR==NR && line==$0{f=1; exit} 
                              END{if (!f) print line >> FILENAME}' "$HIST"
  cfg="${repo}_config"
  if [ "$(type -t "$cfg")" != "function" ]; then
    return
  fi
  cfg=$($cfg)
  dst=$(echo "$in" | rev | cut -d '/' -f 1 | rev)
  if [ -z "$cfg" ]; then
    return
  fi
  dst="$dst/.git/config" 
  if [ ! -e "$dst" ]; then
    echo "unable to set config"
    exit 1
  fi
  echo "$cfg" >> "$dst"
}

if [ -z "$1" ]; then
  echo "argument required"
  exit 1
fi
if [ ! -e "$CONFIG" ]; then
  echo "$CONFIG is missing"
  exit 1
fi

oclone "$@"
