#!/bin/bash
source $HOME/.bin/common
PASSWORD_KEY="passwords"
REBUILD_KEY="rebuild"
RELEASE_KEY="github-releases"
PERM_UPDATE_KEY="perm-pull"
PERM_PUSH_KEY="perm-push"
ENTER_KEY="enterkeys"
DMENU_LOCAL_KEY="dmenu-local"
AUTO_CLIP_KEY="auto-clip"
ARCH_CHROOT_KEY="archroot"
DMENU_APPS="vlc termite pavucontrol"
DMENU_LIST="$DMENU_APPS $PASSWORD_KEY"
BROWSER_WINDOW="Developer"
WSW_CYCLE_KEY="wsw-cycle"
CACHE_PATH=${HOME_CACHE}helper_cache/


function cycle-wsw()
{
    local active new
    new=3
    active=$(wsw --command active 2>&1 | cut -d " " -f 2 | cut -d "=" -f 2 | cut -d ")" -f 1)
    if [ $active -eq 3 ]; then
        new=2
    fi
    wsw --command change --profile $new
}

function dmenu-local()
{
    $HOME/.bin/dmenu-wrapper --browser "/usr/bin/firefox" --list "$DMENU_LIST" --temp "$USER_TMP" --urls "${SYNCED_CONF}urls.csv" "$@"
}

function auto-clip()
{
    source $PRIV_CONF
    auto-clipboard $PERM_LOCATION
}

function enter-keys()
{
    if [ -z $1 ]; then
        echo "must provide input"
    else
        using=$1
        ran=0
        if [ -e $PRIV_CONF ]; then
            result=$($PRIV_CONF $using)
            if [ ! -z "$result" ]; then
                ran=1
                enter-window-vals $BROWSER_WINDOW $result
            fi
        fi
        if [ $ran -eq 0 ]; then
            enter-window-vals $BROWSER_WINDOW $@
        fi
    fi
}

function push-pull-git-fxn()
{
    is_avail=$(test-ssh $BASE_SERVER)
    cpwd=$PWD
    for f_name in $(get-perm-objs); do
        f=$(basename $f_name)
        cd $f_name
        echo "$1: $f"
        if [[ $f == *${PERM_PERSONAL}* ]]; then
            if [ $is_avail -ne $IS_CONNECTED ]; then
                echo "**not available**"
                echo
                continue
            fi
        fi
        git $2
        echo
    done
    cd $cpwd
    update-time "perm-$2"
}

function update-chroot()
{
    epiphyte-archroot update
}

function arch-chroot-manage()
{
    if [ -d $CHROOT ]; then
        update-chroot
    fi
    if [ ! -d $CHROOT ]; then
        mkdir -p $CHROOT
        epiphtey-archroot build
        update-chroot
    fi
    update-time "archroot"
}

function perm-pull()
{
    push-pull-git-fxn "update" "pull"
}

function perm-push()
{
    push-pull-git-fxn "push" "push"
}

function passwords()
{
    keepassx2 $PASS_FILE
}

function rebuild-now()
{
    mkdir -p $CACHE_PATH
    rm ${CACHE_PATH}*
    for line in $(print-help | cut -d " " -f 5); do
        if [[ "$line" == "$REBUILD_KEY" ]]; then
            continue
        fi
        file_name=${CACHE_PATH}$line
        echo "#/bin/bash
helper_cache $line \$@" > $file_name
        chmod u+x $file_name
    done
}

function print-help()
{
    echo "
    $DMENU_LOCAL_KEY (dmenu wrapper for local operations)
    $PASSWORD_KEY (password management)
    $REBUILD_KEY (rebuild cache)
    $PERM_UPDATE_KEY (update pass databases)
    $PERM_PUSH_KEY (push pass databases)
    $ENTER_KEY (enter keys into a non-paste friendly place)
    $AUTO_CLIP_KEY (copy an entry to the clipboard from private aliases)
    $ARCH_CHROOT_KEY (arch-chroot management)
    $RELEASE_KEY (check if anything needs releasing)
    $WSW_CYCLE_KEY (cycle wsw profiles)
" | grep -v -e '^$' | sort
}

if [ ! -z $1 ]; then
    NEED_HELP=0
    case $1 in
        $WSW_CYCLE_KEY)
            cycle-wsw
            ;;
        $RELEASE_KEY)
            github-releases
            ;;
        $PASSWORD_KEY)
            passwords
            ;;
        $REBUILD_KEY)
            rebuild-now
            ;;
        $ENTER_KEY)
            enter-keys ${@:2}
            ;;
        $PERM_UPDATE_KEY)
            perm-pull
            ;;
        $PERM_PUSH_KEY)
            perm-push
            ;;
        $AUTO_CLIP_KEY)
            auto-clip
            ;;
        $ARCH_CHROOT_KEY)
            arch-chroot-manage
            ;;
        $DMENU_LOCAL_KEY)
            dmenu-local ${@:2}
            ;;
        *)
            NEED_HELP=1
            ;;
    esac
    
    if [ $NEED_HELP -eq 0 ]; then
         exit 0
    fi
fi

print-help
