#!/bin/bash
source $HOME/.bin/common

function stats()
{
    local last d
    last=""
    i3status | while :
    do
        read line
        d=$(cat $MAIN_STATS)
        if [ -z "$d" ]; then
            d="$last"
        else
            last="$d"
        fi
        echo "$d$line |" || exit 1
    done
}

function auto-clip()
{
    source $PRIV_CONF
    auto-clipboard $PERM_LOCATION
}

$1
