#!/bin/bash
source $HOME/.bin/common

function stats() {
    local last d
    last=""
    i3status | while :
    do
        read line
        d=$(cat $MAIN_STATS)
        if [ -z "$d" ]; then
            d="$last"
        else
            last="$d"
        fi
        echo "$d $line" || exit 1
    done
}

function auto-clip() {
    source $PRIV_CONF
    auto-clipboard $PERM_LOCATION
}

function _update-workspace() {
    local name
    name="$1:"$(echo "${@:3}" | tr '[:upper:]' '[:lower:]' | tr ' ' '|' | sed "s/^|//g")
    i3-msg rename workspace "$2" to "$name" > /dev/null
}

function _msgparse() {
    i3-msg -t $1 | tr '{' '\n' | tr '}' '\n' | tr ',' '\n' | sed 's/"//g'
}

function _lastworkspace() {
    local res
    res=$(echo "${@:2}" | grep "^$1:")
    if [ -z "$res" ]; then
        echo "$1"
    else
        echo "$res"
    fi
}

function _workspace() {
    local objs o lastnum current val workspaces lastworkspace
    lastnum=-1
    workspaces=$(_msgparse "get_workspaces" | grep -E "^name:" | cut -d ":" -f 2-)
    objs=$(_msgparse "get_tree" | grep -E "^(class|num):" | grep -v "num:\-" | cut -d " " -f 1 | grep -v "class:i3bar")
    for o in $(echo "$objs"); do
        val=$(echo $o | cut -d ":" -f 2)
        if echo "$o" | grep -q "^num:"; then
            if [ $lastnum -ne $val ]; then
                if [ $lastnum -ne -1 ]; then
                    lastworkspace=$(_lastworkspace "$lastnum" "$workspaces")
                    _update-workspace "$lastnum" "$lastworkspace" "$current"
                fi
                lastnum=$val
                current=""
            fi
        else
            current="$current $val"
        fi
    done
    lastworkspace=$(_lastworkspace "$lastnum" "$workspaces")
    _update-workspace "$lastnum" "$lastworkspace" "$current"
}

function workspacer() {
    while [ 1 -eq 1 ]; do
        _workspace
        sleep 1
    done
}

$1
