#!/bin/bash
source $HOME/.bin/common

function tray_reload()
{
    _kill_tray
}

function reload()
{
    _kill_tray "reload"
}

function restart()
{
    _kill_tray "restart"
}

function _kill_tray()
{
    pkill wsw-applet
    if [ ! -z "$1" ]; then
        i3-msg $1
    fi
}

function stats()
{
    local last d
    last=""
    i3status | while :
    do
        read line
        d=$(cat $MAIN_STATS)
        if [ -z "$d" ]; then
            d="$last"
        else
            last="$d"
        fi
        echo "$d$line|" || exit 1
    done
}

function auto-clip()
{
    source $PRIV_CONF
    auto-clipboard $PERM_LOCATION
}

function wsw-cycle()
{
    local active new
    new=3
    active=$(wsw --command active 2>&1 | cut -d " " -f 2 | cut -d "=" -f 2 | cut -d ")" -f 1)
    if [ $active -eq 3 ]; then
        new=2
    fi
    wsw --command change --profile $new
}

$1 $2 
