#!/bin/bash
source $HOME/.bin/common

APP_PATH=$(get-install-path "$2")
REPO="$3"
function install-object()
{
    sudo mkdir $APP_PATH
    sudo chown $USER:$USER $APP_PATH
    git clone git@github.com:enckse/$REPO.git $APP_PATH
}

function remove-object()
{
    sudo rm -rf $APP_PATH
}

case $1 in
    $INSTALL_KEYWORD)
        install-object
        ;;
    $REMOVE_KEYWORD)
        remove-object
        ;;
    *)
        exit 1
        ;;
esac
exit 0
