#!/bin/bash
source $HOME/.bin/displays
source $HOME/.bin/sound
source $HOME/.bin/common
LOCK_KEYWORD="lock"
SUSP_KEYWORD="sleep"
TGL_KEYWORD="toggle"
AUTO_KEYWORD="auto"
SLEEP_AFTER=600

function write-log()
{
    echo "$1" | systemd-cat -t "locking"
}

function get-i3lock()
{
    PID=$(pidof i3lock | cut -d " " -f 1)
    echo "$PID"
}

function lock-now()
{
    if [ ! -e $DISPLAY_UN ]; then
        PID=$(get-i3lock)
        
        if [ -z $PID ]; then
            write-log "locking..."
            i3lock -c 333333
            PID=$(get-i3lock)
            change-brightness $LOW_BRIGHT
            while [ ! -z $PID ];
            do
                PID=$(get-i3lock)
                sleep 1
            done
            write-log "unlocking..."
            change-brightness $MID_BRIGHT
        fi
    fi
}

function suspend-now()
{
    lock-now &
    if [ ! -e $DISPLAY_UN -a ! -e $DISPLAY_EN ]; then
        CUR_VOL=$(change-volume $VOL_STAT)
        CUR_VOL=$(echo $CUR_VOL)
        if [[ "$CUR_VOL" != "0" ]]; then
            write-log "muting volume"
            change-volume $VOL_MUTE
        fi

        rm -f $PROFILE_DEF
        PID=$(get-i3lock)
        SLEEP_COUNT=0
        if [ -z "$1" ]; then
            SLEEP_COUNT=$SLEEP_AFTER
        fi
        write-log "sleep setting: $SLEEP_COUNT"
        while [ ! -z $PID ];
        do
            if [ $SLEEP_COUNT -ge $SLEEP_AFTER ]; then
                write-log "sleeping..."
                SLEEP_COUNT=0
                systemctl suspend
            fi
            sleep 1
            SLEEP_COUNT=$((SLEEP_COUNT+1))
            PID=$(get-i3lock)
        done
        write-log "done sleeping"
    fi
}

function auto-lock-suspend()
{
    suspend-now "auto"
}

function toggle-locking()
{
    if [ -e $DISPLAY_UN ]; then
        rm $DISPLAY_UN
        touch $DISPLAY_EN
        exit 0
    fi

    if [ -e $DISPLAY_EN ]; then
        rm $DISPLAY_EN
        exit 0  
    fi
    touch $DISPLAY_UN
}

function print-help()
{
    echo "
    $LOCK_KEYWORD (lock)
    $SUSP_KEYWORD (sleep)
    $TGL_KEYWORD (toggle lock/sleep availability)
    $AUTO_KEYWORD (auto lock/sleep)
"
}

case $1 in
    $LOCK_KEYWORD)
        lock-now
        ;;
    $SUSP_KEYWORD)
        suspend-now
        ;;
    $TGL_KEYWORD)
        toggle-locking
        ;;
    $AUTO_KEYWORD)
        auto-lock-suspend
        ;;
    *)
        print-help
        ;;
esac
