#!/bin/bash
source /home/enck/.bin/common
CONF_HOME=${HOME_CONF}home
PACKAGE_SET=${CONF_HOME}/packages
RESOURCES="${USER_TMP}/resources"
PACKAGE_GROUPS="
xorg
base-devel
"
BOOTED=/tmp/user.booted-$(uptime -s | sed "s/ /-/g;s/:/-/g")
if [ ! -e $BOOTED ]; then
    echo "booting up..."
    # cleanup file
    rm -f $HOME/.python_history*
    rm -f $HOME/.wget-hsts*
    rm -f $HOME/.esd_auth*
    rm -f $HOME/.lesshst*
    rm -f $PROFILE_TMP*
    
    # packages
    /usr/bin/pacman -Qqe > $PACKAGE_SET
    echo "$PACKAGE_GROUPS" >> $PACKAGE_SET
    touch $BOOTED
fi

_dlresources() {
    local u name prev rsrcd
    rsrcd=$USER_TMP/rsc/
    mkdir -p $rsrcd
    if [ ! -e "$RESOURCES" ]; then
        echo "checking resources"
        touch $RESOURCES
        for u in $(cat $HOME_PERSONAL/track); do
            name=$rsrcd/$u.rsc
            prev=$name.prev
            touch $prev
            /usr/bin/pacman -Ss "^$u$" | head -n +1 > $name
            if [ $? -eq 0 ]; then
                diff -u $prev $name > /dev/null
                if [ $? -ne 0 ]; then
                    echo "$u has updated"
                fi
            fi
            mv $name $prev
        done
    fi
}

_resources() {
     _dlresources | systemd-cat -p err -t "maintain"
}

set-user-files() {
    local f v running vim_dir
    echo "set user files"

    # user tmp
    mkdir -p $USER_TMP
    find $USER_TMP* -mtime 1 -type f -exec rm {} \;
    find $USER_TMP -empty -type d -delete
    
    # vim
    for v in $(echo "undo swap"); do
        vim_dir=$HOME/.vim/$v
        mkdir -p $vim_dir
        find $vim_dir -mmin +1440 -type f -exec rm {} \;
    done
}

daily() {
    local f xsess
    f=$USER_TMP/maintain.$(date +%Y-%m-%d)
    if [ ! -e $f ]; then
        touch $f
        echo "running daily checks..."
        xsess=$HOME/.xsession-errors
        if [ -e $xsess ]; then
            cat $xsess >> $USER_TMP/xsession.$(date +%Y-%m-%d)
            rm -f $xsess
        fi
        check-syncing
    fi
}

check-syncing() {
    journalctl -t sync --since "7 days ago" | grep -q "local sync completed"
    if [ $? -ne 0 ]; then
        echo "no reset successful syncs" | systemd-cat -p err -t "maintain"
    fi
}

set-user-files
daily
_resources
