#!/bin/bash
MY_HOME=/home/enck/
source ${MY_HOME}.bin/common
CONF_HOME=${HOME_CONF}home
PKG_QUERY=$USER_TMP/package.query
PACKAGE_SET=${CONF_HOME}/packages
WEECHAT_PLUGINS=${USER_TMP}/weechat.plugins
IGNORED_PACKAGES="glib2"
PACKAGE_GROUPS="
i3
xorg
base-devel
"
BOOTED=/tmp/user.booted-$(uptime -s | sed "s/ /-/g;s/:/-/g")
if [ ! -e $BOOTED ]; then
    echo "booting up..."
    for f in $(echo "wget-hsts python_history esd_auth lesshst"); do
        fname=${MY_HOME}$f
        echo "deleting app file: $fname"
        rm -f $fname
    done
    for f in $(echo "$DISPLAY_UN $DISPLAY_EN $SND_MUTE $NET_SLEEP $PKG_QUERY"); do
        echo "deleting tmp file: $f"
        rm -f $f
    done
    for f in $(find $USER_TMP -type f | grep "${PROFILE_TMP}"); do
        echo "deleting profile: $f"
        rm -f $f
    done
    touch $BOOTED
fi

function weechat-logs()
{
    local logs
    logs=$USER_TMP/weechat/
    mkdir -p $logs
    running=$(pidof weechat)
    if [ -z "$running" ]; then
        echo "cleaning up weechat logs"
        for f in $(find $HOME/.weechat/logs/ -type f); do
            fname=${logs}$(basename $f)
            cat $f | grep -v -E "^[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9] [0-9][0-9]:[0-9][0-9]:[0-9][0-9][[:space:]]+(<|-)-" > $fname
            cp $f $fname.$(date +%s)
            mv $fname $f
        done
        if [ ! -e $WEECHAT_PLUGINS ]; then
            touch $WEECHAT_PLUGINS
            echo "downloading latest scripts"
            for p in $(echo "buffer_autoset autosort"); do
                tmpfile=$USER_TMP/$p.py
                curl -s https://www.weechat.org/files/scripts/$p.py > $tmpfile
                diff -u $MY_HOME/.weechat/python/$p.py $tmpfile > /dev/null
                if [ $? -ne 0 ]; then
                    echo "$p weechat plugin updated ($tmpfile)" | systemd-cat -p err -t maintain
                fi
            done
        fi
    fi
}

function check-timed-events()
{
    echo "checking timed events"
    all=""
    today=$(date +%Y-%m-%d)
    all="$today"
    for d in $(seq 1 7); do
        past=$(date +%Y-%m-%d -d "-$d days")
        all=$all"|$past"
    done
    year=$(date +%Y)
    months="($year-"$(date +%m)"|"$year-$(date -d "last month" +%m)")"
    all="($all)"
    if [ ! -e "$LAST_TIMES" ]; then
        touch $LAST_TIMES
    else
        warnings=""
        cnt=0
        for item in $(cat $LAST_TIMES); do
            cnt=$((cnt+1))
            i=$(echo $item | cut -d "," -f 1)
            d=$(echo $item | cut -d "," -f 2)
            echo $d | grep -q -E "$all"
            if [ $? -ne 0 ]; then
                _warn=1
                if [[ $i == "$PKGBUILD_IND"* ]]; then
                    if [[ $i == *"-git" ]]; then
                        echo $d | grep -q -E "$months"
                        if [ $? -eq 0 ]; then
                            _warn=0
                        fi
                    fi
                fi
                if [ $_warn -eq 1 ]; then
                    warnings="$warnings ${i}_(${d})"
                fi
            fi
        done
        if [ $cnt -ne $REQUIRED_EVENTS ]; then
            warnings=$warnings" wrong_number_of_events"
        fi
        if [ ! -z "$warnings" ]; then
            for w in $(echo $warnings); do
                changed=$(echo $w |  sed "s/_/ /g")
                echo -e "$changed" | systemd-cat -p err -t maintain
            done
        fi
    fi
}

function set-user-files()
{
    echo "set user files"

    # user tmp
    mkdir -p $USER_TMP
    find $USER_TMP* -mtime +1 -type f -exec rm {} \;
    find $USER_TMP -empty -type d -delete

    for f in $(find $USER_TMP -type f -mmin +30 | grep "dmenu"); do
        rm -f $f
    done

    # vim
    for v in $(echo "undo swap"); do
        vim_dir=$HOME/.vim/$v
        mkdir -p $vim_dir
        find $vim_dir -mmin +1440 -type f -exec rm {} \;
    done
    
    # packages
    if [ ! -e $PKG_QUERY ]; then
        running=$(pidof pacman)
        if [ -z "$running" ]; then
            /usr/bin/pacman -Qqe | grep -v -E "$IGNORED_PACKAGES" > $PACKAGE_SET
            echo "$PACKAGE_GROUPS" >> $PACKAGE_SET
            touch $PKG_QUERY
        fi
    fi
}

function process-logs()
{
    echo "checking pacman status"
    d=$(cat /var/log/pacman.log | grep $(date +%Y) | cut -d " " -f 1 | cut -d "[" -f 2 | sort | uniq | tail -n 1)
    pacman -Qm | systemd-cat -p err -t "maintain"
    update-time-log "pacman" $d
}

weechat-logs
set-user-files
process-logs
check-timed-events
