#!/bin/bash
STORAGE=/tmp/markdown-preview/
mkdir -p $STORAGE
find ${STORAGE}* -type f -mtime +1 -delete &> /dev/null
if [ -z "$1" ]; then
    echo "a markdown file is required"
    exit -1
fi

if [ ! -e "$1" ]; then
    echo "$1 is not a file"
    exit -1
fi

ID=$RANDOM
printf -v ID "%05d" $ID
NOW=$(date +%s)
FILE_NAME=${STORAGE}/$NOW-$ID.html
pandoc -o $FILE_NAME -f markdown $1
(chromium $FILE_NAME &) &>/dev/null
