#!/usr/bin/env bash
LOGS=~/.mutt/tmp/
MAILDIR=~/.mutt/maildir
_truncate() {
    local f s n
    for f in mbsync msmtp; do
        n=${LOGS}$f.log
        touch $n
        s=$(stat --printf="%s" $n)
        if [ $s -gt 1000000 ]; then
            mv $n $n.prev
        fi
    done
}

_count() {
    find $MAILDIR -type f | grep "/new/" | grep -v Trash | wc -l
}

_sync() {
    local prev curr
    date +"%Y-%m-%dT%H:%M:%S"
    prev=$(_count)
    mbsync --verbose -c ~/.mutt/etc/mbsyncrc -a fastmail 2>&1 | sed 's/^/    /g'
    curr=$(_count)
    if [ $prev -ne $curr ]; then
        if [ $curr -gt 0 ]; then
            terminal-notifier -title "New Mail" -message "Messages: $curr"
        fi
    fi
}

mkdir -p $LOGS
mkdir -p $MAILDIR
_truncate
_sync >> $LOGS/mbsync.log 2>&1
