#!/bin/bash
source $HOME/.bin/common
CRYPT_MNT=/mnt/crypt
MNT_SHARE=/mnt/Storage
CRYPT_ROOT=${SYNCED_PATH}/crypt.img
IS_MOUNTED=1
USB_KEYWORD="usb"
SHARE_KEYWORD="shares"
CRYPT_KEYWORD="crypt"
UCRYPT_KEYWORD="ucrypt"
KEYS_KEYWORD="keys"
UMNT_KEYWORD="umount"
MAPPER_NAME="crypt-img"
DEFCRYPT_KEYWORD="defcrypt"
REMCRYPT_KEYWORD="remcrypt"
OPENCRYPT_KEYWORD="opencrypt"
NEWMOUNTS="/tmp/crypts/"
SETUP_CRYPT="setup"
DEFCRYPT_SIZE="100M"
ADD_ALL_KEYS=1
SSH_KEY_PATH=${CRYPT_MNT}/ssh/
SSH_PUB_PATH=${SYNCED_PATH}ssh/
function add-keys()
{
    IS_MNT=$(is-mounted $CRYPT_MNT)
    if [ $IS_MNT -eq $IS_MOUNTED ]; then
        keys=$(find ${SSH_KEY_PATH}**/* -type f)
        for key in $keys; do
            short_name=$(echo ${key#${SSH_KEY_PATH}})
            entry=$(cat $SSH_PUB_PATH/mappings | grep ",$short_name,")
            if [ -z "$entry" ]; then
                echo "missing pubkey entry for $short_name"
                exit -1
            fi
            pub_key=$(echo $entry | cut -d "," -f 1)
            add_key=$(echo $entry | cut -d "," -f 3)
            if [ $add_key -lt 0 ]; then
                echo "ignoring $key"
                continue
            fi
            if [ ! -e "$SSH_PUB_PATH/pubkeys/$pub_key" ]; then
                echo "missing pub key $pub_key"
            fi
            if [ $1 -ne $ADD_ALL_KEYS ]; then
                if [ $add_key -ne $ADD_ALL_KEYS ]; then
                    continue
                fi
            fi
            ssh-add -l | grep -qE "$key"
            if [ $? -ne 0 ]; then
                echo "adding $key"
                ssh-add $key
            fi
        done
    else
        echo "keys not available"
        exit -1
    fi
}

function is-mounted()
{
    mount | grep -q $1
    if [ $? -eq 0 ]; then
        echo $IS_MOUNTED
    else
        echo 0
    fi
}

function print-help()
{
    echo "
    $SHARE_KEYWORD - mount local share(s)
    $UMNT_KEYWORD - umount local share(s)
    $CRYPT_KEYWORD - mount encrypted file image(s)
    $UCRYPT_KEYWORD - umount encrypted file image(s)
    $KEYS_KEYWORD - load ssh keys from crypt
    $USB_KEYWORD - mount a usb drive
    $DEFCRYPT_KEYWORD - define a new crypt (optional size)
    $REMCRYPT_KEYWORD - remove a crypt (required path to crypt)
    $OPENCRYPT_KEYWORD - open an encrypted image (required image file)
"
}

function mount-crypt()
{
    IS_MNT=$(is-mounted $CRYPT_MNT)
    if [ $IS_MNT -eq $IS_MOUNTED ]; then
        echo "already mounted"
        exit -1
    fi

    SYNC_CRYPT=0
    if [ -e $USER_CRYPT ]; then
        current_check=$(sha512sum $USER_CRYPT | cut -d " " -f 1)
        new_check=$(sha512sum $CRYPT_ROOT | cut -d " " -f 1)
        if [[ $current_check == $new_check ]]; then
            echo "no change"
            SYNC_CRYPT=1
        fi 
    fi
    if [ $SYNC_CRYPT -eq 0 ]; then
        echo "copying crypt.img..."
        cp $CRYPT_ROOT $USER_CRYPT
    fi
    open-crypt "--readonly" "$USER_CRYPT" "$MAPPER_NAME" "$CRYPT_MNT" "open"
}

function rem-crypt()
{
    if [ -z $2 ]; then
        echo "requires an object to remove/cleanup"
        exit -1
    fi
    umount_item=${2%/}
    IS_MNT=$(is-mounted $umount_item)
    if [ $IS_MNT -ne $IS_MOUNTED ]; then
        echo "not mounted"
        exit -1
    fi

    use_mapper=$3
    if [ -z $use_mapper ]; then
        use_mapper=$(basename $umount_item)
    fi

    close-crypt $umount_item $use_mapper    
}

function crypt-name()
{
    echo $(uuidgen)"-crypt-mapper"
}

function crypt-place()
{
    mkdir -p ${NEWMOUNTS}
    MOUNT_CRYPT="${NEWMOUNTS}$1"
    echo $MOUNT_CRYPT
}

function def-crypt()
{
    size=$2
    MAPPING=$(crypt-name)
    if [ -z $size ]; then
        size=$DEFCRYPT_SIZE
    fi

    check_size=$(echo "$size" | grep "^[0-9][0-9]*" | grep -E "M|G")
    if [ -z "$check_size" ]; then
        echo "invalid size (expecting [0-9]+(M|G): $size"
        exit -1
    fi

    file_name=$PWD/$MAPPING".img"
    DEF_MOUNT=$(crypt-place "$MAPPING")

    echo "
creating file $file_name ($size)
mounting: $DEF_MOUNT
mapper: $MAPPING
"
    read -p "continue (y/n)? " yn
    if [[ $yn == "y" ]]; then
        dd if=/dev/zero of=$file_name bs=1 count=0 seek=$size
        sudo cryptsetup luksFormat $file_name
        open-crypt "" "$file_name" "$MAPPING" "$DEF_MOUNT" "$SETUP_CRYPT"
        df -h $DEF_MOUNT
    fi
}

function crypt-mounting()
{
    if [ -z "$2" ]; then
        echo "requires an image to mount"
        exit -1
    fi

    MAPPING=$(crypt-name)
    DEF_MOUNT=$(crypt-place "$MAPPING")
    echo $MAPPING
    echo $DEF_MOUNT
    open-crypt "" "$2" "$MAPPING" "$DEF_MOUNT" "mounting"
}

function open-crypt()
{
    sudo cryptsetup luksOpen $1 $2 $3
    sudo mkdir -p $4
    if [[ "$5" == "$SETUP_CRYPT" ]]; then
        sudo mkfs.ext4 /dev/mapper/$3
    fi
    sudo mount /dev/mapper/$3 $4
    if [[ "$5" == "$SETUP_CRYPT" ]]; then
        sudo chown -R $USER:$USER $4
        rm -rf $4/lost+found
    fi
}

function close-crypt()
{
    sudo umount $1
    sudo cryptsetup luksClose $2
}

function umount-crypt()
{
    rem-crypt "" "$CRYPT_MNT" "$MAPPER_NAME"
}

function mount-usb()
{
    sudo fdisk -l | grep "Disk /dev/[sd]" | cut -d ' ' -f 2,3,4 | cut -d ',' -f 1
    echo "Select drive:"
    read USBDISK
    USBDISK+="1"
    sudo mount $USBDISK /mnt/usb
}

function mount-share()
{
    IS_MNT=$(is-mounted $MNT_SHARE)
    if [ $IS_MNT -eq $IS_MOUNTED ]; then
        echo "already mounted"
        exit -1
    fi

    IS_MNT=$(is-mounted $CRYPT_MNT)
    if [ $IS_MNT -eq $IS_MOUNTED ]; then
        sshfs base:$MNT_SHARE $MNT_SHARE
    else
        echo "must mount crypt first"
        exit -1
    fi
}

function umount-share()
{
    IS_MNT=$(is-mounted $MNT_SHARE)
    if [ $IS_MNT -eq $IS_MOUNTED ]; then
        sudo umount $MNT_SHARE
    fi    
}

case $1 in
    $SHARE_KEYWORD)
        mount-share
        ;;
    $UMNT_KEYWORD)
        umount-share
        ;;
    $CRYPT_KEYWORD)
        mount-crypt
        add-keys 0
        ;;
    $UCRYPT_KEYWORD)
        umount-crypt
        ;;
    $KEYS_KEYWORD)
        add-keys $ADD_ALL_KEYS
        ;;
    $USB_KEYWORD)
        mount-usb
        ;;
    $DEFCRYPT_KEYWORD)
        def-crypt $@
        ;;
    $REMCRYPT_KEYWORD)
        rem-crypt $@
        ;;
    $OPENCRYPT_KEYWORD)
        crypt-mounting $@
        ;;
    *)
        print-help
        ;;
esac
