#!/bin/bash
source $HOME/.bin/common
MUSIC=$HOME/.cache/music
cwd=$PWD
cd $MUSIC
oldifs=$IFS
IFS=$'\n'
current=""
for d in $(ls); do
    current="$current
$d"
done
for line in $(cat $HOME_PERSONAL/music); do
    echo "getting $line"
    chr=${line::1}
    chr=$(echo "$chr" | tr '[:lower:]' '[:upper:]')
    rsync --protect-args --include="*/" --include="*.mp3" --exclude="*" -avc -e "ssh" "$BASE_SERVER:store/Home/Media/Music/$chr/$line" . --delete-after
    current=$(echo "$current" | grep -v "$line")
done
if [ ! -z "$current" ]; then
    for f in $(echo "$current"); do
        echo "purging $f"
        rm -r $f
    done
fi
for f in $(find . -type d -empty); do
    rmdir $f
done
IFS=$oldifs
cd $cwd
