#!/bin/bash
source $HOME/.bin/common
MUSIC=$HOME/.cache/music
cwd=$PWD
cd $MUSIC
oldifs=$IFS
IFS=$'\n'
function create-list() {
    has=""
    for l in $(cat $HOME_PERSONAL/music); do
        c=$(echo "$l" | cut -c1 | tr '[:lower:]' '[:upper:]')
        echo "$has" | tr ' ' '\n' | grep -q "$c"
        if [ $? -ne 0 ]; then
            echo "$c/"
        fi
        echo "$c/$l/***"
        has="$c $has"
    done
}
tmpfile=$(mktemp)
create-list > $tmpfile
IFS=$oldifs
rsync -av --include-from $tmpfile --exclude="*" -e "ssh" "$BASE_SERVER:store/Home/Media/Music/" . --delete-after
cd $cwd
