#!/bin/bash
source $HOME/.bin/common
create-list() {
    local idx chr cnt line musicfile
    musicfile="$PERM_MISC/music"
    idx=1
    cnt=$(cat $musicfile | wc -l)
    while [ $idx -le $cnt ]; do
        line=$(cat $musicfile | head -n $idx | tail -n 1)
        chr=$(echo "$line" | cut -c1 | tr '[:lower:]' '[:upper:]')"/"
        echo "$chr"
        echo "$chr$line/***"
        idx=$((idx+1))
    done
}

_music() { 
    tmpfile=$USER_TMP/music.$(date +%s)
    create-list | sort -u > $tmpfile
    rsync -av --include-from $tmpfile --exclude="*" -e "ssh" "$BASE_SERVER:store/Home/Media/Music/" $HOME_CACHE/music --delete-after --delete-excluded
}

_music
