#!/bin/bash
source $HOME/.bin/common
NETWORKS=$SYNCED_PATH/network/
DEFAULT_NETWORK="default"
CACHED=$HOME/.cache/networking
LIST_KEY="list"
RELOAD_KEY="reload"
HELP_KEY="help"

_connect() {
    local conf device
    echo "connecting: $1"
    device=$(echo "$1" | cut -d "/" -f 1)
    conf=$NETWORKS$1.conf
    sudo pkill wpa_supplicant
    if [ -e $conf ]; then
        echo "running supplicant"
        echo "$1" > $CACHED
        sudo /usr/bin/wpa_supplicant -c $conf -i $device -B
    fi
}

_reload() {
    if [ -e "$CACHED" ]; then
        network $(cat $CACHED)
    fi
}

networks=$(find $NETWORKS -type f | sed "s#$NETWORKS##g" | sed "s/\.conf//g" | tr '\n' ' ')" $DEFAULT_NETWORK"
action=$1
if [ -z "$1" ]; then
    action="$HELP_KEY"
fi
case $action in
    "$HELP_KEY")
        echo "$networks $HELP_KEY $LIST_KEY $RELOAD_KEY" | sort
        ;;
    "$LIST_KEY")
        echo "$networks"
        ;;
    "$RELOAD_KEY")
        _reload
        ;;
    *)
        echo "$networks" | tr ' ' '\n' | grep -q "$action"
        if [ $? -eq 0 ]; then
            _connect "$1"
        else
            echo "unknown network: $action"
        fi
        ;;
esac
