#!/bin/bash
NETWORKS=/etc/networks/
NETWORK_CACHE=/home/enck/.cache/network
NETWORK_KILL=$NETWORK_CACHE.pid
HELP_KEY="help"

_get-networks() {
    find $NETWORKS -type f | sed "s#$NETWORKS##g" | sed "s/\.conf//g" | tr '\n' ' '
}
action=$1
case $action in
    "$HELP_KEY")
        echo "$HELP_KEY $RELOAD_KEY "$(_get-networks) | tr ' ' '\n' | sort | tr '\n' ' '
        ;;
    *)
        if [ -e "$NETWORKS$action.conf" ]; then
            echo "$action" > $NETWORK_CACHE
            echo "changed"
        fi
esac
