#!/usr/bin/env bash
CACHE="$HOME/.cache/notes"
MOUNT="$CACHE/mount"
DEST="$CACHE/files"
mkdir -p "$MOUNT" "$DEST"
if ! sudo jmtpfs "$MOUNT" >/dev/null; then
  echo "failed to mount"
  exit 1
fi

_error() {
  echo "[ERROR] $1"
}

EXPORTED="$MOUNT/Supernote/EXPORT"
for file in $(sudo find "$EXPORTED" -type f -iname "*.pdf"); do
  echo "copying: $file"
  if ! sudo cp "$file" "$DEST/"; then
    _error "unable to copy"
  fi
done
if ! sudo chown -R enck:enck "$DEST"; then
  _error "unable to chown"
fi
PDFS=$(find . -type f -iname "*.pdf" | wc -l)
if [ "$PDFS" -gt 0 ]; then
  if ! sudo cp ./*.pdf "$MOUNT/Supernote/Document/"; then
    _error "failed to copy pdfs"
  fi
fi

sudo umount "$MOUNT"
echo "files in"
echo "  $DEST"
