#!/bin/bash
NAME="nspawn"
AUTO_COMPLETE=/usr/share/bash-completion/completions/nspawn
source $HOME/.bin/common
source $HOME/.bin/common
$HOME/.bin/install-git $1 "$NAME" "${NAME}-info"
if [ $? -ne 0 ]; then
    NSPAWN=$(get-install-path $NAME)/nspawn
    if [ ! -f $AUTO_COMPLETE ]; then
        echo "Creating bash auto-completion script"
        sudo ln -s ${NSPAWN}_autocompletion $AUTO_COMPLETE
        . $AUTO_COMPLETE
    fi

    export NSPAWN_INFO_SCREEN=1
    export NSPAWN_INFO_CONTAINERS="/opt/workspace/containers"
    export NSPAWN_INFO_ARGS="--bind /opt/workspace/shared"
    export NSPAWN_INFO_JOURNAL="$NSPAWN_JOURNAL_CATEGORY"
    $NSPAWN $@
fi

