#!/bin/bash
source $HOME/.cache/pastebin.config
INPUT="${1:-/proc/${$}/fd/0}"
data=$(cat $INPUT)
title=$(date +%Y-%m-%dT%H-%M-%S)-$(uuidgen)
if [ -z "$data" ]; then
    echo "no data"
    exit -1
fi

function check-value()
{
    if [ -z "$1" ]; then
        echo "$2 variable not set"
        exit -1
    fi
}

check-value "$PASTE_API_TOKEN" "PASTE_API_TOKEN"
check-value "$PASTE_URL" "PASTE_URL"
check-value "$PASTE_CERT" "PASTE_CERT"

function do-paste()
{
    curl -s $PASTE_URL \
        -d api.token=$PASTE_API_TOKEN \
        -d content="$data" \
        -d title="$title" \
        --insecure \
        --cert $PASTE_CERT
}

do-paste > /dev/null
