#!/bin/bash
source $HOME/.bin/common
tmpfile=/tmp/gitgo

_find() {
    for file in $(find . -type f -name "Gopkg.toml"); do
        cat $file | grep -E "(\s*(name|branch|version)\s*=|constraint)" | sed "s/\s*//g"
        echo
    done
}

_item() {
    echo " $1 -> $2"
    echo
}

_constraints() {
    current=""
    verison=""
    for f in $(cat $tmpfile); do
        if [[ "$f" == "[[constraint]]" ]]; then
            if [ ! -z "$current" ]; then
                _item "$current" "$version"
            fi
            current=""
            version=""
            continue
        fi
        val=$(echo "$f" | cut -d "=" -f 2 | sed 's/"//g')
        if echo "$f" | grep -q "^name"; then
            current=$val
        else
            version=$val
        fi
    done
    _item "$current" "$version"
}

_pkgbuilds() {
    p=pkgbuilds
    if [ ! -d "$p" ]; then
        git clone epiphyte:pkgbuilds
    fi
    for f in $(find $p/ -type f -name "PKGBUILD"); do
        if cat $f | grep -q "go"; then
            d=$(dirname $f)
            for r in $(echo $d | cut -d "/" -f 2,3 | sed "s#/#:#g"); do
                if echo $r | grep -q -E "pkgseed|popularch"; then
                    r=$(echo "$r" | sed "s/epiphyte/enckse/g")
                fi
                d=$(echo "$r" | cut -d ":" -f 2)
                if [ ! -d "$d" ]; then
                    git clone $r
                fi
            done
        fi
    done
}

_versions() {
    local repos r t c refs
    repos=${HOME_PERSONAL}repos
    if [ ! -e "$repos" ]; then
        echo "missing repo file definitions"
        exit 1
    fi
    for r in $(cat $repos); do
        refs=$(git ls-remote $r | sed "s/\t/ /g")
        t=$(echo "$refs" | grep "refs/tags/" | grep "\{\}" | sort -t '/' -k 3 -V | tail -n 1 | cut -d " " -f 1)
        c=$(echo "$refs" | grep "HEAD" | tail -n 1 | cut -d " " -f 1)
        if [[ "$t" != "$c" ]]; then
            echo "$r release available"
        fi
    done
}

function _deploy() {
    local cwd name
    cwd=$PWD
    if [ -z "$1" ]; then
        echo "required file to add is missing"
    else
        if [ -e "$1" ]; then
            cd $HOME_REPO
            name=$(basename $1)
            cp $cwd/$1 $name
            repo-add enckse.db.tar.gz $name
            cd $cwd
        else
            echo "file does not exist"
        fi
    fi
}

if [ -z "$1" ]; then
    echo "command required"
    exit 1
fi
case "$1" in
    "gitgo")
        read -p "download all go-repos and get deps? (Y/n) " dl
        if [[ "$dl" == "n" ]]; then
            echo "cancelled"
            exit 1
        fi
        _pkgbuilds
        _find | grep -v "^$" > $tmpfile
        _constraints | sort -u
        echo
        ;;
    "versions")
        _versions
        ;;
    "deploy")
        _deploy $2
        ;;
    *)
        echo "unknown command"
        ;;
esac
