#!/bin/bash
source $HOME/.bin/common

_search() {
    local _search
    if [ -d $SBH_STORE ]; then
        _search=""
        if [ ! -z "$1" ]; then
            _search="$@"
            cat ${SBH_STORE}* | grep -E "$_search" | awk '{printf "%s %s\n", i++".", $0}' | tee $SBH_LAST
        fi
    fi
}

_last() {
    local cmd grepping
    if [ -s $SBH_LAST ]; then
        grepping=""
        if [ ! -z "$1" ]; then
            grepping="^$1\."
        fi
        cmd=$(cat $SBH_LAST | grep "$grepping" | tail -n 1 | cut -d " " -f 2-)
        eval $cmd
    fi
}


if [ -z "$1" ]; then
    echo "no input given for search or recall"
    exit 1
fi
did=1
if [ -z "$2" ]; then
    re='^[0-9]+$'
    if [[ "$1" =~ $re ]] ; then
        did=0
        _last "$1"
    fi
fi
if [ $did -eq 1 ]; then
    _search "$@"
fi
