#!/bin/bash
if [ -z "$1" ]; then
    echo "requires a search term"
    exit -1
fi
SEARCH=""
for term in $@; do
    SEARCH=$SEARCH" $(perl -MURI::Escape -e 'print uri_escape($ARGV[0]);' "$term")"
done
chromium "http://www.google.com/search?q=$SEARCH"
