#!/bin/bash
source $HOME/.bin/common
WORKING=/opt/workspace/shared
STAGE=$USER_TMP/git/
DATE=`date +%Y-%m-%d`
SNAP_FILE=$PWD/snapshot-$DATE.tar.gz
mkdir -p $STAGE
for f in $(ls $WORKING); do
	REPO="$WORKING/$f"
	if [ -e "$REPO/.git" ]; then
		cd $REPO
        echo "bundling $f"
		git bundle create $STAGE$f.bundle --all &> /dev/null
	fi
done
CUR_DIR=$PWD
cd $STAGE && tar -cvzf $SNAP_FILE * && cd $CUR_DIR
gpg -c $SNAP_FILE
rm -f $SNAP_FILE
rm -rf $STAGE
