#!/bin/bash
VOL_MUTE="mute"

function get-volume-help()
{
    echo "
    $1 $2 $VOL_MUTE (toggle sound on/off)
    "
}

function change-volume()
{
    case $1 in
        $VOL_MUTE)
            pamixer -m
            ;;
        *)
            echo "unknown command $1"
            ;;
    esac
}
