#!/bin/bash
VOL_MUTE="mute"
VOL_STAT="status"

# Function get sound/volume help
function get-volume-help()
{
    echo "
    $1 $2 $VOL_MUTE (toggle sound on/off)
    $1 $2 $VOL_STAT (volume status/level)
    "
}

# Control volume using amixer
function change-volume()
{
    case $1 in
        $VOL_MUTE)
            SUBCMD="1+ toggle"
            ;;
        $VOL_STAT)
            VOL_STAT=$(amixer sget Master | grep Mono:)
            echo $VOL_STAT | grep -q "\[off\]"
            if [ $? -ne 0 ]; then
                VALUE=$(echo $VOL_STAT | cut -d "[" -f 2 | cut -d "]" -f 1)
                VOL_STAT=$VALUE
            fi
            
            VOL_STAT=$(echo $VOL_STAT | awk '{printf "%3.0f", $VOL_STAT}')
            ECHO_VAL="$VOL_STAT"
            ;;
        *)
            echo "unknown command $1"
            ;;
    esac
    if [ ! -z "$SUBCMD" ]; then
        COMPLETED="amixer sset Master $SUBCMD > /dev/null"
    fi

    if [ -z $ECHO_VAL ]; then
        if [ -z "$COMPLETED" ]; then
            echo "invalid options specified"
            exit -1
        fi
        $COMPLETED
    else
        echo "$ECHO_VAL"
    fi
}
