#!/bin/bash
LOCATION=/var/lib/machines/
TEMPLATE="new"
CONFIG=".template"
TEMPLATE_PATH=${LOCATION}$TEMPLATE
TEMPLATE_CONF=$TEMPLATE_PATH$CONFIG

if [ ! -e $TEMPLATE_CONF ]; then
    echo "$TEMPLATE_CONF is required..."
    exit -1
fi

if [ ! -d "$TEMPLATE_PATH" ]; then
    echo "$TEMPLATE_PATH must be a pacstrap container..."
    exit -1
fi

ETC_NSPAWN=/etc/systemd/nspawn/
if [ -z "$1" ]; then
    echo "name required..."
    exit -1
fi

NEW_PATH=${LOCATION}$1
NEW_CONF=$ETC_NSPAWN$1".nspawn"
if [ -d $NEW_PATH ] || [ -e $NEW_CONF ]; then
    echo "$1 already exists..."
    exit -1
fi

sudo mkdir -p $ETC_NSPAWN
NEW_BASIS_TEMPLATE=$ETC_NSPAWN${TEMPLATE}.nspawn
if [ ! -e $NEW_BASIS_TEMPLATE ]; then
    sudo ln -s $TEMPLATE_CONF $NEW_BASIS_TEMPLATE
fi

sudo cp -R $TEMPLATE_PATH $NEW_PATH
sudo cp $TEMPLATE_CONF $NEW_CONF
