#!/bin/bash
JUMP_DEF=$HOME/.cache/ssh.jumps
DELIMITER=","
HELP_KEY="--help"
ARG=$1
function do-jump()
{
    if [ ! -e $JUMP_DEF ]; then
        echo "$JUMP_DEF does not exist"
        exit -1
    fi

    if [ -z $1 ]; then
        echo "requires a destination"
        exit -1
    fi

    matched=$(cat $JUMP_DEF | grep "$DELIMITER$ARG$DELIMITER")
    if [ -z $matched ]; then
        echo "no machine found matching $1"
        exit -1
    fi

    jump=$(echo $matched | cut -d "$DELIMITER" -f 1)
    args=$(echo $matched | cut -d "$DELIMITER" -f 3)
    if [ ! -z $args ]; then
        args="-o $args"
    fi
    ssh -t $jump ssh $1 $args
}

function print-help()
{
    if [ -e $JUMP_DEF ]; then
        for line in $(cat $JUMP_DEF); do
            avail=$(echo $line | cut -d "$DELIMITER" -f 2)
            host=$(echo $line | cut -d "$DELIMITER" -f 1)
            args=$(echo $line | cut -d "$DELIMITER" -f 3)
            echo "    $avail (through $host) $args"
        done
    fi
}

if [ -z $ARG ]; then
    ARG=$HELP_KEY
fi

case $ARG in
    $HELP_KEY)
        print-help
        ;;
    *)
        do-jump "$ARG"
        ;;
esac
