#!/bin/bash
source $HOME/.bin/common
FULL="$HOME/.config/genericon/"
DELIMIT="|"

function output-full()
{
    img=$(echo $1 | cut -d "$DELIMIT" -f 1)
    res=${FULL}$img.png
    echo "$1" | grep -q "$DELIMIT"
    if [ $? -eq 0 ]; then
        tip=$(echo $1 | cut -d "$DELIMIT" -f 2)
    fi
    json='{"path": "'$res'"'
    if [ ! -z $tip ]; then
        json=$json', "tooltip": "'$tip'"'
    fi 
    echo $json'}'
}

function touchpad-status()
{
    status=$(toggle-touchpad "status")
    IMAGE="mouse"
    if [ $status -gt 0 ]; then
        IMAGE="touchpad"
    fi
    echo $IMAGE
}

function backlight-status()
{
    brightness=$(xbacklight | awk '{printf "%3.0f", $1}')
    IMAGE="unknown"
    if [ $brightness -gt 75 ]; then
        IMAGE="high"
    else
        if [ $brightness -gt 30 ]; then
            IMAGE="mid"
        else
            IMAGE="low"
        fi
    fi
    echo $IMAGE${DELIMIT}$(xbacklight | cut -d "." -f 1)
}

function workplace-status()
{
    if [ -e $WORKPLACE_WORKING ]; then
        echo "mobile"
    else
        echo "docked"
    fi
}

function locking-status()
{
    if [ -e $DISPLAY_UN ]; then
        echo "unlocked"
    else
        if [ -e $DISPLAY_EN ]; then
            echo "running"
        else
            echo "display"
        fi
    fi
}

case $1 in
    "workplace")
        cmd=workplace-status
        ;;
    "locking")
        cmd=locking-status
        ;;
    "backlight")
        cmd=backlight-status
        ;;
    "touchpad")
        cmd=touchpad-status
        ;;
esac

if [ ! -z $cmd ]; then
    result=$($cmd)
    output-full $result
fi
