#!/bin/bash
source $HOME/.bin/common
GIT_PARTIAL_PATTERN="weechat|random_seed"

_get-git-folders() {
    local res f d
    res=""
    for d in "$HOME/workspace" "${PERM_LOCATION}"; do
        for f in $(find $d -maxdepth 2 -type d | sort); do
            if [ ! -d "$f/.git" ]; then
                continue
            fi
            res=$res" "$f
        done
    done
    echo $res
}

update-git() {
    if [ ! -e $GIT_CHANGES ]; then
        git-changing > $GIT_CHANGES
    fi
}

_brightness() {
    local b
    b=$(xrandr --current --verbose | grep "Brightness" | \
        cut -d ":" -f 2 | sed "s/0\.//g" | sed "s/1\.0/100/g" | \
        tail -n 1 | awk '{printf "%3.0f", $1}' | sed "s/^[ \t]*//g")
    printf '\xf0\x9f\x94\x86 %3i' $b    
}

_battery() {
    local charging charge val b _path _bat val combined v
    charging=$(cat /sys/class/power_supply/AC/online)
    charge="-"
    if [ $charging -eq 1 ]; then
        charge="+"
    fi
    val=""
    for b in $(echo '0 1'); do
        _path='/sys/class/power_supply/BAT'$b'/capacity'
        if [ -e $_path ]; then
            _bat=$(cat $_path)
            val="$val,$_bat"
        fi
    done
    val=$(echo "$val" | sed "s/^,//g")
    combined=0
    for v in $(echo $val | sed "s/,/ /g"); do
        combined=$((combined+v))
    done
    if [ $combined -lt 20 ]; then
        if [[ "$charge" == "-" ]]; then
            notify-send --urgency=critical Battery "low"
        fi
    fi
    printf '\xf0\x9f\x94\x8b (%3s)%s' $val $charge
}

get-all-changes() {
    git update-index -q --refresh 
    git diff-index --name-only HEAD --
    git status -sb | grep 'ahead'
    git ls-files --other --exclude-standard
}

git-changing() {
    local cwd d_paths d local_res first
    cwd=$PWD
    d_paths="/etc $HOME $SYNCED_PATH $HOME_PERSONAL "$(_get-git-folders)
    for d in $(echo "$d_paths"); do
        if [ ! -d "$d/.git" ]; then
            continue
        fi
        cd $d
        local_res=$(get-all-changes | grep -E -v "$GIT_PARTIAL_PATTERN")
        if [ ! -z "$local_res" ]; then
            if [ -z $first ]; then
                echo "uncommitted changes"
            fi
            echo -e "$d${RED_TEXT}"
            echo -e "$local_res${NORM_TEXT}" | sed "s/^/    /g"
            first="false"
        fi
    done
    cd $cwd
}

_up() {
    local last t n res check
    check=30
    res=$USER_TMP/.online.status
    last=$USER_TMP/.online
    if [ -e $res ]; then
        if [[ $(cat $res) == "offline" ]]; then
            check=5
        fi
    else
        rm -f $last
    fi
    if [ -e $last ]; then
        t=$(cat $last)
        n=$(date +%s)
        t=$((n-t))
        if [ $t -gt $check ]; then
            rm -f $last
        fi
    fi
    if [ ! -e $last ]; then 
        curl -s https://voidedtech.network > /dev/null
        if [ $? -eq 0 ]; then
            echo "online" > $res
            touch $SYS_ONLINE
        else
            echo "offline" > $res
            rm -f $SYS_ONLINE
        fi
        date +%s > $last
    fi
}

_unread() {
    local cnt
    cnt=$($HOME_BIN/email count | cut -d " " -f 1)
    if [ $cnt -gt 0 ]; then
        printf " %3s UNREAD |" "$cnt"
    fi
}

stats() {
    local _git_text _last_cnt bright bat emails
    _git_text=""
    _last_cnt=0
    while [ 1 -eq 1 ]; do
        _up &
        sleep 0.75
        _git_cnt=0
        if [ -e $GIT_CHANGES ]; then
            _git_cnt=$(cat $GIT_CHANGES | grep "    " | wc -l)
        else
            _git_cnt=$_last_cnt
        fi
        _last_cnt=$_git_cnt
        if [ $_git_cnt -gt 0 ]; then
            _git_text=$(printf "$_last_cnt HEAD^ |")
        else
            _git_text=""
        fi
        update-git &
        bright=$(_brightness)
        bat=$(_battery)
        emails=$(_unread)
        echo "$_git_text$emails $bat | $bright |" > $MAIN_STATS
    done
}

stats
