#!/bin/bash
source $HOME/.bin/common

function update-git() {
    if [ ! -e $GIT_CHANGES ]; then
        git-changing > $GIT_CHANGES
    fi
}

function _brightness() {
    local b
    b=$(xrandr --current --verbose | grep "Brightness" | \
        cut -d ":" -f 2 | sed "s/0\.//g" | sed "s/1\.0/100/g" | \
        tail -n 1 | awk '{printf "%3.0f", $1}' | sed "s/^[ \t]*//g")
    printf '\xf0\x9f\x94\x86 %3i' $b    
}

function _battery() {
    local charging charge val b _path _bat val combined
    charging=$(cat /sys/class/power_supply/AC/online)
    charge="-"
    if [ $charging -eq 1 ]; then
        charge="+"
    fi
    val=""
    for b in $(echo '0 1'); do
        _path='/sys/class/power_supply/BAT'$b'/capacity'
        if [ -e $_path ]; then
            _bat=$(cat $_path)
            val="$val,$_bat"
        fi
    done
    val=$(echo "$val" | sed "s/^,//g")
    combined=0
    for v in $(echo $val | sed "s/,/ /g"); do
        combined=$((combined+v))
    done
    if [ $combined -lt 20 ]; then
        if [[ "$charge" == "-" ]]; then
            notify-send --urgency=critical Battery "low"
        fi
    fi
    printf '\xf0\x9f\x94\x8b (%3s)%s' $val $charge
}

function _sound() {
    local icon level
    icon="\xf0\x9f\x94\x8a"
    if [[ $(pamixer --get-mute) == 'true' ]]; then
        icon='\xf0\x9f\x94\x87'
    fi
    level=$(pamixer --get-volume)
    printf "$icon %3i" $level
}

function get-all-changes() {
    git update-index -q --refresh 
    git diff-index --name-only HEAD --
    git status -sb | grep 'ahead'
}

function git-changing() {
    local cwd d_paths d local_res first
    cwd=$PWD
    d_paths="/etc $HOME $SYNCED_PATH "$(_get-perm-objs)" "$(_get-workspace-objs)
    for d in $(echo "$d_paths"); do
        if [ ! -d "$d/.git" ]; then
            continue
        fi
        cd $d
        local_res=$(get-all-changes "$d")
        if [ -e "$GIT_PARTIAL_TMP" ]; then
            local_res=$(echo "$local_res" | grep -E -v "$GIT_PARTIAL_PATTERN")
        fi
        if [ ! -z "$local_res" ]; then
            if [ -z $first ]; then
                echo "uncommitted changes"
            fi
            echo -e "$d${RED_TEXT}"
            echo -e "$local_res${NORM_TEXT}" | sed "s/^/    /g"
            first="false"
        fi
    done
    touch $GIT_PARTIAL_TMP
    cd $cwd
}

function _up() {
    local result last t n res check
    check=30
    res=$USER_TMP/.online.status
    last=$USER_TMP/.online
    if [ -e $res ]; then
        if [[ $(cat $res) == "offline" ]]; then
            check=5
        fi
    else
        rm -f $last
    fi
    if [ -e $last ]; then
        t=$(cat $last)
        n=$(date +%s)
        t=$((n-t))
        if [ $t -gt $check ]; then
            rm -f $last
        fi
    fi
    if [ ! -e $last ]; then 
        curl -s https://voidedtech.network > /dev/null
        if [ $? -eq 0 ]; then
            echo "online" > $res
        else
            echo "offline" > $res
        fi
        date +%s > $last
    fi
    if [[ $(cat $res) == "online" ]]; then
        result='\xf0\x9f\x94\xb5'
    else
        result='\xf0\x9f\x94\xb4'
    fi
    printf "$result"
}

function stats() {
    local _last_git _git_text _last_cnt _partial bright muting bat disp up
    _last_git=0
    _git_text=""
    _last_cnt=0
    _partial=0
    while [ 1 -eq 1 ]; do
        sleep 0.1
        _partial=$((_partial+1))
        if [ $_partial -lt 5 ]; then
            continue
        fi
        _partial=0
        if [ $_last_git -eq 0 ]; then
            _git_cnt=0
            if [ -e $GIT_CHANGES ]; then
                _git_cnt=$(cat $GIT_CHANGES | grep "    " | wc -l)
            else
                _git_cnt=$_last_cnt
            fi
            _last_cnt=$_git_cnt
            _git_text=" git notices|"
            if [ $_git_cnt -eq 0 ]; then
                _git_text="no$_git_text"
            else
                _git_text="$_git_cnt$_git_text"
            fi
            update-git &
        fi
        bright=$(_brightness)
        muting=$(_sound)
        bat=$(_battery)
        disp=$($HOME/.bin/locking status)
        up=$(_up)
        echo "$_git_text$bright|$muting|$bat|$disp|$up|" > $MAIN_STATS
        _last_git=$((_last_git+1))
        if [ $_last_git -eq 1 ]; then
            _last_git=0
        fi
    done
}

stats
