#!/bin/bash
echo '{ "version": 1 }'
echo '[[],'

while : ; do
  dated=$(date +"%Y-%m-%dT%H:%M:%S")
  ipaddr=$(ip addr | grep "inet " | grep -v "127\.0\.0\.1" | awk '{print $2}' | tr '\n' ',' | sed 's/,$//g')
  ipcolor="ffffff"
  if [ -z "$ipaddr" ]; then
    ipcolor="ff0000"
    ipaddr="no network"
  fi
  cat << EOF
[
  {
    "full_text": " $ipaddr ",
    "color": "#$ipcolor"
  },
  {
    "full_text": " $dated"
  }
],
EOF
  sleep 1
done
