#!/bin/bash
source $HOME/.bin/common
SETUP="--install"

function sync-now()
{
    SYNC_TO="sync"
    available=$(test-ssh "$SYNC_TO")
    echo "====================="
    echo "running "$(date +%Y-%m-%dT%H:%M:%S)
    echo "====================="
    if [ ! -d $SSH_KEY_PATH ]; then
        echo "$SSH_KEY_PATH not mounted..."
        exit -1
    fi
    echo "checked for connection...$available"
    if [ $available -eq $IS_CONNECTED ]; then
        echo "### pulling in..."
        rsync -avzc -e ssh $SYNC_TO:~/Host/ $HOME/.cache/hosted/
        echo "### pushing sync..."
        cd ${SYNCED_PATH} && git push
        echo "### syncing out..."
        rsync -avzc --exclude "*.lock" --exclude ".gitignore" --exclude "*/" --delete-after ${SYNCED_PATH} -e ssh $SYNC_TO:~/Sync/
    fi
}

function install()
{
    sudo systemctl enable $HOME/.bin/sys/sync.timer
    sudo ln -s $HOME/.bin/sys/sync.service /etc/systemd/system/sync.service
    sudo systemctl start sync.timer
}

case $1 in
    $SETUP)
        install
        ;;
    *)
        sync-now | systemd-cat -t "sync"
        ;;
esac
