#!/bin/bash
source $HOME/.bin/common
source $HOME/.bin/connect-common
PID_FILE="$USER_TMP/syncing.pid"
SLEEP_FOR=5
ROTATION_COUNT=120
CHANGE_DELTA=1800
CHANGE_MOVE=10
SERVICE_NAME="syncing@enck.service"
SERVICE_FILE="$HOME/.bin/sys/$SERVICE_NAME"

function write-log()
{
    log-message "$SYNC_JOURNAL_CATEGORY" "$1"
}

function start-syncing()
{
    PID=$RANDOM
    echo $PID > $PID_FILE
    IS_READY="ok"
    SYNC_TO="sync"
    echo "Running as $PID"
    ROTATE_COUNT=0
    while [ -e $PID_FILE ]; do
        touch $PID_FILE
        CURRENT_PID=$(cat $PID_FILE)
        if [[ "$CURRENT_PID" != "$PID" ]]; then
            write-log "$CURRENT_PID is active sync process (not $PID)"
            exit -1
        fi
        if [ $ROTATE_COUNT -eq 0 ]; then
            available=$(test-ssh "$SYNC_TO")
            write-log "====================="
            write-log "running ($PID) "$(date +%Y-%m-%dT%H:%M:%S)
            write-log "====================="
            write-log "checked for connection...$available"
            if [ $available -eq $IS_CONNECTED ]; then
                rsync -avzc --delete-after /mnt/Synced/ -e ssh $SYNC_TO:~/Sync/
            fi
        fi
        sleep $SLEEP_FOR
        ROTATE_COUNT=$((ROTATE_COUNT+1))
        if [ $ROTATE_COUNT -gt $ROTATION_COUNT ]; then
            ROTATE_COUNT=0
        fi
        
        CURRENT_READ=$(date +%s)
        if [ -z "$LAST_READ" ]; then
            LAST_READ=$CURRENT_READ
        fi
        READ_DELTA=$((CURRENT_READ-LAST_READ))
        if [ $READ_DELTA -gt $CHANGE_DELTA ]; then
            write-log "noticed time jump ($CURRENT_READ - $LAST_READ) = $READ_DELTA"
            NEW_ROTATE=$((ROTATION_COUNT*CHANGE_MOVE/100))
            NEW_ROTATE=$((ROTATION_COUNT-NEW_ROTATE))
            if [ $ROTATE_COUNT -lt $NEW_ROTATE ]; then
                write-log "changing rotation to $NEW_ROTATE"
                ROTATE_COUNT=$NEW_ROTATE
            fi
        fi

        LAST_READ=$CURRENT_READ
    done
}

function stop-syncing()
{
    if [ -e $PID_FILE ]; then
        rm $PID_FILE
    fi
}

case $1 in
    $INSTALL_KEYWORD)
        sudo systemctl enable $SERVICE_FILE
        sudo ln -s $HOME/.bin/syncing /usr/local/bin/
        ;;
    $REMOVE_KEYWORD)
        sudo systemctl disable $SERVICE_NAME
        sudo rm /usr/local/bin/syncing
        ;;
    "start")
        start-syncing
        ;;
    "stop")
        stop-syncing
        ;;
    *)
        echo "unknown command: $1"
        ;;
esac

