#!/bin/bash
source $HOME/.bin/common
ARCHIVE=/tmp/profile.7z
function backup()
{
    today=$(date +%Y-%m-%d)
    backup=/tmp/.synced.$today
    if [ ! -e $backup ]; then
        rm -f $ARCHIVE
        7z a -t7z -bd $ARCHIVE /home/enck/.cache/home/ /home/enck/.mozilla/
        scp $ARCHIVE $BASE_SERVER:~/.profile.7z
        touch $backup
    fi
}

function sync-now()
{
    auth=$(cat $SSH_AUTH_TMP)
    export SSH_AUTH_SOCK=$auth
    available=$(test-ssh $BASE_SERVER)
    echo "====================="
    echo "running "$(date +%Y-%m-%dT%H:%M:%S)
    echo "====================="
    if [ ! -d $SSH_KEY_PATH ]; then
        echo "$SSH_KEY_PATH not mounted..."
        exit -1
    fi
    echo "checked for connection...$available"
    if [ $available -eq $IS_CONNECTED ]; then
        if [ -e $SSH_AUTH_TMP ]; then
            echo "git push"
            current=$PWD
            cd ${SYNCED_PATH}
            git push 2>&1
            for personal in $(ls ${PERM_LOCATION} | grep $PERM_PERSONAL); do
                echo "pushing $personal"
                cd ${PERM_LOCATION}/$personal
                git push 2>&1
            done
            cd $current
            echo "daily backup"
            backup
        else
            echo "ssh agent unavailable"
        fi
        date +%Y-%m-%d > $USER_LAST_SYNC
    fi
}

sync-now | systemd-cat -t "sync"
