#!/bin/bash
source $HOME/.bin/common
DUMP_TO=${SYNCED_PATH}config.dump.lock
DUMP_TO_OUT=${SYNCED_PATH}configurations.aes
CACHE_KEY=$HOME/.cache/crypt.key
PREV_CHECKS=$USER_TMP/configs.prev
CRNT_CHECKS=$USER_TMP/configs.crnt
DO_ZIPPING=0
SETUP="--install"
IGNORED_DIRS=".git"

function check-changes()
{
    res=$DO_ZIPPING
    rm -f $CRNT_CHECKS
    for d in $(find ${SYNCED_PATH}* -type d | grep -v -E "$IGNORED_DIRS" | sort); do
        for f in $(find ${d}* -type f | sort); do
            sha256sum $f >> $CRNT_CHECKS
        done
    done
    if [ -e $PREV_CHECKS ]; then
        diff $PREV_CHECKS $CRNT_CHECKS > /dev/null
        res=$?
    else
        res=2
    fi
    mv $CRNT_CHECKS $PREV_CHECKS
    echo $res
}

function zip-configs()
{
    echo "zipping configs ($DUMP_TO)..."
    for d in $(ls ${SYNCED_PATH} | grep -v -E "$IGNORED_DIRS"); do
        echo "zip $d ?..."
        if [ -d ${SYNCED_PATH}$d ]; then
            echo "yes"
            7z a $DUMP_TO ${SYNCED_PATH}$d/
        fi
    done
    echo "encrypting configs ($DUMP_TO_OUT)..."
    # call with -d to decrypt
    openssl aes-256-cbc -salt -in $DUMP_TO -out $DUMP_TO_OUT -kfile $HOME/.cache/crypt.key
    rm -f $DUMP_TO
}

function sync-now()
{
    SYNC_TO="sync"
    available=$(test-ssh "$SYNC_TO")
    echo "====================="
    echo "running "$(date +%Y-%m-%dT%H:%M:%S)
    echo "====================="
    echo "checked for connection...$available"
    if [ $available -eq $IS_CONNECTED ]; then
        if [ ! -e $CACHE_KEY ]; then
            echo "missing crypt key for caching config ($CACHE_KEY)..."
            exit -1
        fi
        do_zip=$(check-changes)
        echo "do zipping? $do_zip"
        if [ $do_zip -ne $DO_ZIPPING ]; then
            zip-configs
        fi
        rsync -avzc --exclude "*.lock" --exclude ".gitignore" --exclude "*/" --delete-after ${SYNCED_PATH} -e ssh $SYNC_TO:~/Sync/
    fi
}

function install()
{
    sudo systemctl enable $HOME/.bin/sys/sync.timer
    sudo ln -s $HOME/.bin/sys/sync.service /etc/systemd/system/sync.service
    sudo systemctl start sync.timer
}

case $1 in
    $SETUP)
        install
        ;;
    *)
        sync-now | systemd-cat -t "sync"
        ;;
esac
