#!/bin/sh
for FILE in $(ls); do
  TARGET=$(date +%d.T_%H%M%S).$(echo "$FILE" | sha256sum | cut -c 1-7)
  EXT=$(echo "$FILE" | tr '[:upper:]' '[:lower:]' | rev | cut -d "." -f 1 | rev)
  case "$EXT" in
    "jpeg" | "jpg")
      OUTPUT="$TARGET.jpeg"
      if ! mv "$FILE" "$OUTPUT"; then
        echo "failed to rename target"
        exit 1
      fi
      ;;
    "mov")
      OUTPUT="$TARGET.mp4"
      if ! ffmpeg -i "$FILE" -vcodec h264 "$OUTPUT"; then
        echo "failed to transcode via avconvert"
        exit 1
      fi
      ;;
    *)
      continue
      ;;
  esac
  echo "processed: $FILE"
  if [ -n "$OUTPUT" ]; then
    rm -f "$FILE"
  fi
done
