#!/bin/bash
UPSTREAM="$HOME/.cache/upstreams/"
CONF="$HOME/.config/voidedtech/upstream.yml"
mkdir -p "$UPSTREAM"
PKGS="$1"
VIM_PLUGINS="$HOME/.config/nvim/pack/plugins/start/"

_vim_plugin_update() {
  local name dir
  name=$(basename "$1")
  echo "updating: $name"
  dir="${VIM_PLUGINS}$name"
  if [ ! -d "$dir" ]; then
    if ! git clone "$1" "$dir"; then
      echo "failed to clone $name"
      exit 1
    fi
  fi
  if ! git -C "$dir" pull; then
    echo "failed to update $name"
    exit 1
  fi
}

_vim_plugins() {
  mkdir -p "$VIM_PLUGINS"
  _vim_plugin_update "https://github.com/vim-airline/vim-airline"
  _vim_plugin_update "https://github.com/neovim/nvim-lspconfig"
  _vim_plugin_update "https://github.com/hrsh7th/nvim-cmp"
  _vim_plugin_update "https://github.com/hrsh7th/cmp-nvim-lsp"
  _vim_plugin_update "https://github.com/L3MON4D3/LuaSnip"
}

_externals() {
  local r n curr prev changed cnt len
  if [ ! -e "$CONF" ]; then
    echo "no $CONFIG file"
    exit 1
  fi
  changed=0
  cnt=0
  len=$(yq '.sources | length' "$CONF")
  if [ -z "$len" ] || [ "$len" -le 0 ]; then
    echo "invalid sources"
    exit 1
  fi
  while [ "$cnt" -lt "$len" ]; do
    n=$(yq ".sources[$cnt].name" "$CONF")
    r=$(yq ".sources[$cnt].url" "$CONF")
    curr="${UPSTREAM}$n"
    prev="$curr.prev"
    echo "checking: $r ($n)"
    if ! git ls-remote --tags "$r" > "$curr"; then
      echo "failed to fetch: $r"
      exit 1
    fi
    if [ -e "$prev" ]; then
      if ! diff -u "$prev" "$curr"; then
        echo "$r has changed"
        if confirm "dismiss"; then
          mv "$curr" "$prev"
        fi
      fi
    else
      mv "$curr" "$prev"
    fi
    cnt=$((cnt+1))
  done
  exit $changed
}

mkdir -p "$UPSTREAM"
if [ -n "$1" ]; then
  if [ "$1" != "check" ]; then
    echo "unknown command"
    exit 1
  fi
  CNT=$(find $UPSTREAM -type f -mtime -7 | wc -l)
  if [ $CNT -eq 0 ]; then
    exit 1
  fi
  exit 0
fi
_vim_plugins
_externals
