#!/usr/bin/env bash
NVIM="$HOME/.config/nvim/"

_plugins() {
  echo "updating plugins..."
  if ! make --no-print-directory -C "$NVIM"; then
    echo "failed to update plugins"
    exit 1
  fi
  echo
}

_plugins
echo "syncing files..."
abw sync
