#!/bin/bash
source $HOME/.bin/common
MAIL_KEYWORD="mail"
SSID_KEYWORD="ssid"
SNAP_KEYWORD="snapshot"
TREE_KEYWORD="tree"
CHKSUM_KEYWORD="checksum"
WORKING=/opt/workspace/shared

function snapshot()
{
    STAGE=$USER_TMP/git/
    DATE=`date +%Y-%m-%d`
    SNAP_FILE=$PWD/snapshot-$DATE.tar.gz
    mkdir -p $STAGE
    for f in $(ls $WORKING); do
	    REPO="$WORKING/$f"
    	if [ -e "$REPO/.git" ]; then
    		cd $REPO
            echo "bundling $f"
		    git bundle create $STAGE$f.bundle --all &> /dev/null
    	fi
    done
    CUR_DIR=$PWD
    cd $STAGE && tar -cvzf $SNAP_FILE * && cd $CUR_DIR
    rm -rf $STAGE
}

function get-tree()
{
    tree .
}

function get-checksum()
{
    find -type f -exec sha512sum "{}" + | sort -k 2
}

function clear-mail()
{
    echo 'd *' | mail -N
}

function hidden-ssid()
{
    if [ -z "$1" ]; then
        echo "ssid required..."
        exit -1
    fi
    sudo iwlist wlp3s0 scanning essid $1
}

function print-help()
{
    echo "
$MAIL_KEYWORD (clear mail)
$SSID_KEYWORD (discover a hidden SSID)
$SNAP_KEYWORD (snapshot workspace)
$CHKSUM_KEYWORD (get checksum of files under this directory)
$TREE_KEYWORD (get file and directory tree structure)
"
}

case $1 in
    $MAIL_KEYWORD)
        clear-mail
        ;;
    $SSID_KEYWORD)
        hidden-ssid "$2"
        ;;
    $SNAP_KEYWORD)
        snapshot
        ;;
    $TREE_KEYWORD)
        get-tree
        ;;
    $CHKSUM_KEYWORD)
        get-checksum
        ;;
    *)
        print-help
        ;;
esac

