#!/bin/bash
VSCODE_PATH=/opt/apps/vscode
VSCODE_EXE=$VSCODE_PATH/Code
VSCODE_PAGE="/tmp/vscode-update.html"
VSCODE_UPDATE_FILE="/tmp/vscode-need-update"
UPDATE_URL="https://code.visualstudio.com/updates"

if [ -e $VSCODE_UPDATE_FILE ]; then
    rm $VSCODE_UPDATE_FILE
fi

if [ -e $VSCODE_PAGE ]; then
    VSCODE_AGE=$(stat -c %Y $VSCODE_PAGE)
    CURRENT=$(date +%s)
    DELTA=$((CURRENT - VSCODE_AGE))
    if [ $DELTA -gt 86400 ]; then
        rm $VSCODE_PAGE
    fi
fi

VSCODE_VER=$(cat $VSCODE_PATH/resources/app/package.json | grep "version" | cut -d ":" -f 2 | cut -d " " -f 2 | cut -d "," -f 1 | sed 's/"//g')
if [ ! -e $VSCODE_PAGE ]; then
    wget -qO- $UPDATE_URL > $VSCODE_PAGE
fi

UPDATE_AVAIL=""
cat $VSCODE_PAGE | grep "<h1>" | head -n 1 | grep -q "<h1>$VSCODE_VER"

if [ $? -ne 0 ]; then
    echo "Version: $VSCODE_VER" > $VSCODE_UPDATE_FILE
    echo "An update may be available" >> $VSCODE_UPDATE_FILE
    echo "$UPDATE_URL" >> $VSCODE_UPDATE_FILE
    ARGS=$VSCODE_UPDATE_FILE                
#    rm -f $VSCODE_PAGE
else
    ARGS="-n"
fi

$VSCODE_EXE $ARGS
