#!/usr/bin/env bash
_apps() {
  local w
  echo "firefox,firefox --new-window,app"
  echo "files,thunar,app"
  echo "terminal,alacritty,app"
  for w in "fastmail.com" "home.voidedtech.com" "voidedtech.com"; do
    echo "$w,$w,web"
  done
  for w in $(flatpak list --app --columns="application"); do
    echo "$(echo "$w" | rev | cut -d '.' -f 1 | rev | tr '[:upper:]' '[:lower:]'),flatpak run $w,app"
  done
}

_urlencode() {
  LC_ALL=C awk -- '
    BEGIN {
      for (i = 1; i <= 255; i++) hex[sprintf("%c", i)] = sprintf("%%%02X", i)
    }
    function urlencode(s,  c,i,r,l) {
      l = length(s)
      for (i = 1; i <= l; i++) {
        c = substr(s, i, 1)
        r = r "" (c ~ /^[-._~0-9a-zA-Z]$/ ? c : hex[c])
      }
      return r
    }
    BEGIN {
      for (i = 1; i < ARGC; i++)
        print urlencode(ARGV[i])
    }' "$@"
}

_menu() {
  local cnt chosen matched url
  cnt=$(_apps | wc -l)
  pkill bemenu
  chosen=$(_apps | sort | cut -d ',' -f 1 | bemenu -i -l "$cnt" -w -p "apps:")
  if [ -z "$chosen" ]; then
    return
  fi
  matched=$(_apps | grep "^$chosen," | grep ',app$' | cut -d "," -f 2)
  if [ -n "$matched" ]; then
    $matched
    return
  fi
  url=""
  if echo "$chosen" | grep -v -q " "; then
    if [ $(echo "$chosen" | tr '.' '\n' | wc -l) -gt 1 ]; then
      url="$chosen"
    fi
  fi
  if [ -z "$url" ]; then
    url="https://duckduckgo.com?q=$(_urlencode "$chosen")"
  fi
  firefox --new-window "$url"
}

_menu
