#!/bin/bash
ps aux | grep workspacing | grep "/bin/bash" | grep -q -v "$$"
if [ $? -eq 0 ]; then
    exit 0
fi
while [ 1 -eq 1 ]; do
    p=$(pidof workspacer)
    sleep 3
    if [ -z "$p" ]; then
        $HOME/.config/go/i3workspacer/workspacer &
    fi
done
