#!/bin/bash
source $HOME/.bin/common
source $HOME/.bin/displays
WORKSPACE_START="startup"
WORKSPACE_RELOAD="reload"
WORKSPACE_CHANGE="change"
CYCLING="cycle"
BACKGROUND_IMAGE=$HOME/.config/images/background.png
DEFAULT_WORKSPACE_ID=1
DOCKED_ID=2
DISP_HOLDER="DISPLAY_VALUE"
WORK_COMMON_LEFT="--output $DISP_HOLDER --auto --left-of $MAIN_DISPLAY --rotate right"
WORK_COMMON_RIGHT="--output $DISP_HOLDER --auto --right-of $MAIN_DISPLAY"
HOME_COMMON="--output $DISP_HOLDER --auto --left-of $MAIN_DISPLAY"

function replace-and-execute()
{
    VAL="xrandr "$(echo "$1" | sed "s/$DISP_HOLDER/$2/g")
    eval $VAL
}

function kill-icons()
{
    for pid in $(pgrep "python"); do
        ps $pid | grep -q "genericon"
        if [ $? -eq 0 ]; then
            kill $pid
        fi
    done
}

function set-workplace()
{
    use_dpi=192
    ALL_DISPLAYS=$(get-all-displays | grep -v "$MAIN_DISPLAY")
    has_side=0
    for disp in $ALL_DISPLAYS; do
        xrandr --output $disp --off
        xrandr | grep -q "^$disp connected"
        if [ $? -eq 0 ]; then
            has_side=1
        fi
    done
    xrandr --output $MAIN_DISPLAY --primary --auto
    use_setting=$1
    if [ $has_side -eq 0 ]; then
        use_setting=$DEFAULT_WORKSPACE_ID
    fi
    kill-icons
    rate=$DEFAULT_REFRESH
    case $use_setting in
        $DOCKED_ID | $HOME_WORKPLACE_ID)
            use_dpi=144
            rate=5000
            case $use_setting in
                $DOCKED_ID)
                    replace-and-execute "$WORK_COMMON_LEFT" "$DISP_ONE"
                    replace-and-execute "$WORK_COMMON_RIGHT" "$DISP_TWO"
                    ;;
                $HOME_WORKPLACE_ID)
                    replace-and-execute "$HOME_COMMON" "$HOME_DISP"
                    ;;
            esac
            rm -f $WORKPLACE_WORKING
            ;;
        *)
            touch $WORKPLACE_WORKING
            ;;
    esac
    status init $rate
    xrandr --dpi $use_dpi
    if [ $1 -eq $use_setting ]; then
        i3 restart
    fi
}

# Workspace help
function get-workspace-help()
{
    echo "
    $1 $2 $CYCLING (change the current workspace setup)
    $1 $2 $DEFAULT_WORKSPACE_ID (force default workspace)
    $1 $2 $DOCKED_ID (force docked workspace)
    $1 $2 $HOME_ID (change to home workspace)
    "
}

function force-workplace()
{
    if [[ "$1" == "$CYCLING" ]]; then
        WORKSPACE_NUM=$DEFAULT_WORKSPACE_ID
        if [ -e $WORKPLACE_WORKING ]; then
            WORKSPACE_NUM=$DOCKED_ID
        fi
        force-workplace $WORKSPACE_NUM
    else
        set-workplace $1
        if [ -e $BACKGROUND_IMAGE ]; then
            feh --bg-fill $BACKGROUND_IMAGE
        else
            xsetroot -solid "#333333"
        fi
    fi
}
