[applications.alpinevirt]
platforms = [
  { value = "{{ $.Config.OS }}-$HOST_OS", target = "linux-alpine" },
  { value = "{{ $.Config.OS }}-$HOST_OS", target = "linux-cusp" }
]
[applications.alpinevirt.web]
url = "https://gitlab.alpinelinux.org/alpine/aports/-/raw/{{ $.Getenv \"HOST_OS_VERSION\" }}-stable/main/linux-lts/APKBUILD?ref_type=heads"
scrape.filters = [
  "^pkgver=(.*)"
]
scrape.download = "{{ $.Vars.Source }}"
[applications.alpinevirt.extract]
command = [
    ["cp", "{{ $.Input }}", "{{ $.Output }}"],
    ["/bin/bash", "-c", "test -e APKBUILD || mv *.APKBUILD* APKBUILD"],
    ["/bin/bash", "-c", "diff --ignore-all-space -u <(grep -E '^(pkgver|pkgrel)=' APKBUILD | sort -r | cut -d '=' -f 2 | tr '\n' '-' | sed 's/$/virt/g') <(uname -r)"]
]
