[applications.kitty]
platforms = [
  { value = "{{ $.Config.OS }}", target = "darwin" }
]
[applications.kitty.github]
project = "kovidgoyal/kitty"
release = { asset = ".dmg$" }
[applications.kitty.extract]
skip = true
