[applications.rectangle]
platforms = [
  { value = "{{ $.Config.OS }}", target = "darwin" }
]
[applications.rectangle.github]
project = "rxhanson/Rectangle"
release = { asset = ".dmg$" }
[applications.rectangle.extract]
skip = true
