[applications.nvimscrollbar]
platforms = [
  { value = "{{ $.Config.OS }}-$EDITOR", target = "linux-nvim" }
]
[applications.nvimscrollbar.github]
project = "petertriho/nvim-scrollbar"
branch = { name = "main" }
[[applications.nvimscrollbar.commands.steps]]
command = ["rsync", "-ac", "--delete-after", ".", "$VIM_PLUGINS/nvim-scrollbar/"]

[applications.vimairline]
platforms = [
  { value = "{{ $.Config.OS }}", target = "linux" }
]
[applications.vimairline.github]
project = "vim-airline/vim-airline"
branch = { name = "master" }
[[applications.vimairline.commands.steps]]
command = ["rsync", "-ac", "--delete-after", ".", "$VIM_PLUGINS/vim-airline/"]

[applications.vimjust]
platforms = [
  { value = "{{ $.Config.OS }}", target = "linux" }
]
[applications.vimjust.github]
project = "NoahTheDuke/vim-just"
branch = { name = "main" }
[[applications.vimjust.commands.steps]]
command = ["rsync", "-ac", "--delete-after", ".", "$VIM_PLUGINS/vim-just/"]

[applications.toggleterm]
platforms = [
  { value = "{{ $.Config.OS }}-$EDITOR", target = "linux-nvim" }
]
[applications.toggleterm.github]
project = "akinsho/toggleterm.nvim"
branch = { name = "main" }
[[applications.toggleterm.commands.steps]]
command = ["rsync", "-ac", "--delete-after", ".", "$VIM_PLUGINS/toggleterm/"]

[applications.mini-completion]
platforms = [
  { value = "{{ $.Config.OS }}-$EDITOR", target = "linux-nvim" }
]
[applications.mini-completion.github]
project = "echasnovski/mini.completion"
branch = { name = "main" }
[[applications.mini-completion.commands.steps]]
command = ["rsync", "-ac", "--delete-after", ".", "$VIM_PLUGINS/mini.completion/"]

[applications.vimlsp]
flags = ["disabled"]
platforms = [
  { value = "{{ $.Config.OS }}-$EDITOR", target = "linux-vim" }
]
[applications.vimlsp.github]
project = "prabirshrestha/vim-lsp"
branch = { name = "master" }
[[applications.vimlsp.commands.steps]]
command = ["rsync", "-ac", "--delete-after", ".", "$VIM_PLUGINS/vim-lsp/"]

[applications.asyncomplete]
flags = ["disabled"]
platforms = [
  { value = "{{ $.Config.OS }}-$EDITOR", target = "linux-vim" }
]
[applications.asyncomplete.github]
project = "prabirshrestha/asyncomplete.vim"
branch = { name = "master" }
[[applications.asyncomplete.commands.steps]]
command = ["rsync", "-ac", "--delete-after", ".", "$VIM_PLUGINS/asyncomplete/"]

[applications.asyncompletelsp]
flags = ["disabled"]
platforms = [
  { value = "{{ $.Config.OS }}-$EDITOR", target = "linux-vim" }
]
[applications.asyncompletelsp.github]
project = "prabirshrestha/asyncomplete-lsp.vim"
branch = { name = "master" }
[[applications.asyncompletelsp.commands.steps]]
command = ["rsync", "-ac", "--delete-after", ".", "$VIM_PLUGINS/asyncomplete-lsp/"]

[applications.ale]
flags = ["disabled"]
platforms = [
  { value = "{{ $.Config.OS }}-$EDITOR", target = "linux-vim" }
]
[applications.ale.github]
project = "dense-analysis/ale"
branch = { name = "master" }
[[applications.ale.commands.steps]]
command = ["rsync", "-ac", "--delete-after", ".", "$VIM_PLUGINS/ale/"]

[applications.vimshellcheck]
platforms = [
  { value = "{{ $.Config.OS }}-$EDITOR", target = "linux-vim" }
]
[applications.vimshellcheck.github]
project = "itspriddle/vim-shellcheck"
branch = { name = "master" }
[[applications.vimshellcheck.commands.steps]]
command = ["rsync", "-ac", "--delete-after", ".", "$VIM_PLUGINS/vim-shellcheck/"]
