[applications.nvimscrollbar]
platforms = [
  { value = "{{ $.Config.OS }}-$EDITOR", target = "linux-nvim" }
]
[applications.nvimscrollbar.github]
project = "petertriho/nvim-scrollbar"
branch = { name = "main" }
[[applications.nvimscrollbar.commands.steps]]
command = ["rsync", "-ac", "--delete-after", ".", "$VIM_PLUGINS/nvim-scrollbar/"]

[applications.vimairline]
platforms = [
  { value = "{{ $.Config.OS }}", target = "linux" }
]
[applications.vimairline.github]
project = "vim-airline/vim-airline"
branch = { name = "master" }
[[applications.vimairline.commands.steps]]
command = ["rsync", "-ac", "--delete-after", ".", "$VIM_PLUGINS/vim-airline/"]

[applications.vimjust]
platforms = [
  { value = "{{ $.Config.OS }}", target = "linux" }
]
[applications.vimjust.github]
project = "NoahTheDuke/vim-just"
branch = { name = "main" }
[[applications.vimjust.commands.steps]]
command = ["rsync", "-ac", "--delete-after", ".", "$VIM_PLUGINS/vim-just/"]

[applications.toggleterm]
platforms = [
  { value = "{{ $.Config.OS }}-$EDITOR", target = "linux-nvim" }
]
[applications.toggleterm.github]
project = "akinsho/toggleterm.nvim"
branch = { name = "main" }
[[applications.toggleterm.commands.steps]]
command = ["rsync", "-ac", "--delete-after", ".", "$VIM_PLUGINS/toggleterm/"]

[applications.mini-completion]
platforms = [
  { value = "{{ $.Config.OS }}-$EDITOR", target = "linux-nvim" }
]
[applications.mini-completion.github]
project = "echasnovski/mini.completion"
branch = { name = "main" }
[[applications.mini-completion.commands.steps]]
command = ["rsync", "-ac", "--delete-after", ".", "$VIM_PLUGINS/mini.completion/"]

[applications.vimshellcheck]
platforms = [
  { value = "{{ $.Config.OS }}-$EDITOR", target = "linux-vim" }
]
[applications.vimshellcheck.github]
project = "itspriddle/vim-shellcheck"
branch = { name = "master" }
[[applications.vimshellcheck.commands.steps]]
command = ["rsync", "-ac", "--delete-after", ".", "$VIM_PLUGINS/vim-shellcheck/"]

[applications.vimqfdiag]
platforms = [
  { value = "{{ $.Config.OS }}-$EDITOR", target = "linux-vim" }
]
[applications.vimqfdiag.github]
project = "bfrg/vim-qf-diagnostics"
branch = { name = "master" }
[[applications.vimqfdiag.commands.steps]]
command = ["rsync", "-ac", "--delete-after", ".", "$VIM_PLUGINS/vim-qf-diagnostics/"]

[applications.vimgo]
platforms = [
  { value = "{{ $.Config.OS }}-$EDITOR", target = "linux-vim" }
]
[applications.vimgo.github]
project = "fatih/vim-go"
branch = { name = "master" }
[applications.vimgo.commands]
variables = [
  { key = "INSTALLDIR", value = "$VIM_PLUGINS/vim-go/" },
]
[[applications.vimgo.commands.steps]]
command = ["rsync", "-ac", "--delete-after", ".", "$INSTALLDIR"]
[[applications.vimgo.commands.steps]]
command = ["/bin/sh", "-c", "cd $INSTALLDIR && git apply $HOME/.config/blap/patches/0001.vim-go.diagnostics.patch"]

[applications.asyncomplete]
platforms = [
  { value = "{{ $.Config.OS }}-$EDITOR", target = "linux-vim" }
]
[applications.asyncomplete.github]
project = "prabirshrestha/asyncomplete.vim"
branch = { name = "master" }
[[applications.asyncomplete.commands.steps]]
command = ["rsync", "-ac", "--delete-after", ".", "$VIM_PLUGINS/asyncomplete.vim/"]
