# common plugins for both vim+neovim
[apps.vimairline]
platforms = [
  { value = "{{ $.Config.OS }}", target = "linux" }
]
[apps.vimairline.github]
project = "vim-airline/vim-airline"
branch = { name = "master" }
[[apps.vimairline.setup]]
commands = ["rsync", "-ac", "--delete-after", ".", "$VIM_PLUGINS/vim-airline/"]

[apps.vimjust]
platforms = [
  { value = "{{ $.Config.OS }}", target = "linux" }
]
[apps.vimjust.github]
project = "NoahTheDuke/vim-just"
branch = { name = "main" }
[[apps.vimjust.setup]]
commands = ["rsync", "-ac", "--delete-after", ".", "$VIM_PLUGINS/vim-just/"]

# ===
# neovim specific plugins
# ===
[apps.mini-completion]
platforms = [
  { value = "{{ $.Config.OS }}-$EDITOR", target = "linux-nvim" }
]
[apps.mini-completion.github]
project = "echasnovski/mini.completion"
branch = { name = "main" }
[[apps.mini-completion.setup]]
commands = ["rsync", "-ac", "--delete-after", ".", "$VIM_PLUGINS/mini.completion/"]

[apps.nvimscrollbar]
platforms = [
  { value = "{{ $.Config.OS }}-$EDITOR", target = "linux-nvim" }
]
[apps.nvimscrollbar.github]
project = "petertriho/nvim-scrollbar"
branch = { name = "main" }
[[apps.nvimscrollbar.setup]]
commands = ["rsync", "-ac", "--delete-after", ".", "$VIM_PLUGINS/nvim-scrollbar/"]

[apps.nvimlint]
platforms = [
  { value = "{{ $.Config.OS }}-$EDITOR", target = "linux-nvim" }
]
[apps.nvimlint.github]
project = "mfussenegger/nvim-lint"
branch = { name = "master" }
[[apps.nvimlint.setup]]
commands = ["rsync", "-ac", "--delete-after", ".", "$VIM_PLUGINS/nvim-lint/"]

# ===
# vim specific plugins
# ===
[apps.vimshellcheck]
platforms = [
  { value = "{{ $.Config.OS }}-$EDITOR", target = "linux-vim" }
]
[apps.vimshellcheck.github]
project = "itspriddle/vim-shellcheck"
branch = { name = "master" }
[[apps.vimshellcheck.setup]]
commands = ["rsync", "-ac", "--delete-after", ".", "$VIM_PLUGINS/vim-shellcheck/"]

[apps.vimqfdiag]
platforms = [
  { value = "{{ $.Config.OS }}-$EDITOR", target = "linux-vim" }
]
[apps.vimqfdiag.github]
project = "bfrg/vim-qf-diagnostics"
branch = { name = "master" }
[[apps.vimqfdiag.setup]]
commands = ["rsync", "-ac", "--delete-after", ".", "$VIM_PLUGINS/vim-qf-diagnostics/"]

[apps.vimgo]
platforms = [
  { value = "{{ $.Config.OS }}-$EDITOR", target = "linux-vim" }
]
variables = [
  { key = "INSTALLDIR", value = "$VIM_PLUGINS/vim-go/" },
]
[apps.vimgo.github]
project = "fatih/vim-go"
branch = { name = "master" }
[[apps.vimgo.setup]]
commands = ["rsync", "-ac", "--delete-after", ".", "$INSTALLDIR"]
[[apps.vimgo.setup]]
commands = ["/bin/sh", "-c", "cd $INSTALLDIR && git apply $HOME/.config/blap/patches/0001.vim-go.diagnostics.patch"]

[apps.asyncomplete]
platforms = [
  { value = "{{ $.Config.OS }}-$EDITOR", target = "linux-vim" }
]
[apps.asyncomplete.github]
project = "prabirshrestha/asyncomplete.vim"
branch = { name = "master" }
[[apps.asyncomplete.setup]]
commands = ["rsync", "-ac", "--delete-after", ".", "$VIM_PLUGINS/asyncomplete.vim/"]
