[applications.age]
platforms = [
  { value = "{{ $.Config.OS }}", target = "darwin"},
]
[applications.age.github]
project = "FiloSottile/age"
release = { asset = "{{ $.OS }}-{{ $.Arch }}.tar.gz$" }
[applications.age.commands]
[[applications.age.commands.steps]]
command = ["/bin/sh", "-c", "cat '{{ $.Vars.Tag }}.hash' | grep -q $(sha256sum $(ls ../*\"{{ $.Vars.File }}\") | cut -d ' ' -f 1)"]
[[applications.age.commands.steps]]
command = ["ln", "-sf", "{{ $.Vars.Directories.Root }}/{{ $.Name }}", "$LOCALBIN/"]
[[applications.age.commands.steps]]
command = ["ln", "-sf", "{{ $.Vars.Directories.Root }}/{{ $.Name }}-keygen", "$LOCALBIN/"]
