[applications]
  [applications.blap]
    [applications.blap.commands]

      [[applications.blap.commands.steps]]
        command = ["ln", "-sf", "{{ $.Vars.Directories.Root }}/{{ $.Name }}", "$LOCALBIN/"]

      [[applications.blap.commands.steps]]
        command = ["/bin/sh", "-c", "{{ $.Vars.Directories.Root }}$COMPGEN"]
    [applications.blap.github]
      project = "seanenck/blap"
      [applications.blap.github.release]
        asset = "{{ $.OS }}-{{ $.Arch }}.tar.gz$"
