[applications.blap]
platforms = [
  { value = "{{ $.Config.OS }}", target = "darwin"},
]
[applications.blap.github]
project = "seanenck/blap"
release = { asset = "{{ $.OS }}-{{ $.Arch }}.tar.gz$" }
[[applications.blap.setup]]
command = ["/bin/sh", "-c", "test -e '{{ $.Vars.NewFile \"hash\" }}' || curl --silent -L $(dirname '{{ $.Vars.URL }}')/'{{ $.Name }}-{{ slice $.Vars.Tag 1 }}-checksums.txt' | grep \"$(basename '{{ $.Vars.URL }}')\" > '{{ $.Vars.GetFile \"hash\" }}'"]
[[applications.blap.setup]]
command = ["/bin/sh", "-c", "cat '{{ $.Vars.GetFile \"hash\" }}' | grep -q $(sha256sum '{{ $.Vars.Archive }}' | cut -d ' ' -f 1)"]
[[applications.blap.setup]]
command = ["ln", "-sf", "{{ $.Vars.Directories.Root }}/{{ $.Name }}", "$LOCALBIN/"]
[[applications.blap.setup]]
command = ["/bin/sh", "-c", "{{ $.Vars.Directories.Root }}$COMPGEN"]
