[applications.delta.github]
project = "dandavison/delta"
release = { asset = ".{{ if eq $.Arch \"amd64\" }}x86_64{{ end }}(.*?){{ $.OS }}{{ if eq $.OS \"linux\" }}-gnu{{end}}(.*?).tar.gz$" }
[[applications.delta.commands.steps]]
command = ["ln", "-sf", "{{ $.Vars.Directories.Root }}/{{ $.Name }}", "$LOCALBIN/"]
