[apps.deno]
platforms = [
  { value = "{{ $.Config.OS }}", target = "linux" },
]
[apps.deno.github]
project = "denoland/deno"
release = { asset = "deno-{{ if eq $.Arch \"amd64\" }}x86_64{{ else }}aarch64{{end}}(.*?){{ $.OS }}-{{ $.Getenv \"LIBC\" }}(.*?).zip$" }
[[apps.deno.setup]]
commands = [
    ["/bin/sh", "-c", "test -e '{{ $.Vars.GetFile \"hash\" }}' || curl --silent -L '{{ $.Vars.URL }}.sha256sum' | grep \"$(basename '{{ $.Vars.URL }}')\" > '{{ $.Vars.GetFile \"hash\" }}'"],
    ["/bin/sh", "-c", "cat '{{ $.Vars.GetFile \"hash\" }}' | grep -q $(sha256sum '{{ $.Vars.Archive }}' | cut -d ' ' -f 1)"],
    ["ln", "-sf", "{{ $.Vars.Directories.Root }}/{{ $.Name }}", "$LOCALBIN/"],
    ["/bin/sh", "-c", "deno completions {{ if eq $.OS \"linux\" }}bash{{else}}zsh{{end}} > $COMPLETIONS/{{ $.Name }}"]
]
