[applications.gittools]
flags = ["disabled"]
platforms = [
  { value = "{{ $.Config.OS }}", target = "darwin"},
]
[applications.gittools.github]
project = "seanenck/git-tools"
release = { asset = "{{ $.OS }}-{{ $.Arch }}.tar.gz$" }
[[applications.gittools.setup]]
command = ["/bin/sh", "-c", "test -e '{{ $.Vars.NewFile \"hash\" }}' || curl --silent -L $(dirname '{{ $.Vars.URL }}')/'{{ $.Vars.File }}.sha256sum' > '{{ $.Vars.GetFile \"hash\" }}'"]
[[applications.gittools.setup]]
command = ["/bin/sh", "-c", "cat '{{ $.Vars.GetFile \"hash\" }}' | grep -q $(sha256sum '{{ $.Vars.Archive }}' | cut -d ' ' -f 1)"]
[[applications.gittools.setup]]
command = ["ln", "-sf", "{{ $.Vars.Directories.Root }}/git-uncommitted", "$LOCALBIN/"]
[[applications.gittools.setup]]
command = ["ln", "-sf", "{{ $.Vars.Directories.Root }}/git-motd", "$LOCALBIN/"]
[[applications.gittools.setup]]
command = ["ln", "-sf", "{{ $.Vars.Directories.Root }}/git-current-state", "$LOCALBIN/"]
