[applications.gittools]
platforms = [
  { value = "{{ $.Config.OS }}", target = "darwin"},
]
[applications.gittools.github]
project = "seanenck/git-tools"
release = { asset = "{{ $.OS }}-{{ $.Arch }}.tar.gz$" }
[[applications.gittools.commands.steps]]
command = ["/bin/sh", "-c", "test -e '{{ $.Vars.Tag }}.hash' || curl --silent -L $(dirname '{{ $.Vars.URL }}')/'{{ $.Vars.File }}.sha256sum' | grep \"$(basename '{{ $.Vars.URL }}')\" > '{{ $.Vars.Tag }}.hash'"]
[[applications.gittools.commands.steps]]
command = ["/bin/sh", "-c", "cat '{{ $.Vars.Tag }}.hash' | grep -q $(sha256sum $(ls ../*\"{{ $.Vars.File }}\") | cut -d ' ' -f 1)"]
[[applications.gittools.commands.steps]]
command = ["ln", "-sf", "{{ $.Vars.Directories.Root }}/git-uncommitted", "$LOCALBIN/"]
[[applications.gittools.commands.steps]]
command = ["ln", "-sf", "{{ $.Vars.Directories.Root }}/git-motd", "$LOCALBIN/"]
[[applications.gittools.commands.steps]]
command = ["ln", "-sf", "{{ $.Vars.Directories.Root }}/git-current-state", "$LOCALBIN/"]
