[applications.go]
priority = 100
platforms = [
  { value = "{{ $.Config.OS }}", target = "linux"},
]
[applications.go.git]
repository = "https://github.com/golang/go"
tagged.download = "https://go.dev/dl/{{ $.Vars.Tag }}.{{ $.OS }}-{{ $.Arch }}.tar.gz"
tagged.filters = [
  "^go[0-9]+[.][0-9]+[.][0-9]+$"
]
[[applications.go.commands.steps]]
command = ["/bin/sh", "-c", "test -e '{{ $.Vars.Tag }}.hash' || curl --silent -L 'https://go.dev/dl/' | grep '<tt>' > '{{ $.Vars.Tag }}.hash'"]
[[applications.go.commands.steps]]
command = ["/bin/sh", "-c", "cat '{{ $.Vars.Tag }}.hash' | grep -q $(sha256sum $(ls ../*\"{{ $.Vars.File }}\") | cut -d ' ' -f 1)"]
[[applications.go.commands.steps]]
command = ["ln", "-sf", "{{ $.Vars.Directories.Root }}/bin/{{ $.Name }}", "$LOCALBIN/"]
