[applications.go]
priority = 100
platforms = [
  { value = "{{ $.Config.OS }}", target = "linux"},
]
[applications.go.git]
repository = "https://github.com/golang/go"
tagged.download = "https://go.dev/dl/{{ $.Vars.Tag }}.{{ $.OS }}-{{ $.Arch }}.tar.gz"
tagged.filters = [
  "^go[0-9]+[.][0-9]+[.][0-9]+$"
]
[[applications.go.commands.steps]]
command = ["ln", "-sf", "{{ $.Vars.Directories.Root }}/bin/{{ $.Name }}", "$LOCALBIN/"]
