[applications.go]
priority = 100
platforms = [
  { value = "{{ $.Config.OS }}", target = "linux"},
]
[applications.go.git]
repository = "https://github.com/golang/go"
tagged.download = "https://go.dev/dl/{{ $.Vars.Tag }}.{{ $.OS }}-{{ $.Arch }}.tar.gz"
tagged.filters = [
  "^go[0-9]+[.][0-9]+[.][0-9]+$"
]
[[applications.go.setup]]
command = [
    ["/bin/sh", "-c", "test -e '{{ $.Vars.NewFile \"hash\" }}' || curl --silent -L 'https://go.dev/dl/' | grep '<tt>' > '{{ $.Vars.GetFile \"hash\" }}'"],
    ["/bin/sh", "-c", "cat '{{ $.Vars.GetFile \"hash\" }}' | grep -q $(sha256sum '{{ $.Vars.Archive }}' | cut -d ' ' -f 1)"],
    ["ln", "-sf", "{{ $.Vars.Directories.Root }}/bin/{{ $.Name }}", "$LOCALBIN/"]
]
