[apps.lb]
platforms = [
  { value = "{{ $.Config.OS }}", target = "darwin"},
]
[apps.lb.github]
project = "seanenck/lockbox"
release = { asset = "{{ $.OS }}-{{ $.Arch }}.tar.gz$" }
[[apps.lb.setup]]
commands = [
    ["/bin/sh", "-c", "test -e '{{ $.Vars.NewFile \"hash\" }}' || curl --silent -L $(dirname '{{ $.Vars.URL }}')/'lockbox-{{ slice $.Vars.Tag 1 }}-checksums.txt' | grep \"$(basename '{{ $.Vars.URL }}')\" > '{{ $.Vars.GetFile \"hash\" }}'"],
    ["/bin/sh", "-c", "cat '{{ $.Vars.GetFile \"hash\" }}' | grep -q $(sha256sum '{{ $.Vars.Archive }}' | cut -d ' ' -f 1)"],
    ["ln", "-sf", "{{ $.Vars.Directories.Root }}/{{ $.Name }}", "$LOCALBIN/"],
    ["/bin/sh", "-c", "{{ $.Vars.Directories.Root }}$COMPGEN"]
]
