[applications.lb]
platforms = [
  { value = "{{ $.Config.OS }}", target = "darwin"},
]
[applications.lb.github]
project = "seanenck/lockbox"
release = { asset = "{{ $.OS }}-{{ $.Arch }}.tar.gz$" }
[[applications.lb.commands.steps]]
command = ["ln", "-sf", "{{ $.Vars.Directories.Root }}/{{ $.Name }}", "$LOCALBIN/"]
[[applications.lb.commands.steps]]
command = ["/bin/sh", "-c", "{{ $.Vars.Directories.Root }}$COMPGEN"]
