[applications]
  [applications.nvim]
    [applications.nvim.commands]

      [[applications.nvim.commands.steps]]
        command = ["ln", "-sf", "{{ $.Vars.Directories.Root }}/bin/{{ $.Name }}", "$LOCALBIN/"]
    [applications.nvim.github]
      project = "neovim/neovim"
      [applications.nvim.github.release]
        asset = "nvim-{{ $.OS }}{{ if eq $.Arch \"amd64\" }}64{{ end }}.tar.gz$"
