[applications.rg]
platforms = [
  { value = "{{ $.Config.OS }}-$HOST_OS", target = "linux-fedora"},
  { value = "{{ $.Config.OS }}-$HOST_OS", target = "linux-opensuse-tumbleweed"}
]
[applications.rg.github]
project = "BurntSushi/ripgrep"
release = { asset = ".{{ if eq $.Arch \"amd64\" }}x86_64{{ end }}(.*?){{ $.OS }}(.*?).tar.gz$" }
[[applications.rg.commands.steps]]
command = ["ln", "-sf", "{{ $.Vars.Directories.Root }}/{{ $.Name }}", "$LOCALBIN/"]
