[applications.shellcheck]
platforms = [
  { value = "{{ $.Config.OS }}", target = "linux"},
]
[applications.shellcheck.github]
project = "koalaman/shellcheck"
release = { asset = "{{ $.OS }}.{{ if eq $.Arch \"amd64\" }}x86_64{{ else }}aarch64{{ end }}.tar.xz$" }
[[applications.shellcheck.commands.steps]]
command = ["/bin/sh", "-c", "if test ! -e '{{ $.Vars.Tag }}.hash'; then echo 'no {{ $.Vars.Tag }}.hash found for release'; exit 1; fi"]
[[applications.shellcheck.commands.steps]]
command = ["/bin/sh", "-c", "cat '{{ $.Vars.Tag }}.hash' | grep -q $(sha256sum $(ls ../*\"{{ $.Vars.File }}\") | cut -d ' ' -f 1)"]
[[applications.shellcheck.commands.steps]]
command = ["ln", "-sf", "{{ $.Vars.Directories.Root }}/{{ $.Name }}", "$LOCALBIN/"]
