[applications.shellcheck.github]
project = "koalaman/shellcheck"
release = { asset = "{{ $.OS }}.{{ if eq $.Arch \"amd64\" }}x86_64{{ end }}.tar.xz$" }
[[applications.shellcheck.commands.steps]]
command = ["ln", "-sf", "{{ $.Vars.Directories.Root }}/{{ $.Name }}", "$LOCALBIN/"]
