[applications.shellcheck]
platforms = [
  { value = "{{ $.Config.OS }}-$HOST_OS", target = "linux-fedora"},
  { value = "{{ $.Config.OS }}-$HOST_OS", target = "linux-opensuse-tumbleweed"}
]
[applications.shellcheck.github]
project = "koalaman/shellcheck"
release = { asset = "{{ $.OS }}.{{ if eq $.Arch \"amd64\" }}x86_64{{ else }}aarch64{{ end }}.tar.xz$" }
[[applications.shellcheck.commands.steps]]
command = ["ln", "-sf", "{{ $.Vars.Directories.Root }}/{{ $.Name }}", "$LOCALBIN/"]
