FROM alpine:latest

ARG COMMIT

RUN apk add --no-cache m4 make texlive-xetex texlive-full patch
RUN wget -O resume.zip https://github.com/enckse/resume/archive/$COMMIT.zip
RUN unzip resume.zip -d /resume
RUN mv /resume/resume-* /src

WORKDIR /src
COPY bin/build.sh build
COPY bin/env resume.env
RUN ./build personal
COPY bin/work.patch work.patch
RUN patch < work.patch
RUN ./build work
