#!/usr/bin/env bash
ABUILD_DIR=$HOME/.abuild
ABUILD_CONF=$ABUILD_DIR/abuild.conf
mkdir -p "$ABUILD_DIR"
{
	printf 'PACKAGER="Sean Enck <enckse@voidedtech.com>"\n'
	printf 'PACKAGER_PRIVKEY="/home/enck/.abuild/build@voidedtech.com.rsa"\n'
} > "$ABUILD_CONF"