#!/usr/bin/env bash
CACHE="$HOME/.cache/oclone.hst"
if [ ! -e "$CACHE" ]; then
  touch "$CACHE"
fi
if [ -z "$1" ]; then
  echo "argument required"
  exit 1
fi

_targets() {
  git config --list | grep insteadof | rev | cut -d "=" -f 1 | rev | sort -u
}

if [ "$1" == "--list" ]; then
  {
    _targets
    cat "$CACHE"
  } | sed 's#:#/#'
  exit 0
fi

TARGET="$(echo "$1" | sed 's#/#:#')"
if ! git clone "$TARGET"; then
  exit 1
fi
echo "$TARGET" >> "$CACHE"
sort -u -o "$CACHE" "$CACHE"
