#!/bin/bash
source /etc/voidedtech/skel/env
export GOPATH="$HOME/.cache/go"

IS_SCHROOT=0
if [ ! -z "$SCHROOT_CHROOT_NAME" ]; then
    IS_SCHROOT=1
fi

export IS_SCHROOT

if [ ! -d $HOME/.env/machine ]; then
    echo "no machine profile set"
fi

if [ ! -e ~/.vimrc ]; then
    ln -sf /etc/voidedtech/skel/vimrc ~/.vimrc
fi

if [ ! -d ~/.gnupg ]; then
    ln -sf ~/.private/gnupg ~/.gnupg
fi

pltidy() {
    local f
    for f in $(git grep "#\!/usr/bin/perl" | cut -d ":" -f 1 | sort); do
       perltidy $f
       mv $f.tdy $f
    done
}

glint() {
    local f
    goimports -l . | grep -v bindata.go | sed 's/^/[goimports]    /g'
    revive ./... | sed 's/^/[revive]       /g'
    for f in $(find . -type f -name "*.go" -exec dirname {} \; | sort -u); do
        go vet $f | sed 's/^/[govet]        /g'
    done
}

_cleanup-dirs() {
    local f check
    check=/tmp/.cleanup.$(date +%Y%m%d)
    if [ -e $check ]; then
        return
    fi
    for f in swap undo backup; do
        find $HOME/.vim/$f -type f -mtime +1 -delete
    done
    touch $check
}

_messaging() {
    systemctl --user enable drudge-session@messaging.service
}

if [ $IS_SCHROOT -eq 0 ]; then
    if [ -d "$HOME/.gnupg" ]; then
        unset SSH_AGENT_PID
        if [ "${gnupg_SSH_AUTH_SOCK_by:-0}" -ne $$ ]; then
            export SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"
        fi

        export GPG_TTY=$(tty)
        gpg-connect-agent updatestartuptty /bye >/dev/null
    else
        echo "no .gnupg dir"
    fi

    _cleanup-dirs
    _messaging
fi
