export GOPATH="$HOME/Library/Caches/go"
export PATH="/opt/local/libexec/gnubin:/opt/local/bin:/opt/local/sbin:$PATH"
export DISPLAY=:0
export LOCAL_CACHE="$HOME/Library/Caches/com.voidedtech.Local"

source /opt/local/share/bash-completion/bash_completion
source /Applications/kitty.app/Contents/Resources/kitty/shell-integration/bash/kitty.bash

_localcomp() {
    local c f
    c=$LOCAL_FS/usr/local/share/bash-completion
    if [ -d "$c" ]; then
        for f in $(find $c -type f); do
            source $f
        done
    fi
}

_gpga() {
    CACHE=$LOCAL_CACHE/gpg/
    mkdir -p $CACHE
    find $CACHE -type f -mtime +2 -delete
    FILE=${CACHE}$(date +%Y-%m-%d)
    if [ ! -e $FILE ]; then
        killall gpg-agent 2>/dev/null
        touch $FILE
    fi
}

_vmrlist() {
    local f has
    has=""
    for f in $(vmr up 2>/dev/null); do
        if [ -z "$has" ]; then
            has="yes"
            echo "vmr:"
        fi
        echo "  -> $f"
    done
    if [ ! -z "$has" ]; then
        echo
    fi
}

_localcomp
_gpga
export GPG_TTY=$(tty)
git uncommitted
_vmrlist
