#!/bin/bash
_mounting()
{
    local cur opts 
    if [ $COMP_CWORD -eq 1 ]; then
        cur=${COMP_WORDS[COMP_CWORD]}
        opts=$(mounting | grep -v "^$" | cut -d " " -f 3)
        COMPREPLY=( $(compgen -W "$opts" -- $cur) )
    fi
}
complete -F _mounting mounting
