#!/bin/bash
source $HOME/.bin/ssh-nspawn-common
_ssh-nspawn()
{
    local cur prev opts cmd host item
    cur=${COMP_WORDS[COMP_CWORD]}
    prev=${COMP_WORDS[COMP_CWORD-1]}
    if [ $COMP_CWORD -eq 1 ]; then
        opts=$(ssh-nspawn $SSH_NSPAWN_HOSTS | cut -d " " -f 1)
        COMPREPLY=( $(compgen -W "$opts" -- $cur) )
    else
        cmd=""
        for item in $(ssh-nspawn $SSH_NSPAWN_HOSTS); do
            if [[ $item == $prev ]]; then
                cmd="$SSH_NSPAWN_CONTAINERS $prev"
                break
            fi
        done 
        if [ ! -z "$cmd" ]; then
            opts=$(ssh-nspawn $cmd)
            COMPREPLY=( $(compgen -W "$opts" -- $cur) ) 
        fi
    fi
}
complete -F _ssh-nspawn ssh-nspawn
