directory: ~/.local/fs
applications:
  go:
    mode: "tagged"
    remote:
      upstream: "https://github.com/golang/go"
      download: "https://go.dev/dl/{{ $.Tag }}.linux-amd64.tar.gz"
      filters: 
        - "refs/tags/weekly"
        - "refs/tags/release"
        - "[0-9]rc[0-9]"
    binaries:
      files:
        - "bin/go"
      destination: "~/.local/bin/developer"
  rg:
    mode: "github"
    remote:
      upstream: "BurntSushi/ripgrep"
      asset: "x86_64-unknown-linux-(.+?).tar.gz$"
    binaries:
      files:
        - "rg"
      destination: "~/.local/bin"
  nvim:
    mode: "github"
    remote:
      upstream: "neovim/neovim"
      asset: "nvim-linux64.tar.gz$"
    binaries:
      files:
        - "bin/nvim"
      destination: "~/.local/bin"
  rclone:
    mode: "github"
    remote:
      upstream: "rclone/rclone"
      asset: "rclone-(.+?)-osx-arm64.zip"
  bat:
    mode: "github"
    remote:
      upstream: "sharkdp/bat"
      asset: "x86_64-unknown-linux-gnu.tar.gz$"
    binaries:
      files:
        - "bat"
      destination: "~/.local/bin"
  delta:
    mode: "github"
    remote:
      upstream: "dandavison/delta"
      asset: "x86_64-unknown-linux-gnu.tar.gz$"
    binaries:
      files:
        - "delta"
      destination: "~/.local/bin"
  efm:
    mode: "github"
    remote:
      upstream: "mattn/efm-langserver"
      asset: "linux_amd64.tar.gz$"
    binaries:
      files:
        - "efm-langserver"
      destination: "~/.local/bin"
  lb:
    mode: "github"
    remote:
      upstream: "seanenck/lockbox"
      asset: "linux-amd64.tar.gz$"
    extract:
      command: ["tar", "xf", "{INPUT}", "-C", "{OUTPUT}"]
    binaries:
      files:
        - "lb"
      destination: "~/.local/bin/lockbox"
