directory: ~/.local/fs
token: ~/.local/state/bd.token
applications:
  go:
    disable: true
    mode: "tagged"
    remote:
      upstream: "https://github.com/golang/go"
      download: "https://go.dev/dl/{{ $.Tag }}.linux-amd64.tar.gz"
      filters: 
        - "refs/tags/weekly"
        - "refs/tags/release"
        - "[0-9]rc[0-9]"
    binaries:
      files:
        - "bin/go"
      destination: "~/.local/bin/development"
  rg:
    disable: true
    mode: "github"
    remote:
      upstream: "BurntSushi/ripgrep"
      asset: "x86_64-unknown-linux-(.+?).tar.gz$"
    binaries:
      files:
        - "rg"
      destination: "~/.local/bin"
  nvim:
    disable: true
    mode: "github"
    remote:
      upstream: "neovim/neovim"
      asset: "nvim-linux64.tar.gz$"
    binaries:
      files:
        - "bin/nvim"
      destination: "~/.local/bin"
  rclone:
    mode: "github"
    remote:
      upstream: "rclone/rclone"
      asset: "rclone-(.+?)-osx-arm64.zip"
  bat:
    disable: true
    mode: "github"
    remote:
      upstream: "sharkdp/bat"
      asset: "x86_64-unknown-linux-gnu.tar.gz$"
    binaries:
      files:
        - "bat"
      destination: "~/.local/bin"
  delta:
    disable: true
    mode: "github"
    remote:
      upstream: "dandavison/delta"
      asset: "x86_64-unknown-linux-gnu.tar.gz$"
    binaries:
      files:
        - "delta"
      destination: "~/.local/bin"
  efm:
    disable: true
    mode: "github"
    remote:
      upstream: "mattn/efm-langserver"
      asset: "linux_amd64.tar.gz$"
    binaries:
      files:
        - "efm-langserver"
      destination: "~/.local/bin/development"
  lb:
    mode: "github"
    remote:
      upstream: "seanenck/lockbox"
      asset: "linux-amd64.tar.gz$"
    binaries:
      files:
        - "lb"
      destination: "~/.local/bin/development"
  bd:
    mode: "github"
    remote:
      upstream: "seanenck/bd"
      asset: "linux-amd64.tar.gz$"
    binaries:
      files:
        - "bd"
      destination: "~/.local/bin"
  age:
    disable: true
    mode: "github"
    remote:
      upstream: "FiloSottile/age"
      asset: "linux-amd64.tar.gz$"
    binaries:
      files:
        - "age"
      destination: "~/.local/bin/host"
  shellcheck:
    disable: true
    mode: "github"
    remote:
      upstream: "koalaman/shellcheck"
      asset: "linux.x86_64.tar.xz$"
    binaries:
      files:
        - "shellcheck"
      destination: "~/.local/bin"
