[colors.bright]
black = "#767676"
blue = "#4b94ff"
cyan = "#ffffff"
green = "#cff72f"
magenta = "#ff7001"
red = "#ff0000"
white = "#ffffff"
yellow = "#62fd62"

[colors.normal]
black = "#151515"
blue = "#4b94ff"
cyan = "#ffffff"
green = "#cff72f"
magenta = "#ff7001"
red = "#ff4d4d"
white = "#d0d0d0"
yellow = "#62fd62"

[colors.primary]
background = "#101010"
foreground = "#c0c0c0"

[font]
size = 13.5

[font.normal]
family = "monospace"

[[keyboard.bindings]]
action = "Paste"
key = "P"
mods = "Control"

[[keyboard.bindings]]
action = "Copy"
key = "Y"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "S"
mods = "Super"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "S"
mode = "Vi|~Search"
mods = "Super"

[[keyboard.bindings]]
action = "SearchNext"
key = "N"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "SearchPrevious"
key = "P"
mode = "Vi|~Search"

[scrolling]
history = 50000
