#!/usr/bin/env bash
ABUILD_DIR=$HOME/.abuild
ABUILD_CONF=$ABUILD_DIR/abuild.conf
mkdir -p "$ABUILD_DIR"
{
	printf 'PACKAGER="Sean Enck <enckse@voidedtech.com>"\n'
    printf 'PACKAGER_PRIVKEY=%s/.abuild/enckse@voidedtech.com.rsa\n' "$HOME"
	printf 'export GOFLAGS="-trimpath -buildmode=pie -mod=readonly -modcacherw -buildvcs=false"'
} > "$ABUILD_CONF"
