#!/usr/bin/env bash
ABUILD_DIR=$HOME/.abuild
ABUILD_CONF=$ABUILD_DIR/abuild.conf
mkdir -p "$ABUILD_DIR"

_abuild-conf() {
  local k
  printf 'PACKAGER="Sean Enck <enckse@voidedtech.com>"\n'
  for k in "$ABUILD_DIR/"*.rsa; do
    printf 'PACKAGER_PRIVKEY=%s\n' "$k"
  done
  printf 'export GOFLAGS="-trimpath -buildmode=pie -mod=readonly -modcacherw -buildvcs=false"'
} 

_abuild-conf > "$ABUILD_CONF"
