[user]
name = "Sean Enck"
email = "enckse@voidedtech.com"

[templates]
log = 'builtin_log_detailed'

[ui]
pager = ["sh", "-c", "bat | less -RFX"]
diff.format = "git"

[aliases]
log-all = ["log", "-r", "all()"]
