#!/usr/bin/env bash
PACK="$HOME/.config/nvim/pack/plugins/start/"
PLUGINS=(
  "https://github.com/neovim/nvim-lspconfig" \
  "https://github.com/akinsho/toggleterm.nvim" \
  "https://github.com/hrsh7th/nvim-cmp" \
  "https://github.com/hrsh7th/cmp-nvim-lsp" \
  "https://github.com/L3MON4D3/LuaSnip" \
  "https://github.com/vim-airline/vim-airline"
)

_plugins() {
  local bname url dest
  for url in "${PLUGINS[@]}"; do
    bname=$(basename "$url")
    echo "========="
    echo "$bname"
    echo "========="
    dest="$PACK/$bname"
    if [ ! -d "$dest" ]; then
      if ! git clone "$url" "$dest" --single-branch; then
        echo "unable to clone"
        exit 1
      fi
    else
      if ! git -C "$dest" pull origin "$(git -C "$dest" rev-parse --abbrev-ref HEAD)"; then
        echo "failed to pull updates"
        exit 1
      fi
    fi
  done
}

_plugins
