#!/usr/bin/env bash
PACK="$HOME/.config/nvim/pack/plugins/start/"
PLUGINS=(
  "https://github.com/neovim/nvim-lspconfig" \
  "https://github.com/akinsho/toggleterm.nvim" \
  "https://github.com/nvimdev/guard.nvim" \
  "https://github.com/echasnovski/mini.nvim"
)

if [ -z "$1" ]; then
  echo "command required"
  exit 1
fi
CMD="$1"
case "$CMD" in
  "init")
    ;;
  "update")
    ;;
  *)
    echo "unknown command: $CMD"
    exit 1
    ;;
esac

_plugins() {
  local bname url dest
  if [ "$CMD" == "update" ]; then
    date
    echo "updating plugins..."
  fi
  for url in "${PLUGINS[@]}"; do
    bname=$(basename "$url")
    if [ "$CMD" == "update" ]; then
      echo "$CMD: $bname"
    fi
    dest="$PACK/$bname"
    if [ ! -d "$dest" ]; then
      if ! git clone "$url" "$dest" --single-branch; then
        echo "unable to clone"
        exit 1
      fi
    else
      if [ "$CMD" == "init" ]; then
        continue
      fi
    fi
    if ! git -C "$dest" pull origin "$(git -C "$dest" rev-parse --abbrev-ref HEAD)"; then
      echo "failed to pull updates"
      exit 1
    fi
  done
}

_plugins
