theme = "monokai"

[editor]
middle-click-paste = false
auto-pairs = false
bufferline = "always"

[keys.normal]
C-c = "yank_main_selection_to_clipboard"
esc = "exit_select_mode"
tab = "goto_next_buffer"
S-tab = "goto_previous_buffer"
[keys.select]
C-c = "yank_main_selection_to_clipboard"
esc = "exit_select_mode"

