name: "build"

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  alpine-build:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - uses: actions/checkout@v4
      - name: "deps"
        run: apk add deno make
      - name: "build"
        run: cd src && make
